// Tests for <algorithm> — Part 1 (classic non-ranges algorithms)
// No main(); auto-generated by tools/gen_main.sh
#include <algorithm>
#include "test.h"

// ======== min / max / minmax / clamp ========

void test_algorithm_min() {
    static_assert(std::min(1, 2) == 1);
    static_assert(std::min(2, 1) == 1);
    static_assert(std::min(3, 3) == 3);
    static_assert(std::min(1, 2, std::greater<int>{}) == 2);
    static_assert(std::min({3, 1, 4, 1, 5}) == 1);
    static_assert(std::min({3, 1, 4}, std::greater<int>{}) == 4);
}

void test_algorithm_max() {
    static_assert(std::max(1, 2) == 2);
    static_assert(std::max(2, 1) == 2);
    static_assert(std::max(3, 3) == 3);
    static_assert(std::max(1, 2, std::greater<int>{}) == 1);
    static_assert(std::max({3, 1, 4, 1, 5}) == 5);
    static_assert(std::max({3, 1, 4}, std::greater<int>{}) == 1);
}

void test_algorithm_minmax() {
    // minmax returns pair<const T&, const T&> so can't be constexpr in all contexts
    auto p1 = std::minmax(1, 2);
    CHECK(p1.first == 1 && p1.second == 2);
    auto p2 = std::minmax(2, 1);
    CHECK(p2.first == 1 && p2.second == 2);
    auto p3 = std::minmax(3, 3);
    CHECK(p3.first == 3 && p3.second == 3);
    // initializer_list overload returns pair<T,T>
    constexpr auto p4 = std::minmax({3, 1, 4, 1, 5});
    static_assert(p4.first == 1 && p4.second == 5);
}

void test_algorithm_clamp() {
    static_assert(std::clamp(3, 1, 5) == 3);
    static_assert(std::clamp(0, 1, 5) == 1);
    static_assert(std::clamp(7, 1, 5) == 5);
    static_assert(std::clamp(1, 1, 5) == 1);
    static_assert(std::clamp(5, 1, 5) == 5);
    static_assert(std::clamp(3, 1, 5, std::less<int>{}) == 3);
}

// ======== min_element / max_element / minmax_element ========

void test_algorithm_min_element() {
    int a[] = {3, 1, 4, 1, 5, 9, 2};
    auto it = std::min_element(a, a + 7);
    CHECK(*it == 1);
    CHECK(it == a + 1);

    int b[] = {5};
    CHECK(std::min_element(b, b + 1) == b);

    // empty
    CHECK(std::min_element(b, b) == b);

    // with comparator
    auto it2 = std::min_element(a, a + 7, std::greater<int>{});
    CHECK(*it2 == 9);
}

void test_algorithm_max_element() {
    int a[] = {3, 1, 4, 1, 5, 9, 2};
    auto it = std::max_element(a, a + 7);
    CHECK(*it == 9);
    CHECK(it == a + 5);

    auto it2 = std::max_element(a, a + 7, std::greater<int>{});
    CHECK(*it2 == 1);
}

void test_algorithm_minmax_element() {
    int a[] = {3, 1, 4, 1, 5, 9, 2, 6};
    auto [mn, mx] = std::minmax_element(a, a + 8);
    CHECK(*mn == 1);
    CHECK(*mx == 9);
}

// ======== all_of / any_of / none_of ========

void test_algorithm_all_of() {
    int a[] = {2, 4, 6, 8};
    CHECK(std::all_of(a, a + 4, [](int x){ return x % 2 == 0; }));
    CHECK(!std::all_of(a, a + 4, [](int x){ return x > 4; }));
    // empty range -> true
    CHECK(std::all_of(a, a, [](int){ return false; }));
}

void test_algorithm_any_of() {
    int a[] = {1, 3, 5, 6};
    CHECK(std::any_of(a, a + 4, [](int x){ return x % 2 == 0; }));
    CHECK(!std::any_of(a, a + 3, [](int x){ return x % 2 == 0; }));
    // empty -> false
    CHECK(!std::any_of(a, a, [](int){ return true; }));
}

void test_algorithm_none_of() {
    int a[] = {1, 3, 5, 7};
    CHECK(std::none_of(a, a + 4, [](int x){ return x % 2 == 0; }));
    CHECK(!std::none_of(a, a + 4, [](int x){ return x > 4; }));
    // empty -> true
    CHECK(std::none_of(a, a, [](int){ return true; }));
}

// ======== for_each / for_each_n ========

void test_algorithm_for_each() {
    int a[] = {1, 2, 3, 4};
    int sum = 0;
    std::for_each(a, a + 4, [&](int x){ sum += x; });
    CHECK(sum == 10);
}

void test_algorithm_for_each_n() {
    int a[] = {1, 2, 3, 4, 5};
    int sum = 0;
    auto it = std::for_each_n(a, 3, [&](int x){ sum += x; });
    CHECK(sum == 6);
    CHECK(it == a + 3);
}

// ======== count / count_if ========

void test_algorithm_count() {
    int a[] = {1, 2, 3, 2, 1};
    CHECK(std::count(a, a + 5, 2) == 2);
    CHECK(std::count(a, a + 5, 7) == 0);
    CHECK(std::count(a, a, 1) == 0);
}

void test_algorithm_count_if() {
    int a[] = {1, 2, 3, 4, 5};
    CHECK(std::count_if(a, a + 5, [](int x){ return x % 2 == 0; }) == 2);
    CHECK(std::count_if(a, a + 5, [](int x){ return x > 10; }) == 0);
}

// ======== mismatch ========

void test_algorithm_mismatch() {
    int a[] = {1, 2, 3, 4};
    int b[] = {1, 2, 5, 4};
    auto [p1, p2] = std::mismatch(a, a + 4, b, b + 4);
    CHECK(p1 == a + 2 && p2 == b + 2);

    // equal ranges
    auto [q1, q2] = std::mismatch(a, a + 4, a, a + 4);
    CHECK(q1 == a + 4 && q2 == a + 4);

    // 3-iterator version
    auto [r1, r2] = std::mismatch(a, a + 4, b);
    CHECK(r1 == a + 2 && r2 == b + 2);
}

// ======== equal ========

void test_algorithm_equal() {
    int a[] = {1, 2, 3};
    int b[] = {1, 2, 3};
    int c[] = {1, 2, 4};
    CHECK(std::equal(a, a + 3, b, b + 3));
    CHECK(!std::equal(a, a + 3, c, c + 3));
    // 3-iter
    CHECK(std::equal(a, a + 3, b));
    CHECK(!std::equal(a, a + 3, c));
    // different lengths
    CHECK(!std::equal(a, a + 3, b, b + 2));
    // with pred
    CHECK(std::equal(a, a + 3, b, b + 3, std::equal_to<int>{}));
}

// ======== find / find_if / find_if_not ========

void test_algorithm_find() {
    int a[] = {1, 2, 3, 4, 5};
    CHECK(std::find(a, a + 5, 3) == a + 2);
    CHECK(std::find(a, a + 5, 7) == a + 5);
}

void test_algorithm_find_if() {
    int a[] = {1, 3, 5, 4, 7};
    auto it = std::find_if(a, a + 5, [](int x){ return x % 2 == 0; });
    CHECK(it == a + 3 && *it == 4);
    auto it2 = std::find_if(a, a + 3, [](int x){ return x % 2 == 0; });
    CHECK(it2 == a + 3);
}

void test_algorithm_find_if_not() {
    int a[] = {2, 4, 6, 5, 8};
    auto it = std::find_if_not(a, a + 5, [](int x){ return x % 2 == 0; });
    CHECK(it == a + 3 && *it == 5);
}

// ======== find_end ========

void test_algorithm_find_end() {
    int a[] = {1, 2, 3, 1, 2, 3, 1, 2};
    int pat[] = {1, 2, 3};
    auto it = std::find_end(a, a + 8, pat, pat + 3);
    CHECK(it == a + 3);

    // not found
    int pat2[] = {4, 5};
    auto it2 = std::find_end(a, a + 8, pat2, pat2 + 2);
    CHECK(it2 == a + 8);

    // empty pattern -> returns last
    auto it3 = std::find_end(a, a + 8, pat, pat);
    CHECK(it3 == a + 8);
}

// ======== find_first_of ========

void test_algorithm_find_first_of() {
    int a[] = {1, 2, 3, 4, 5};
    int b[] = {3, 5, 7};
    auto it = std::find_first_of(a, a + 5, b, b + 3);
    CHECK(it == a + 2 && *it == 3);

    int c[] = {8, 9};
    auto it2 = std::find_first_of(a, a + 5, c, c + 2);
    CHECK(it2 == a + 5);
}

// ======== adjacent_find ========

void test_algorithm_adjacent_find() {
    int a[] = {1, 2, 3, 3, 4};
    auto it = std::adjacent_find(a, a + 5);
    CHECK(it == a + 2 && *it == 3);

    int b[] = {1, 2, 3, 4};
    auto it2 = std::adjacent_find(b, b + 4);
    CHECK(it2 == b + 4);

    // with pred
    int c[] = {1, 3, 2, 4};
    auto it3 = std::adjacent_find(c, c + 4, std::greater<int>{});
    CHECK(it3 == c + 1);
}

// ======== search ========

void test_algorithm_search() {
    int a[] = {1, 2, 3, 4, 5};
    int pat[] = {3, 4};
    auto it = std::search(a, a + 5, pat, pat + 2);
    CHECK(it == a + 2);

    int pat2[] = {5, 6};
    auto it2 = std::search(a, a + 5, pat2, pat2 + 2);
    CHECK(it2 == a + 5);

    // empty pattern -> returns first
    auto it3 = std::search(a, a + 5, pat, pat);
    CHECK(it3 == a);
}

// ======== search_n ========

void test_algorithm_search_n() {
    int a[] = {1, 2, 2, 2, 3};
    auto it = std::search_n(a, a + 5, 3, 2);
    CHECK(it == a + 1);

    auto it2 = std::search_n(a, a + 5, 4, 2);
    CHECK(it2 == a + 5);

    auto it3 = std::search_n(a, a + 5, 0, 2);
    CHECK(it3 == a);
}

// ======== copy / copy_if / copy_n / copy_backward ========

void test_algorithm_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    std::copy(src, src + 5, dst);
    CHECK(dst[0] == 1 && dst[4] == 5);
}

void test_algorithm_copy_if() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    auto end = std::copy_if(src, src + 5, dst, [](int x){ return x % 2 == 0; });
    CHECK(end - dst == 2);
    CHECK(dst[0] == 2 && dst[1] == 4);
}

void test_algorithm_copy_n() {
    int src[] = {10, 20, 30, 40};
    int dst[4] = {};
    auto end = std::copy_n(src, 3, dst);
    CHECK(end == dst + 3);
    CHECK(dst[0] == 10 && dst[2] == 30 && dst[3] == 0);
}

void test_algorithm_copy_backward() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    std::copy_backward(src, src + 5, dst + 5);
    CHECK(dst[0] == 1 && dst[4] == 5);

    // Overlapping: shift right by 1
    int a[] = {1, 2, 3, 4, 5};
    std::copy_backward(a, a + 4, a + 5);
    CHECK(a[1] == 1 && a[4] == 4);
}

// ======== move / move_backward ========

void test_algorithm_move() {
    int src[] = {1, 2, 3};
    int dst[3] = {};
    std::move(src, src + 3, dst);
    CHECK(dst[0] == 1 && dst[2] == 3);
}

void test_algorithm_move_backward() {
    int a[] = {1, 2, 3, 4, 5};
    std::move_backward(a, a + 4, a + 5);
    CHECK(a[1] == 1 && a[4] == 4);
}

// ======== fill / fill_n ========

void test_algorithm_fill() {
    int a[5] = {};
    std::fill(a, a + 5, 7);
    for (int i = 0; i < 5; ++i) CHECK(a[i] == 7);
    std::fill(a, a, 99);
    CHECK(a[0] == 7); // empty range, no change
}

void test_algorithm_fill_n() {
    int a[5] = {};
    auto end = std::fill_n(a, 3, 42);
    CHECK(end == a + 3);
    CHECK(a[0] == 42 && a[2] == 42 && a[3] == 0);
}

// ======== transform ========

void test_algorithm_transform() {
    int src[] = {1, 2, 3, 4};
    int dst[4] = {};
    std::transform(src, src + 4, dst, [](int x){ return x * 2; });
    CHECK(dst[0] == 2 && dst[3] == 8);

    int dst2[4] = {};
    int src2[] = {10, 10, 10, 10};
    std::transform(src, src + 4, src2, dst2, std::plus<int>{});
    CHECK(dst2[0] == 11 && dst2[3] == 14);
}

// ======== generate / generate_n ========

void test_algorithm_generate() {
    int a[5] = {};
    int n = 0;
    std::generate(a, a + 5, [&]{ return ++n; });
    CHECK(a[0] == 1 && a[4] == 5);
}

void test_algorithm_generate_n() {
    int a[5] = {};
    int n = 0;
    auto end = std::generate_n(a, 3, [&]{ return ++n; });
    CHECK(end == a + 3);
    CHECK(a[0] == 1 && a[2] == 3 && a[3] == 0);
}

// ======== remove / remove_if / remove_copy / remove_copy_if ========

void test_algorithm_remove() {
    int a[] = {1, 2, 3, 2, 1};
    auto end = std::remove(a, a + 5, 2);
    CHECK(end - a == 3);
    CHECK(a[0] == 1 && a[1] == 3 && a[2] == 1);
}

void test_algorithm_remove_if() {
    int a[] = {1, 2, 3, 4, 5};
    auto end = std::remove_if(a, a + 5, [](int x){ return x % 2 == 0; });
    CHECK(end - a == 3);
    CHECK(a[0] == 1 && a[1] == 3 && a[2] == 5);
}

void test_algorithm_remove_copy() {
    int src[] = {1, 2, 3, 2, 1};
    int dst[5] = {};
    auto end = std::remove_copy(src, src + 5, dst, 2);
    CHECK(end - dst == 3);
    CHECK(dst[0] == 1 && dst[1] == 3 && dst[2] == 1);
}

void test_algorithm_remove_copy_if() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    auto end = std::remove_copy_if(src, src + 5, dst, [](int x){ return x % 2 == 0; });
    CHECK(end - dst == 3);
    CHECK(dst[0] == 1 && dst[1] == 3 && dst[2] == 5);
}

// ======== replace / replace_if / replace_copy / replace_copy_if ========

void test_algorithm_replace() {
    int a[] = {1, 2, 3, 2, 1};
    std::replace(a, a + 5, 2, 9);
    CHECK(a[1] == 9 && a[3] == 9 && a[0] == 1);
}

void test_algorithm_replace_if() {
    int a[] = {1, 2, 3, 4, 5};
    std::replace_if(a, a + 5, [](int x){ return x % 2 == 0; }, 0);
    CHECK(a[1] == 0 && a[3] == 0 && a[0] == 1);
}

void test_algorithm_replace_copy() {
    int src[] = {1, 2, 3, 2, 1};
    int dst[5] = {};
    std::replace_copy(src, src + 5, dst, 2, 9);
    CHECK(dst[1] == 9 && dst[3] == 9 && dst[0] == 1);
}

void test_algorithm_replace_copy_if() {
    int src[] = {1, 2, 3, 4};
    int dst[4] = {};
    std::replace_copy_if(src, src + 4, dst, [](int x){ return x % 2 == 0; }, 0);
    CHECK(dst[0] == 1 && dst[1] == 0 && dst[2] == 3 && dst[3] == 0);
}

// ======== swap_ranges / iter_swap ========

void test_algorithm_swap_ranges() {
    int a[] = {1, 2, 3};
    int b[] = {4, 5, 6};
    auto it = std::swap_ranges(a, a + 3, b);
    CHECK(it == b + 3);
    CHECK(a[0] == 4 && a[2] == 6);
    CHECK(b[0] == 1 && b[2] == 3);
}

void test_algorithm_iter_swap() {
    int a = 10, b = 20;
    std::iter_swap(&a, &b);
    CHECK(a == 20 && b == 10);
}

// ======== reverse / reverse_copy ========

void test_algorithm_reverse() {
    int a[] = {1, 2, 3, 4, 5};
    std::reverse(a, a + 5);
    CHECK(a[0] == 5 && a[4] == 1);

    int b[] = {1, 2, 3, 4};
    std::reverse(b, b + 4);
    CHECK(b[0] == 4 && b[3] == 1);

    // empty / single
    int c[] = {42};
    std::reverse(c, c + 1);
    CHECK(c[0] == 42);
}

void test_algorithm_reverse_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    std::reverse_copy(src, src + 5, dst);
    CHECK(dst[0] == 5 && dst[4] == 1);
    CHECK(src[0] == 1); // source unchanged
}

// ======== rotate / rotate_copy ========

void test_algorithm_rotate() {
    int a[] = {1, 2, 3, 4, 5};
    auto new_first = std::rotate(a, a + 2, a + 5);
    CHECK(new_first == a + 3);
    CHECK(a[0] == 3 && a[4] == 2);

    // rotate by 0 (middle == first -> return last)
    int b[] = {1, 2, 3};
    auto r = std::rotate(b, b, b + 3);
    CHECK(r == b + 3);

    // rotate by full (middle == last -> return first)
    auto r2 = std::rotate(b, b + 3, b + 3);
    CHECK(r2 == b);
}

void test_algorithm_rotate_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    auto end = std::rotate_copy(src, src + 2, src + 5, dst);
    CHECK(end == dst + 5);
    CHECK(dst[0] == 3 && dst[2] == 5 && dst[3] == 1 && dst[4] == 2);
}

// ======== unique / unique_copy ========

void test_algorithm_unique() {
    int a[] = {1, 1, 2, 3, 3, 3, 4};
    auto end = std::unique(a, a + 7);
    CHECK(end - a == 4);
    CHECK(a[0] == 1 && a[1] == 2 && a[2] == 3 && a[3] == 4);

    int b[] = {1, 2, 3};
    auto end2 = std::unique(b, b + 3);
    CHECK(end2 == b + 3);
}

void test_algorithm_unique_copy() {
    int src[] = {1, 1, 2, 3, 3, 4};
    int dst[6] = {};
    auto end = std::unique_copy(src, src + 6, dst);
    CHECK(end - dst == 4);
    CHECK(dst[0] == 1 && dst[1] == 2 && dst[2] == 3 && dst[3] == 4);
}

// ======== shift_left / shift_right ========

void test_algorithm_shift_left() {
    int a[] = {1, 2, 3, 4, 5};
    auto end = std::shift_left(a, a + 5, 2);
    // Elements [2..4] moved to [0..2], returns new end
    CHECK(end == a + 3);
    CHECK(a[0] == 3 && a[1] == 4 && a[2] == 5);

    // n == 0: no change, returns last
    int b[] = {1, 2, 3};
    auto e2 = std::shift_left(b, b + 3, 0);
    CHECK(e2 == b + 3);
    CHECK(b[0] == 1);

    // n >= size: returns first
    int c[] = {1, 2, 3};
    auto e3 = std::shift_left(c, c + 3, 5);
    CHECK(e3 == c);
}

void test_algorithm_shift_right() {
    int a[] = {1, 2, 3, 4, 5};
    auto begin = std::shift_right(a, a + 5, 2);
    // Returns new begin
    CHECK(begin == a + 2);
    CHECK(a[2] == 1 && a[3] == 2 && a[4] == 3);

    // n == 0: returns first
    int b[] = {1, 2, 3};
    auto e2 = std::shift_right(b, b + 3, 0);
    CHECK(e2 == b);

    // n >= size: returns last
    int c[] = {1, 2, 3};
    auto e3 = std::shift_right(c, c + 3, 5);
    CHECK(e3 == c + 3);
}

// ======== lexicographical_compare ========

void test_algorithm_lexicographical_compare() {
    int a[] = {1, 2, 3};
    int b[] = {1, 2, 4};
    CHECK(std::lexicographical_compare(a, a + 3, b, b + 3));
    CHECK(!std::lexicographical_compare(b, b + 3, a, a + 3));
    CHECK(!std::lexicographical_compare(a, a + 3, a, a + 3));

    // Shorter range
    CHECK(std::lexicographical_compare(a, a + 2, a, a + 3));
    CHECK(!std::lexicographical_compare(a, a + 3, a, a + 2));

    // Empty ranges
    CHECK(!std::lexicographical_compare(a, a, a, a));
    CHECK(std::lexicographical_compare(a, a, a, a + 1));
}

// ======== lexicographical_compare_three_way ========

void test_algorithm_lexicographical_compare_three_way() {
    int a[] = {1, 2, 3};
    int b[] = {1, 2, 4};
    auto r1 = std::lexicographical_compare_three_way(a, a + 3, b, b + 3);
    CHECK(r1 < 0);

    auto r2 = std::lexicographical_compare_three_way(b, b + 3, a, a + 3);
    CHECK(r2 > 0);

    auto r3 = std::lexicographical_compare_three_way(a, a + 3, a, a + 3);
    CHECK(r3 == 0);

    // shorter
    auto r4 = std::lexicographical_compare_three_way(a, a + 2, a, a + 3);
    CHECK(r4 < 0);
}
