// Tests for <algorithm> — Part 1 (classic non-ranges algorithms)
// No main(); auto-generated by tools/gen_main.sh
#include <algorithm>
#include "test.h"

// ======== min / max / minmax / clamp ========

void test_algorithm_min() {
    static_assert(std::min(1, 2) == 1);
    static_assert(std::min(2, 1) == 1);
    static_assert(std::min(3, 3) == 3);
    static_assert(std::min(1, 2, std::greater<int>{}) == 2);
    static_assert(std::min({3, 1, 4, 1, 5}) == 1);
    static_assert(std::min({3, 1, 4}, std::greater<int>{}) == 4);
}

void test_algorithm_max() {
    static_assert(std::max(1, 2) == 2);
    static_assert(std::max(2, 1) == 2);
    static_assert(std::max(3, 3) == 3);
    static_assert(std::max(1, 2, std::greater<int>{}) == 1);
    static_assert(std::max({3, 1, 4, 1, 5}) == 5);
    static_assert(std::max({3, 1, 4}, std::greater<int>{}) == 1);
}

void test_algorithm_minmax() {
    // minmax returns pair<const T&, const T&> so can't be constexpr in all contexts
    auto p1 = std::minmax(1, 2);
    CHECK(p1.first == 1 && p1.second == 2);
    auto p2 = std::minmax(2, 1);
    CHECK(p2.first == 1 && p2.second == 2);
    auto p3 = std::minmax(3, 3);
    CHECK(p3.first == 3 && p3.second == 3);
    // initializer_list overload returns pair<T,T>
    constexpr auto p4 = std::minmax({3, 1, 4, 1, 5});
    static_assert(p4.first == 1 && p4.second == 5);
}

void test_algorithm_clamp() {
    static_assert(std::clamp(3, 1, 5) == 3);
    static_assert(std::clamp(0, 1, 5) == 1);
    static_assert(std::clamp(7, 1, 5) == 5);
    static_assert(std::clamp(1, 1, 5) == 1);
    static_assert(std::clamp(5, 1, 5) == 5);
    static_assert(std::clamp(3, 1, 5, std::less<int>{}) == 3);
}

// ======== min_element / max_element / minmax_element ========

void test_algorithm_min_element() {
    int a[] = {3, 1, 4, 1, 5, 9, 2};
    auto it = std::min_element(a, a + 7);
    CHECK(*it == 1);
    CHECK(it == a + 1);

    int b[] = {5};
    CHECK(std::min_element(b, b + 1) == b);

    // empty
    CHECK(std::min_element(b, b) == b);

    // with comparator
    auto it2 = std::min_element(a, a + 7, std::greater<int>{});
    CHECK(*it2 == 9);
}

void test_algorithm_max_element() {
    int a[] = {3, 1, 4, 1, 5, 9, 2};
    auto it = std::max_element(a, a + 7);
    CHECK(*it == 9);
    CHECK(it == a + 5);

    auto it2 = std::max_element(a, a + 7, std::greater<int>{});
    CHECK(*it2 == 1);
}

void test_algorithm_minmax_element() {
    int a[] = {3, 1, 4, 1, 5, 9, 2, 6};
    auto [mn, mx] = std::minmax_element(a, a + 8);
    CHECK(*mn == 1);
    CHECK(*mx == 9);
}

// ======== all_of / any_of / none_of ========

void test_algorithm_all_of() {
    int a[] = {2, 4, 6, 8};
    CHECK(std::all_of(a, a + 4, [](int x){ return x % 2 == 0; }));
    CHECK(!std::all_of(a, a + 4, [](int x){ return x > 4; }));
    // empty range -> true
    CHECK(std::all_of(a, a, [](int){ return false; }));
}

void test_algorithm_any_of() {
    int a[] = {1, 3, 5, 6};
    CHECK(std::any_of(a, a + 4, [](int x){ return x % 2 == 0; }));
    CHECK(!std::any_of(a, a + 3, [](int x){ return x % 2 == 0; }));
    // empty -> false
    CHECK(!std::any_of(a, a, [](int){ return true; }));
}

void test_algorithm_none_of() {
    int a[] = {1, 3, 5, 7};
    CHECK(std::none_of(a, a + 4, [](int x){ return x % 2 == 0; }));
    CHECK(!std::none_of(a, a + 4, [](int x){ return x > 4; }));
    // empty -> true
    CHECK(std::none_of(a, a, [](int){ return true; }));
}

// ======== for_each / for_each_n ========

void test_algorithm_for_each() {
    int a[] = {1, 2, 3, 4};
    int sum = 0;
    std::for_each(a, a + 4, [&](int x){ sum += x; });
    CHECK(sum == 10);
}

void test_algorithm_for_each_n() {
    int a[] = {1, 2, 3, 4, 5};
    int sum = 0;
    auto it = std::for_each_n(a, 3, [&](int x){ sum += x; });
    CHECK(sum == 6);
    CHECK(it == a + 3);
}

// ======== count / count_if ========

void test_algorithm_count() {
    int a[] = {1, 2, 3, 2, 1};
    CHECK(std::count(a, a + 5, 2) == 2);
    CHECK(std::count(a, a + 5, 7) == 0);
    CHECK(std::count(a, a, 1) == 0);
}

void test_algorithm_count_if() {
    int a[] = {1, 2, 3, 4, 5};
    CHECK(std::count_if(a, a + 5, [](int x){ return x % 2 == 0; }) == 2);
    CHECK(std::count_if(a, a + 5, [](int x){ return x > 10; }) == 0);
}

// ======== mismatch ========

void test_algorithm_mismatch() {
    int a[] = {1, 2, 3, 4};
    int b[] = {1, 2, 5, 4};
    auto [p1, p2] = std::mismatch(a, a + 4, b, b + 4);
    CHECK(p1 == a + 2 && p2 == b + 2);

    // equal ranges
    auto [q1, q2] = std::mismatch(a, a + 4, a, a + 4);
    CHECK(q1 == a + 4 && q2 == a + 4);

    // 3-iterator version
    auto [r1, r2] = std::mismatch(a, a + 4, b);
    CHECK(r1 == a + 2 && r2 == b + 2);
}

// ======== equal ========

void test_algorithm_equal() {
    int a[] = {1, 2, 3};
    int b[] = {1, 2, 3};
    int c[] = {1, 2, 4};
    CHECK(std::equal(a, a + 3, b, b + 3));
    CHECK(!std::equal(a, a + 3, c, c + 3));
    // 3-iter
    CHECK(std::equal(a, a + 3, b));
    CHECK(!std::equal(a, a + 3, c));
    // different lengths
    CHECK(!std::equal(a, a + 3, b, b + 2));
    // with pred
    CHECK(std::equal(a, a + 3, b, b + 3, std::equal_to<int>{}));
}

// ======== find / find_if / find_if_not ========

void test_algorithm_find() {
    int a[] = {1, 2, 3, 4, 5};
    CHECK(std::find(a, a + 5, 3) == a + 2);
    CHECK(std::find(a, a + 5, 7) == a + 5);
}

void test_algorithm_find_if() {
    int a[] = {1, 3, 5, 4, 7};
    auto it = std::find_if(a, a + 5, [](int x){ return x % 2 == 0; });
    CHECK(it == a + 3 && *it == 4);
    auto it2 = std::find_if(a, a + 3, [](int x){ return x % 2 == 0; });
    CHECK(it2 == a + 3);
}

void test_algorithm_find_if_not() {
    int a[] = {2, 4, 6, 5, 8};
    auto it = std::find_if_not(a, a + 5, [](int x){ return x % 2 == 0; });
    CHECK(it == a + 3 && *it == 5);
}

// ======== find_end ========

void test_algorithm_find_end() {
    int a[] = {1, 2, 3, 1, 2, 3, 1, 2};
    int pat[] = {1, 2, 3};
    auto it = std::find_end(a, a + 8, pat, pat + 3);
    CHECK(it == a + 3);

    // not found
    int pat2[] = {4, 5};
    auto it2 = std::find_end(a, a + 8, pat2, pat2 + 2);
    CHECK(it2 == a + 8);

    // empty pattern -> returns last
    auto it3 = std::find_end(a, a + 8, pat, pat);
    CHECK(it3 == a + 8);
}

// ======== find_first_of ========

void test_algorithm_find_first_of() {
    int a[] = {1, 2, 3, 4, 5};
    int b[] = {3, 5, 7};
    auto it = std::find_first_of(a, a + 5, b, b + 3);
    CHECK(it == a + 2 && *it == 3);

    int c[] = {8, 9};
    auto it2 = std::find_first_of(a, a + 5, c, c + 2);
    CHECK(it2 == a + 5);
}

// ======== adjacent_find ========

void test_algorithm_adjacent_find() {
    int a[] = {1, 2, 3, 3, 4};
    auto it = std::adjacent_find(a, a + 5);
    CHECK(it == a + 2 && *it == 3);

    int b[] = {1, 2, 3, 4};
    auto it2 = std::adjacent_find(b, b + 4);
    CHECK(it2 == b + 4);

    // with pred
    int c[] = {1, 3, 2, 4};
    auto it3 = std::adjacent_find(c, c + 4, std::greater<int>{});
    CHECK(it3 == c + 1);
}

// ======== search ========

void test_algorithm_search() {
    int a[] = {1, 2, 3, 4, 5};
    int pat[] = {3, 4};
    auto it = std::search(a, a + 5, pat, pat + 2);
    CHECK(it == a + 2);

    int pat2[] = {5, 6};
    auto it2 = std::search(a, a + 5, pat2, pat2 + 2);
    CHECK(it2 == a + 5);

    // empty pattern -> returns first
    auto it3 = std::search(a, a + 5, pat, pat);
    CHECK(it3 == a);
}

// ======== search_n ========

void test_algorithm_search_n() {
    int a[] = {1, 2, 2, 2, 3};
    auto it = std::search_n(a, a + 5, 3, 2);
    CHECK(it == a + 1);

    auto it2 = std::search_n(a, a + 5, 4, 2);
    CHECK(it2 == a + 5);

    auto it3 = std::search_n(a, a + 5, 0, 2);
    CHECK(it3 == a);
}

// ======== copy / copy_if / copy_n / copy_backward ========

void test_algorithm_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    std::copy(src, src + 5, dst);
    CHECK(dst[0] == 1 && dst[4] == 5);
}

void test_algorithm_copy_if() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    auto end = std::copy_if(src, src + 5, dst, [](int x){ return x % 2 == 0; });
    CHECK(end - dst == 2);
    CHECK(dst[0] == 2 && dst[1] == 4);
}

void test_algorithm_copy_n() {
    int src[] = {10, 20, 30, 40};
    int dst[4] = {};
    auto end = std::copy_n(src, 3, dst);
    CHECK(end == dst + 3);
    CHECK(dst[0] == 10 && dst[2] == 30 && dst[3] == 0);
}

void test_algorithm_copy_backward() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    std::copy_backward(src, src + 5, dst + 5);
    CHECK(dst[0] == 1 && dst[4] == 5);

    // Overlapping: shift right by 1
    int a[] = {1, 2, 3, 4, 5};
    std::copy_backward(a, a + 4, a + 5);
    CHECK(a[1] == 1 && a[4] == 4);
}

// ======== move / move_backward ========

void test_algorithm_move() {
    int src[] = {1, 2, 3};
    int dst[3] = {};
    std::move(src, src + 3, dst);
    CHECK(dst[0] == 1 && dst[2] == 3);
}

void test_algorithm_move_backward() {
    int a[] = {1, 2, 3, 4, 5};
    std::move_backward(a, a + 4, a + 5);
    CHECK(a[1] == 1 && a[4] == 4);
}

// ======== fill / fill_n ========

void test_algorithm_fill() {
    int a[5] = {};
    std::fill(a, a + 5, 7);
    for (int i = 0; i < 5; ++i) CHECK(a[i] == 7);
    std::fill(a, a, 99);
    CHECK(a[0] == 7); // empty range, no change
}

void test_algorithm_fill_n() {
    int a[5] = {};
    auto end = std::fill_n(a, 3, 42);
    CHECK(end == a + 3);
    CHECK(a[0] == 42 && a[2] == 42 && a[3] == 0);
}

// ======== transform ========

void test_algorithm_transform() {
    int src[] = {1, 2, 3, 4};
    int dst[4] = {};
    std::transform(src, src + 4, dst, [](int x){ return x * 2; });
    CHECK(dst[0] == 2 && dst[3] == 8);

    int dst2[4] = {};
    int src2[] = {10, 10, 10, 10};
    std::transform(src, src + 4, src2, dst2, std::plus<int>{});
    CHECK(dst2[0] == 11 && dst2[3] == 14);
}

// ======== generate / generate_n ========

void test_algorithm_generate() {
    int a[5] = {};
    int n = 0;
    std::generate(a, a + 5, [&]{ return ++n; });
    CHECK(a[0] == 1 && a[4] == 5);
}

void test_algorithm_generate_n() {
    int a[5] = {};
    int n = 0;
    auto end = std::generate_n(a, 3, [&]{ return ++n; });
    CHECK(end == a + 3);
    CHECK(a[0] == 1 && a[2] == 3 && a[3] == 0);
}

// ======== remove / remove_if / remove_copy / remove_copy_if ========

void test_algorithm_remove() {
    int a[] = {1, 2, 3, 2, 1};
    auto end = std::remove(a, a + 5, 2);
    CHECK(end - a == 3);
    CHECK(a[0] == 1 && a[1] == 3 && a[2] == 1);
}

void test_algorithm_remove_if() {
    int a[] = {1, 2, 3, 4, 5};
    auto end = std::remove_if(a, a + 5, [](int x){ return x % 2 == 0; });
    CHECK(end - a == 3);
    CHECK(a[0] == 1 && a[1] == 3 && a[2] == 5);
}

void test_algorithm_remove_copy() {
    int src[] = {1, 2, 3, 2, 1};
    int dst[5] = {};
    auto end = std::remove_copy(src, src + 5, dst, 2);
    CHECK(end - dst == 3);
    CHECK(dst[0] == 1 && dst[1] == 3 && dst[2] == 1);
}

void test_algorithm_remove_copy_if() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    auto end = std::remove_copy_if(src, src + 5, dst, [](int x){ return x % 2 == 0; });
    CHECK(end - dst == 3);
    CHECK(dst[0] == 1 && dst[1] == 3 && dst[2] == 5);
}

// ======== replace / replace_if / replace_copy / replace_copy_if ========

void test_algorithm_replace() {
    int a[] = {1, 2, 3, 2, 1};
    std::replace(a, a + 5, 2, 9);
    CHECK(a[1] == 9 && a[3] == 9 && a[0] == 1);
}

void test_algorithm_replace_if() {
    int a[] = {1, 2, 3, 4, 5};
    std::replace_if(a, a + 5, [](int x){ return x % 2 == 0; }, 0);
    CHECK(a[1] == 0 && a[3] == 0 && a[0] == 1);
}

void test_algorithm_replace_copy() {
    int src[] = {1, 2, 3, 2, 1};
    int dst[5] = {};
    std::replace_copy(src, src + 5, dst, 2, 9);
    CHECK(dst[1] == 9 && dst[3] == 9 && dst[0] == 1);
}

void test_algorithm_replace_copy_if() {
    int src[] = {1, 2, 3, 4};
    int dst[4] = {};
    std::replace_copy_if(src, src + 4, dst, [](int x){ return x % 2 == 0; }, 0);
    CHECK(dst[0] == 1 && dst[1] == 0 && dst[2] == 3 && dst[3] == 0);
}

// ======== swap_ranges / iter_swap ========

void test_algorithm_swap_ranges() {
    int a[] = {1, 2, 3};
    int b[] = {4, 5, 6};
    auto it = std::swap_ranges(a, a + 3, b);
    CHECK(it == b + 3);
    CHECK(a[0] == 4 && a[2] == 6);
    CHECK(b[0] == 1 && b[2] == 3);
}

void test_algorithm_iter_swap() {
    int a = 10, b = 20;
    std::iter_swap(&a, &b);
    CHECK(a == 20 && b == 10);
}

// ======== reverse / reverse_copy ========

void test_algorithm_reverse() {
    int a[] = {1, 2, 3, 4, 5};
    std::reverse(a, a + 5);
    CHECK(a[0] == 5 && a[4] == 1);

    int b[] = {1, 2, 3, 4};
    std::reverse(b, b + 4);
    CHECK(b[0] == 4 && b[3] == 1);

    // empty / single
    int c[] = {42};
    std::reverse(c, c + 1);
    CHECK(c[0] == 42);
}

void test_algorithm_reverse_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    std::reverse_copy(src, src + 5, dst);
    CHECK(dst[0] == 5 && dst[4] == 1);
    CHECK(src[0] == 1); // source unchanged
}

// ======== rotate / rotate_copy ========

void test_algorithm_rotate() {
    int a[] = {1, 2, 3, 4, 5};
    auto new_first = std::rotate(a, a + 2, a + 5);
    CHECK(new_first == a + 3);
    CHECK(a[0] == 3 && a[4] == 2);

    // rotate by 0 (middle == first -> return last)
    int b[] = {1, 2, 3};
    auto r = std::rotate(b, b, b + 3);
    CHECK(r == b + 3);

    // rotate by full (middle == last -> return first)
    auto r2 = std::rotate(b, b + 3, b + 3);
    CHECK(r2 == b);
}

void test_algorithm_rotate_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int dst[5] = {};
    auto end = std::rotate_copy(src, src + 2, src + 5, dst);
    CHECK(end == dst + 5);
    CHECK(dst[0] == 3 && dst[2] == 5 && dst[3] == 1 && dst[4] == 2);
}

// ======== unique / unique_copy ========

void test_algorithm_unique() {
    int a[] = {1, 1, 2, 3, 3, 3, 4};
    auto end = std::unique(a, a + 7);
    CHECK(end - a == 4);
    CHECK(a[0] == 1 && a[1] == 2 && a[2] == 3 && a[3] == 4);

    int b[] = {1, 2, 3};
    auto end2 = std::unique(b, b + 3);
    CHECK(end2 == b + 3);
}

void test_algorithm_unique_copy() {
    int src[] = {1, 1, 2, 3, 3, 4};
    int dst[6] = {};
    auto end = std::unique_copy(src, src + 6, dst);
    CHECK(end - dst == 4);
    CHECK(dst[0] == 1 && dst[1] == 2 && dst[2] == 3 && dst[3] == 4);
}

// ======== shift_left / shift_right ========

void test_algorithm_shift_left() {
    int a[] = {1, 2, 3, 4, 5};
    auto end = std::shift_left(a, a + 5, 2);
    // Elements [2..4] moved to [0..2], returns new end
    CHECK(end == a + 3);
    CHECK(a[0] == 3 && a[1] == 4 && a[2] == 5);

    // n == 0: no change, returns last
    int b[] = {1, 2, 3};
    auto e2 = std::shift_left(b, b + 3, 0);
    CHECK(e2 == b + 3);
    CHECK(b[0] == 1);

    // n >= size: returns first
    int c[] = {1, 2, 3};
    auto e3 = std::shift_left(c, c + 3, 5);
    CHECK(e3 == c);
}

void test_algorithm_shift_right() {
    int a[] = {1, 2, 3, 4, 5};
    auto begin = std::shift_right(a, a + 5, 2);
    // Returns new begin
    CHECK(begin == a + 2);
    CHECK(a[2] == 1 && a[3] == 2 && a[4] == 3);

    // n == 0: returns first
    int b[] = {1, 2, 3};
    auto e2 = std::shift_right(b, b + 3, 0);
    CHECK(e2 == b);

    // n >= size: returns last
    int c[] = {1, 2, 3};
    auto e3 = std::shift_right(c, c + 3, 5);
    CHECK(e3 == c + 3);
}

// ======== lexicographical_compare ========

void test_algorithm_lexicographical_compare() {
    int a[] = {1, 2, 3};
    int b[] = {1, 2, 4};
    CHECK(std::lexicographical_compare(a, a + 3, b, b + 3));
    CHECK(!std::lexicographical_compare(b, b + 3, a, a + 3));
    CHECK(!std::lexicographical_compare(a, a + 3, a, a + 3));

    // Shorter range
    CHECK(std::lexicographical_compare(a, a + 2, a, a + 3));
    CHECK(!std::lexicographical_compare(a, a + 3, a, a + 2));

    // Empty ranges
    CHECK(!std::lexicographical_compare(a, a, a, a));
    CHECK(std::lexicographical_compare(a, a, a, a + 1));
}

// ======== lexicographical_compare_three_way ========

void test_algorithm_lexicographical_compare_three_way() {
    int a[] = {1, 2, 3};
    int b[] = {1, 2, 4};
    auto r1 = std::lexicographical_compare_three_way(a, a + 3, b, b + 3);
    CHECK(r1 < 0);

    auto r2 = std::lexicographical_compare_three_way(b, b + 3, a, a + 3);
    CHECK(r2 > 0);

    auto r3 = std::lexicographical_compare_three_way(a, a + 3, a, a + 3);
    CHECK(r3 == 0);

    // shorter
    auto r4 = std::lexicographical_compare_three_way(a, a + 2, a, a + 3);
    CHECK(r4 < 0);
}

// ======== Part 2: heap operations ========

void test_algorithm_heap() {
    // make_heap / is_heap / push_heap / pop_heap / sort_heap
    int a[] = {3, 1, 4, 1, 5, 9, 2, 6};
    std::make_heap(a, a + 8);
    CHECK(std::is_heap(a, a + 8));
    CHECK(std::is_heap_until(a, a + 8) == a + 8);

    // push_heap: append element then sift up
    int b[] = {9, 6, 5, 4, 3, 2, 1, 0, 7};  // first 8 form a heap
    std::make_heap(b, b + 8);
    b[8] = 7;
    std::push_heap(b, b + 9);
    CHECK(std::is_heap(b, b + 9));

    // pop_heap: moves max to end
    int c[] = {5, 3, 4, 2, 1};
    std::make_heap(c, c + 5);
    CHECK(c[0] == 5);
    std::pop_heap(c, c + 5);
    CHECK(c[4] == 5);
    CHECK(std::is_heap(c, c + 4));

    // sort_heap
    int d[] = {3, 1, 4, 1, 5, 9, 2, 6};
    std::make_heap(d, d + 8);
    std::sort_heap(d, d + 8);
    CHECK(std::is_sorted(d, d + 8));

    // with comparator (max-heap by default = ascending sort)
    int e[] = {4, 2, 7, 1, 9};
    std::make_heap(e, e + 5, std::greater<int>{});
    CHECK(std::is_heap(e, e + 5, std::greater<int>{}));
    std::sort_heap(e, e + 5, std::greater<int>{});
    // sorted descending
    CHECK(e[0] == 9 && e[4] == 1);
}

// ======== Part 2: is_sorted / is_sorted_until ========

void test_algorithm_is_sorted() {
    int a[] = {1, 2, 3, 4, 5};
    CHECK(std::is_sorted(a, a + 5));
    int b[] = {1, 3, 2, 4};
    CHECK(!std::is_sorted(b, b + 4));
    // empty / single
    CHECK(std::is_sorted(a, a));
    CHECK(std::is_sorted(a, a + 1));

    auto it = std::is_sorted_until(b, b + 4);
    CHECK(it == b + 2);

    // with comp
    int c[] = {5, 4, 3, 2, 1};
    CHECK(std::is_sorted(c, c + 5, std::greater<int>{}));
}

// ======== Part 2: sort ========

void test_algorithm_sort() {
    int a[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::sort(a, a + 9);
    CHECK(std::is_sorted(a, a + 9));
    CHECK(a[0] == 1 && a[8] == 9);

    // with comparator
    int b[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::sort(b, b + 9, std::greater<int>{});
    CHECK(std::is_sorted(b, b + 9, std::greater<int>{}));
    CHECK(b[0] == 9 && b[8] == 1);

    // already sorted
    int c[] = {1, 2, 3, 4, 5};
    std::sort(c, c + 5);
    CHECK(std::is_sorted(c, c + 5));

    // reverse sorted
    int d[] = {5, 4, 3, 2, 1};
    std::sort(d, d + 5);
    CHECK(d[0] == 1 && d[4] == 5);

    // single / empty
    int e[] = {42};
    std::sort(e, e + 1);
    CHECK(e[0] == 42);
    std::sort(e, e);
}

// ======== Part 2: stable_sort ========

void test_algorithm_stable_sort() {
    int a[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::stable_sort(a, a + 9);
    CHECK(std::is_sorted(a, a + 9));
    CHECK(a[0] == 1 && a[8] == 9);

    // with comparator
    int b[] = {5, 3, 8, 1, 2};
    std::stable_sort(b, b + 5, std::greater<int>{});
    CHECK(std::is_sorted(b, b + 5, std::greater<int>{}));

    // stability: equal elements keep relative order
    // Use pairs: sort by first, check second is stable
    // Simulate with structs via arrays of pairs
    // Use int* trick: sort 0-4 with key = v%3, record original index
    // Simple test: already-sorted remains sorted
    int c[] = {1, 1, 2, 2, 3, 3};
    std::stable_sort(c, c + 6);
    CHECK(c[0] == 1 && c[5] == 3);
}

// ======== Part 2: partial_sort / partial_sort_copy ========

void test_algorithm_partial_sort() {
    int a[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::partial_sort(a, a + 4, a + 9);
    // First 4 elements are the 4 smallest, sorted
    CHECK(a[0] == 1 && a[1] == 2 && a[2] == 3 && a[3] == 4);

    // with comparator
    int b[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::partial_sort(b, b + 3, b + 9, std::greater<int>{});
    CHECK(b[0] == 9 && b[1] == 8 && b[2] == 7);
}

void test_algorithm_partial_sort_copy() {
    int src[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    int dst[4] = {};
    auto end = std::partial_sort_copy(src, src + 9, dst, dst + 4);
    CHECK(end == dst + 4);
    CHECK(dst[0] == 1 && dst[1] == 2 && dst[2] == 3 && dst[3] == 4);

    // with comparator
    int dst2[3] = {};
    auto end2 = std::partial_sort_copy(src, src + 9, dst2, dst2 + 3, std::greater<int>{});
    CHECK(end2 == dst2 + 3);
    CHECK(dst2[0] == 9 && dst2[1] == 8 && dst2[2] == 7);
}

// ======== Part 2: nth_element ========

void test_algorithm_nth_element() {
    int a[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::nth_element(a, a + 4, a + 9);
    // a[4] should be 5 (the median)
    CHECK(a[4] == 5);
    // All elements before a[4] should be <= a[4]
    for (int i = 0; i < 4; ++i) CHECK(a[i] <= 5);
    for (int i = 5; i < 9; ++i) CHECK(a[i] >= 5);

    // with comparator
    int b[] = {5, 3, 8, 1, 9, 2, 7, 4, 6};
    std::nth_element(b, b + 0, b + 9, std::greater<int>{});
    CHECK(b[0] == 9);
}

// ======== Part 2: lower_bound / upper_bound / equal_range / binary_search ========

void test_algorithm_lower_bound() {
    int a[] = {1, 2, 2, 3, 4, 4, 5};
    auto it = std::lower_bound(a, a + 7, 2);
    CHECK(it == a + 1);
    auto it2 = std::lower_bound(a, a + 7, 6);
    CHECK(it2 == a + 7);
    auto it3 = std::lower_bound(a, a + 7, 0);
    CHECK(it3 == a);
    auto it4 = std::lower_bound(a, a + 7, 4);
    CHECK(*it4 == 4 && it4 == a + 4);
}

void test_algorithm_upper_bound() {
    int a[] = {1, 2, 2, 3, 4, 4, 5};
    auto it = std::upper_bound(a, a + 7, 2);
    CHECK(it == a + 3);
    auto it2 = std::upper_bound(a, a + 7, 6);
    CHECK(it2 == a + 7);
    auto it3 = std::upper_bound(a, a + 7, 0);
    CHECK(it3 == a);
}

void test_algorithm_equal_range() {
    int a[] = {1, 2, 2, 3, 4, 4, 5};
    auto [lo, hi] = std::equal_range(a, a + 7, 2);
    CHECK(lo == a + 1 && hi == a + 3);
    auto [lo2, hi2] = std::equal_range(a, a + 7, 6);
    CHECK(lo2 == a + 7 && hi2 == a + 7);
    auto [lo3, hi3] = std::equal_range(a, a + 7, 3);
    CHECK(lo3 == a + 3 && hi3 == a + 4);
}

void test_algorithm_binary_search() {
    int a[] = {1, 2, 3, 4, 5};
    CHECK(std::binary_search(a, a + 5, 3));
    CHECK(!std::binary_search(a, a + 5, 6));
    CHECK(std::binary_search(a, a + 5, 1));
    CHECK(std::binary_search(a, a + 5, 5));
    CHECK(!std::binary_search(a, a, 1)); // empty
}

// ======== Part 2: merge / inplace_merge ========

void test_algorithm_merge() {
    int a[] = {1, 3, 5, 7};
    int b[] = {2, 4, 6, 8};
    int out[8] = {};
    auto end = std::merge(a, a + 4, b, b + 4, out);
    CHECK(end == out + 8);
    for (int i = 0; i < 8; ++i) CHECK(out[i] == i + 1);

    // with comparator
    int c[] = {8, 6, 4, 2};
    int d[] = {7, 5, 3, 1};
    int out2[8] = {};
    std::merge(c, c + 4, d, d + 4, out2, std::greater<int>{});
    CHECK(out2[0] == 8 && out2[7] == 1);
}

void test_algorithm_inplace_merge() {
    int a[] = {1, 3, 5, 2, 4, 6};
    std::inplace_merge(a, a + 3, a + 6);
    CHECK(std::is_sorted(a, a + 6));
    CHECK(a[0] == 1 && a[5] == 6);

    int b[] = {8, 6, 4, 7, 5, 3};
    std::inplace_merge(b, b + 3, b + 6, std::greater<int>{});
    CHECK(std::is_sorted(b, b + 6, std::greater<int>{}));
}

// ======== Part 2: set operations ========

void test_algorithm_set_ops() {
    int a[] = {1, 2, 3, 4, 5};
    int b[] = {3, 4, 5, 6, 7};

    // includes
    CHECK(std::includes(a, a + 5, a + 2, a + 4));  // {3,4} in {1..5}
    CHECK(!std::includes(a, a + 5, b, b + 5));      // {3..7} not in {1..5}

    // set_union
    int un[10] = {};
    auto un_end = std::set_union(a, a + 5, b, b + 5, un);
    CHECK(un_end - un == 7);
    CHECK(un[0] == 1 && un[6] == 7);

    // set_intersection
    int isect[5] = {};
    auto is_end = std::set_intersection(a, a + 5, b, b + 5, isect);
    CHECK(is_end - isect == 3);
    CHECK(isect[0] == 3 && isect[1] == 4 && isect[2] == 5);

    // set_difference a - b
    int diff[5] = {};
    auto diff_end = std::set_difference(a, a + 5, b, b + 5, diff);
    CHECK(diff_end - diff == 2);
    CHECK(diff[0] == 1 && diff[1] == 2);

    // set_symmetric_difference
    int symm[10] = {};
    auto symm_end = std::set_symmetric_difference(a, a + 5, b, b + 5, symm);
    CHECK(symm_end - symm == 4);
    CHECK(symm[0] == 1 && symm[1] == 2 && symm[2] == 6 && symm[3] == 7);
}

// ======== Part 2: partition operations ========

void test_algorithm_partition() {
    int a[] = {1, 2, 3, 4, 5, 6, 7, 8};
    auto mid = std::partition(a, a + 8, [](int x){ return x % 2 == 0; });
    CHECK(std::is_partitioned(a, a + 8, [](int x){ return x % 2 == 0; }));
    // All evens before mid, all odds from mid onward
    for (int* p = a; p != mid; ++p) CHECK(*p % 2 == 0);
    for (int* p = mid; p != a + 8; ++p) CHECK(*p % 2 != 0);
}

void test_algorithm_stable_partition() {
    int a[] = {1, 2, 3, 4, 5, 6, 7, 8};
    auto mid = std::stable_partition(a, a + 8, [](int x){ return x % 2 == 0; });
    CHECK(std::is_partitioned(a, a + 8, [](int x){ return x % 2 == 0; }));
    // Evens should be in original relative order: 2,4,6,8
    CHECK(a[0] == 2 && a[1] == 4 && a[2] == 6 && a[3] == 8);
    // Odds in original relative order: 1,3,5,7
    CHECK(a[4] == 1 && a[5] == 3 && a[6] == 5 && a[7] == 7);
    CHECK(mid == a + 4);
}

void test_algorithm_partition_copy() {
    int src[] = {1, 2, 3, 4, 5};
    int evens[5] = {}, odds[5] = {};
    auto [pe, po] = std::partition_copy(src, src + 5, evens, odds,
                                         [](int x){ return x % 2 == 0; });
    CHECK(pe - evens == 2);
    CHECK(po - odds == 3);
    CHECK(evens[0] == 2 && evens[1] == 4);
    CHECK(odds[0] == 1 && odds[1] == 3 && odds[2] == 5);
}

void test_algorithm_is_partitioned() {
    int a[] = {2, 4, 6, 1, 3, 5};
    CHECK(std::is_partitioned(a, a + 6, [](int x){ return x % 2 == 0; }));
    int b[] = {1, 2, 3, 4};
    CHECK(!std::is_partitioned(b, b + 4, [](int x){ return x % 2 == 0; }));
    // empty is partitioned
    CHECK(std::is_partitioned(a, a, [](int){ return false; }));
}

void test_algorithm_partition_point() {
    int a[] = {2, 4, 6, 1, 3, 5};
    auto pt = std::partition_point(a, a + 6, [](int x){ return x % 2 == 0; });
    CHECK(pt == a + 3);
}

// ======== Part 2: permutations ========

void test_algorithm_next_permutation() {
    int a[] = {1, 2, 3};
    CHECK(std::next_permutation(a, a + 3));
    CHECK(a[0] == 1 && a[1] == 3 && a[2] == 2);
    CHECK(std::next_permutation(a, a + 3));
    CHECK(a[0] == 2 && a[1] == 1 && a[2] == 3);
    // Count all permutations of {1,2,3}
    int b[] = {1, 2, 3};
    int count = 1;
    while (std::next_permutation(b, b + 3)) ++count;
    CHECK(count == 6);
    // After cycling back, array should be {1,2,3}
    CHECK(b[0] == 1 && b[1] == 2 && b[2] == 3);
}

void test_algorithm_prev_permutation() {
    int a[] = {3, 2, 1};
    CHECK(std::prev_permutation(a, a + 3));
    CHECK(a[0] == 3 && a[1] == 1 && a[2] == 2);
    // Count all permutations
    int b[] = {3, 2, 1};
    int count = 1;
    while (std::prev_permutation(b, b + 3)) ++count;
    CHECK(count == 6);
}

void test_algorithm_is_permutation() {
    int a[] = {1, 2, 3};
    int b[] = {3, 1, 2};
    CHECK(std::is_permutation(a, a + 3, b));
    CHECK(std::is_permutation(a, a + 3, b, b + 3));
    int c[] = {1, 2, 4};
    CHECK(!std::is_permutation(a, a + 3, c));
    CHECK(!std::is_permutation(a, a + 3, c, c + 3));
    // same sequence
    CHECK(std::is_permutation(a, a + 3, a));
    // with pred
    CHECK(std::is_permutation(a, a + 3, b, std::equal_to<int>{}));
}
