// test/any.cpp — tests for <any>
// Each test_* function is a no-arg free function using CHECK / static_assert.
// main() is auto-generated by tools/gen_main.sh.
//
// Note: <string> is intentionally NOT included here because the transitive
// include chain string→algorithm→ranges→optional currently has a pre-existing
// namespace-nesting bug in include/optional. Tests use int/double/large structs
// instead of std::string.
#include <any>
#include "test.h"

// A type larger than the small-object-optimisation buffer (3*sizeof(void*))
// so that LargeHandler gets exercised.
struct BigVal {
    long data[8];
    explicit BigVal(long v) { for (auto& x : data) x = v; }
    bool all(long v) const { for (auto x : data) if (x != v) return false; return true; }
};

// ============================================================
// test_any_store_int
// ============================================================
void test_any_store_int() {
    std::any a = 42;
    CHECK(a.has_value());
    int* p = std::any_cast<int>(&a);
    CHECK(p != nullptr);
    CHECK(*p == 42);
}

// ============================================================
// test_any_store_large
// ============================================================
void test_any_store_large() {
    // Exercises the LargeHandler path (BigVal > 3*sizeof(void*)).
    std::any a = BigVal(99);
    CHECK(a.has_value());
    BigVal* p = std::any_cast<BigVal>(&a);
    CHECK(p != nullptr);
    CHECK(p->all(99));
}

// ============================================================
// test_any_cast_value
// ============================================================
void test_any_cast_value() {
    std::any a = 7;
    int v = std::any_cast<int>(a);
    CHECK(v == 7);
}

// ============================================================
// test_any_cast_pointer_bad_type_returns_nullptr
// ============================================================
void test_any_cast_pointer_bad_type_returns_nullptr() {
    std::any a = 3.14;
    // Casting to wrong type must return nullptr, not trap.
    int* p = std::any_cast<int>(&a);
    CHECK(p == nullptr);
    // Correct type should succeed.
    double* q = std::any_cast<double>(&a);
    CHECK(q != nullptr);
}

// ============================================================
// test_any_has_value_reset
// ============================================================
void test_any_has_value_reset() {
    std::any a = 99;
    CHECK(a.has_value());
    a.reset();
    CHECK(!a.has_value());
    // Default-constructed is empty.
    std::any b;
    CHECK(!b.has_value());
}

// ============================================================
// test_any_emplace
// ============================================================
void test_any_emplace() {
    std::any a;
    a.emplace<int>(55);
    CHECK(a.has_value());
    int* p = std::any_cast<int>(&a);
    CHECK(p != nullptr && *p == 55);
    // Emplace BigVal over existing value.
    a.emplace<BigVal>(77L);
    BigVal* b = std::any_cast<BigVal>(&a);
    CHECK(b != nullptr && b->all(77));
}

// ============================================================
// test_any_swap
// ============================================================
void test_any_swap() {
    std::any a = 1;
    std::any b = BigVal(2L);
    std::swap(a, b);
    CHECK(std::any_cast<int>(&b) != nullptr && *std::any_cast<int>(&b) == 1);
    CHECK(std::any_cast<BigVal>(&a) != nullptr && std::any_cast<BigVal>(&a)->all(2));
}

// ============================================================
// test_any_make_any
// ============================================================
void test_any_make_any() {
    auto a = std::make_any<BigVal>(42L);
    CHECK(a.has_value());
    BigVal* p = std::any_cast<BigVal>(&a);
    CHECK(p != nullptr && p->all(42));
}

// ============================================================
// test_any_copy_construct
// ============================================================
void test_any_copy_construct() {
    std::any a = 123;
    std::any b = a;  // copy
    CHECK(b.has_value());
    int* p = std::any_cast<int>(&b);
    CHECK(p != nullptr && *p == 123);
    // Original still intact.
    int* q = std::any_cast<int>(&a);
    CHECK(q != nullptr && *q == 123);
}

// ============================================================
// test_any_move_construct
// ============================================================
void test_any_move_construct() {
    std::any a = 77;
    std::any b = std::move(a);
    CHECK(b.has_value());
    int* p = std::any_cast<int>(&b);
    CHECK(p != nullptr && *p == 77);
}
