// Tests for <array> — libcis port.
// Each function is named test_array_<case>; main is auto-generated by
// tools/gen_main.sh.  No progress printing; failures trap via CHECK().
#include "test.h"
#include <array>
#include <utility>
#include <type_traits>
#include <compare>

// ── Aggregate construction & basic access ──────────────────────────────────

void test_array_aggregate() {
    // Default aggregate construction
    std::array<int, 3> a = {1, 2, 3};
    CHECK(a[0] == 1);
    CHECK(a[1] == 2);
    CHECK(a[2] == 3);

    // Copy construction
    std::array<int, 3> b = a;
    CHECK(b[0] == 1 && b[1] == 2 && b[2] == 3);

    // Assignment
    std::array<int, 3> c;
    c = a;
    CHECK(c[0] == 1 && c[1] == 2 && c[2] == 3);
}

// ── Types ─────────────────────────────────────────────────────────────────

void test_array_types() {
    using A = std::array<double, 5>;
    static_assert(std::is_same_v<A::value_type, double>);
    static_assert(std::is_same_v<A::reference, double&>);
    static_assert(std::is_same_v<A::const_reference, const double&>);
    static_assert(std::is_same_v<A::pointer, double*>);
    static_assert(std::is_same_v<A::const_pointer, const double*>);
    static_assert(std::is_same_v<A::size_type, std::size_t>);
    static_assert(std::is_same_v<A::difference_type, std::ptrdiff_t>);
    static_assert(A{}.size() == 5);
}

// ── Size & capacity ────────────────────────────────────────────────────────

void test_array_size() {
    std::array<int, 3> a = {1, 2, 3};
    CHECK(a.size() == 3);
    CHECK(a.max_size() == 3);
    CHECK(!a.empty());

    std::array<int, 0> b{};
    CHECK(b.size() == 0);
    CHECK(b.max_size() == 0);
    CHECK(b.empty());

    static_assert(std::array<int, 4>{}.size() == 4);
    static_assert(std::array<int, 0>{}.empty());
}

// ── Iterators ─────────────────────────────────────────────────────────────

void test_array_iterators() {
    std::array<int, 3> a = {10, 20, 30};

    // forward iteration
    int sum = 0;
    for (auto it = a.begin(); it != a.end(); ++it)
        sum += *it;
    CHECK(sum == 60);

    // const iteration
    const std::array<int, 3> ca = {1, 2, 3};
    sum = 0;
    for (auto it = ca.begin(); it != ca.end(); ++it)
        sum += *it;
    CHECK(sum == 6);

    // cbegin / cend
    sum = 0;
    for (auto it = a.cbegin(); it != a.cend(); ++it)
        sum += *it;
    CHECK(sum == 60);

    // reverse iteration
    int vals[3];
    int idx = 0;
    for (auto it = a.rbegin(); it != a.rend(); ++it)
        vals[idx++] = *it;
    CHECK(vals[0] == 30 && vals[1] == 20 && vals[2] == 10);

    // crbegin / crend
    idx = 0;
    for (auto it = a.crbegin(); it != a.crend(); ++it)
        vals[idx++] = *it;
    CHECK(vals[0] == 30 && vals[1] == 20 && vals[2] == 10);
}

// ── Element access ────────────────────────────────────────────────────────

void test_array_element_access() {
    std::array<double, 3> a = {1.1, 2.2, 3.3};

    // operator[]
    CHECK(a[0] == 1.1);
    CHECK(a[2] == 3.3);
    a[1] = 99.0;
    CHECK(a[1] == 99.0);

    // at() — in-range
    CHECK(a.at(0) == 1.1);
    a.at(2) = 7.7;
    CHECK(a.at(2) == 7.7);

    // front / back
    CHECK(a.front() == 1.1);
    CHECK(a.back() == 7.7);

    // data()
    double* p = a.data();
    CHECK(p[0] == 1.1);
    CHECK(p[1] == 99.0);

    const std::array<double, 3> ca = {4.0, 5.0, 6.0};
    CHECK(ca[0] == 4.0);
    CHECK(ca.at(1) == 5.0);
    CHECK(ca.front() == 4.0);
    CHECK(ca.back() == 6.0);
    CHECK(ca.data()[2] == 6.0);
}

// ── Constexpr element access ───────────────────────────────────────────────

void test_array_constexpr_access() {
    constexpr std::array<int, 3> a = {10, 20, 30};
    static_assert(a[0] == 10);
    static_assert(a[1] == 20);
    static_assert(a[2] == 30);
    static_assert(a.at(0) == 10);
    static_assert(a.front() == 10);
    static_assert(a.back() == 30);
    static_assert(a.size() == 3);
    static_assert(!a.empty());
}

// ── fill ──────────────────────────────────────────────────────────────────

void test_array_fill() {
    std::array<int, 4> a = {1, 2, 3, 4};
    a.fill(7);
    CHECK(a[0] == 7 && a[1] == 7 && a[2] == 7 && a[3] == 7);

    // fill on zero-sized array should compile (and be a no-op)
    std::array<int, 0> b{};
    b.fill(42); // no-op
    (void)b;
}

// ── swap ──────────────────────────────────────────────────────────────────

void test_array_swap() {
    std::array<int, 3> a = {1, 2, 3};
    std::array<int, 3> b = {4, 5, 6};
    a.swap(b);
    CHECK(a[0] == 4 && a[1] == 5 && a[2] == 6);
    CHECK(b[0] == 1 && b[1] == 2 && b[2] == 3);

    // free swap (defined in <array> itself)
    std::swap(a, b);
    CHECK(a[0] == 1 && a[1] == 2 && a[2] == 3);
    CHECK(b[0] == 4 && b[1] == 5 && b[2] == 6);
}

// ── operator== ────────────────────────────────────────────────────────────

void test_array_equality() {
    const std::array<int, 3> a = {1, 2, 3};
    const std::array<int, 3> b = {1, 2, 3};
    const std::array<int, 3> c = {1, 2, 4};

    CHECK(a == b);
    CHECK(!(a == c));
    CHECK(!(a != b));  // synthesised from ==
    CHECK(a != c);

    // zero-sized
    const std::array<int, 0> e1{};
    const std::array<int, 0> e2{};
    CHECK(e1 == e2);
}

// ── operator<=> ───────────────────────────────────────────────────────────

void test_array_three_way() {
    const std::array<int, 3> a = {1, 2, 3};
    const std::array<int, 3> b = {1, 2, 3};
    const std::array<int, 3> c = {1, 2, 4};
    const std::array<int, 3> d = {1, 1, 9};

    CHECK((a <=> b) == std::strong_ordering::equal);
    CHECK((a <=> c) == std::strong_ordering::less);
    CHECK((c <=> a) == std::strong_ordering::greater);
    CHECK((a <=> d) == std::strong_ordering::greater);

    // zero-sized
    const std::array<int, 0> e1{};
    const std::array<int, 0> e2{};
    CHECK((e1 <=> e2) == std::strong_ordering::equal);

    // concept check
    static_assert(std::three_way_comparable<std::array<int, 3>>);
}

// ── to_array ──────────────────────────────────────────────────────────────

void test_array_to_array() {
    // lvalue
    int src[3] = {1, 2, 3};
    auto a = std::to_array(src);
    static_assert(std::is_same_v<decltype(a), std::array<int, 3>>);
    CHECK(a[0] == 1 && a[1] == 2 && a[2] == 3);

    // rvalue
    auto b = std::to_array(std::move(src));
    static_assert(std::is_same_v<decltype(b), std::array<int, 3>>);
    CHECK(b[0] == 1 && b[1] == 2 && b[2] == 3);

    // const-qualified element type (strip const)
    const int csrc[2] = {10, 20};
    auto c = std::to_array(csrc);
    static_assert(std::is_same_v<decltype(c)::value_type, int>);
    CHECK(c[0] == 10 && c[1] == 20);

    // constexpr
    constexpr int dsrc[3] = {7, 8, 9};
    constexpr auto d = std::to_array(dsrc);
    static_assert(d[0] == 7 && d[1] == 8 && d[2] == 9);
}

// ── tuple interface ───────────────────────────────────────────────────────

void test_array_tuple_interface() {
    // tuple_size
    static_assert(std::tuple_size<std::array<int, 3>>::value == 3);
    static_assert(std::tuple_size<std::array<double, 0>>::value == 0);

    // tuple_element
    static_assert(std::is_same_v<std::tuple_element<0, std::array<int, 3>>::type, int>);
    static_assert(std::is_same_v<std::tuple_element<2, std::array<double, 3>>::type, double>);

    // get<I> — lvalue
    std::array<double, 3> a = {1.1, 2.2, 3.3};
    CHECK(std::get<0>(a) == 1.1);
    CHECK(std::get<1>(a) == 2.2);
    CHECK(std::get<2>(a) == 3.3);
    std::get<1>(a) = 9.9;
    CHECK(std::get<1>(a) == 9.9);

    // get<I> — const lvalue
    const std::array<double, 3> ca = {4.0, 5.0, 6.0};
    CHECK(std::get<0>(ca) == 4.0);
    static_assert(std::is_same_v<decltype(std::get<0>(ca)), const double&>);

    // get<I> — rvalue (move)
    {
        std::array<int, 2> tmp = {10, 20};
        int v = std::get<0>(std::move(tmp));
        CHECK(v == 10);
        static_assert(std::is_same_v<
            decltype(std::get<0>(std::move(tmp))), int&&>);
    }

    // structured binding
    std::array<int, 3> sb = {7, 8, 9};
    auto [x, y, z] = sb;
    CHECK(x == 7 && y == 8 && z == 9);
}

// ── Zero-size array ───────────────────────────────────────────────────────

void test_array_zero_size() {
    std::array<int, 0> a{};
    CHECK(a.size() == 0);
    CHECK(a.max_size() == 0);
    CHECK(a.empty());
    CHECK(a.data() == nullptr);

    // Iteration over zero-sized array should be empty
    int count = 0;
    for (auto& v : a) { (void)v; ++count; }
    CHECK(count == 0);

    // equality of two zero-sized arrays
    std::array<int, 0> b{};
    CHECK(a == b);
    CHECK((a <=> b) == std::strong_ordering::equal);
}

// ── Deduction guide ───────────────────────────────────────────────────────

void test_array_deduction() {
    std::array a{1, 2, 3};
    static_assert(std::is_same_v<decltype(a), std::array<int, 3>>);
    CHECK(a[0] == 1 && a[1] == 2 && a[2] == 3);

    std::array b{1.0, 2.0};
    static_assert(std::is_same_v<decltype(b), std::array<double, 2>>);
}

// ── Contiguity / data pointer consistency ────────────────────────────────

void test_array_contiguous() {
    std::array<int, 4> a = {10, 20, 30, 40};
    int* p = a.data();
    CHECK(p == &a[0]);
    CHECK(p + 1 == &a[1]);
    CHECK(p + 3 == &a[3]);
    CHECK(a.begin() == p);
    CHECK(a.end()   == p + 4);
}
