// Tests for <atomic>, ported from libc++ test suite.
// Each test_* function exercises runtime behaviour via CHECK().
// No main(); it's auto-generated by tools/gen_main.sh.
#include <atomic>
#include "test.h"

//===----------------------------------------------------------------------===//
// test_memory_order_values
//===----------------------------------------------------------------------===//
void test_memory_order_values() {
    // The scoped enum values must match the GCC __ATOMIC_* integers.
    static_assert(static_cast<int>(std::memory_order_relaxed) == __ATOMIC_RELAXED);
    static_assert(static_cast<int>(std::memory_order_consume) == __ATOMIC_CONSUME);
    static_assert(static_cast<int>(std::memory_order_acquire) == __ATOMIC_ACQUIRE);
    static_assert(static_cast<int>(std::memory_order_release) == __ATOMIC_RELEASE);
    static_assert(static_cast<int>(std::memory_order_acq_rel) == __ATOMIC_ACQ_REL);
    static_assert(static_cast<int>(std::memory_order_seq_cst) == __ATOMIC_SEQ_CST);
    // Inline constexpr aliases
    CHECK(std::memory_order_relaxed == std::memory_order::relaxed);
    CHECK(std::memory_order_seq_cst == std::memory_order::seq_cst);
}

//===----------------------------------------------------------------------===//
// test_atomic_int_load_store
//===----------------------------------------------------------------------===//
void test_atomic_int_load_store() {
    std::atomic<int> a(0);
    CHECK(a.load() == 0);
    a.store(42);
    CHECK(a.load() == 42);
    a.store(7, std::memory_order_relaxed);
    CHECK(a.load(std::memory_order_acquire) == 7);
    // implicit conversion
    int v = a;
    CHECK(v == 7);
    // assignment operator
    a = 99;
    CHECK(a.load() == 99);
}

//===----------------------------------------------------------------------===//
// test_atomic_int_exchange
//===----------------------------------------------------------------------===//
void test_atomic_int_exchange() {
    std::atomic<int> a(10);
    int old = a.exchange(20);
    CHECK(old == 10);
    CHECK(a.load() == 20);
    old = a.exchange(30, std::memory_order_acq_rel);
    CHECK(old == 20);
    CHECK(a.load() == 30);
}

//===----------------------------------------------------------------------===//
// test_atomic_int_cas
//===----------------------------------------------------------------------===//
void test_atomic_int_cas() {
    std::atomic<int> a(5);
    int expected = 5;
    bool ok = a.compare_exchange_strong(expected, 6);
    CHECK(ok);
    CHECK(a.load() == 6);
    CHECK(expected == 5);

    expected = 99; // wrong
    ok = a.compare_exchange_strong(expected, 7);
    CHECK(!ok);
    CHECK(a.load() == 6);
    CHECK(expected == 6); // updated to current

    // compare_exchange_weak (may spuriously fail, loop until success)
    int prev = a.load();
    while (!a.compare_exchange_weak(prev, prev + 1)) {}
    CHECK(a.load() == 7);

    // two-order variant
    expected = 7;
    ok = a.compare_exchange_strong(expected, 100,
                                    std::memory_order_seq_cst,
                                    std::memory_order_acquire);
    CHECK(ok);
    CHECK(a.load() == 100);
}

//===----------------------------------------------------------------------===//
// test_atomic_int_fetch_ops
//===----------------------------------------------------------------------===//
void test_atomic_int_fetch_ops() {
    std::atomic<int> a(10);

    CHECK(a.fetch_add(3) == 10); CHECK(a.load() == 13);
    CHECK(a.fetch_sub(5) == 13); CHECK(a.load() == 8);
    CHECK(a.fetch_and(0xF) == 8); CHECK(a.load() == 8);
    CHECK(a.fetch_or(0x10) == 8); CHECK(a.load() == 0x18);
    CHECK(a.fetch_xor(0xFF) == 0x18); CHECK(a.load() == (0x18 ^ 0xFF));
}

//===----------------------------------------------------------------------===//
// test_atomic_int_increment
//===----------------------------------------------------------------------===//
void test_atomic_int_increment() {
    std::atomic<int> a(5);
    CHECK(a++ == 5); CHECK(a.load() == 6);
    CHECK(a-- == 6); CHECK(a.load() == 5);
    CHECK(++a == 6); CHECK(a.load() == 6);
    CHECK(--a == 5); CHECK(a.load() == 5);
    a += 10; CHECK(a.load() == 15);
    a -= 3;  CHECK(a.load() == 12);
    a &= 0xF; CHECK(a.load() == 12);   // 12 & 0xF == 12
    a |= 0x100; CHECK(a.load() == 268); // 12 | 256
    a ^= 0xFF; CHECK(a.load() == (268 ^ 0xFF));
}

//===----------------------------------------------------------------------===//
// test_atomic_bool_load_store
//===----------------------------------------------------------------------===//
void test_atomic_bool_load_store() {
    std::atomic<bool> b(false);
    CHECK(!b.load());
    b.store(true);
    CHECK(b.load());
    b = false;
    CHECK(!b);
}

//===----------------------------------------------------------------------===//
// test_atomic_pointer
//===----------------------------------------------------------------------===//
void test_atomic_pointer() {
    int arr[5] = {10, 20, 30, 40, 50};
    std::atomic<int*> p(arr);

    CHECK(p.load() == arr);

    int* old = p.fetch_add(1);
    CHECK(old == arr);
    CHECK(p.load() == arr + 1);

    old = p.fetch_sub(1);
    CHECK(old == arr + 1);
    CHECK(p.load() == arr);

    p++;
    CHECK(p.load() == arr + 1);
    ++p;
    CHECK(p.load() == arr + 2);
    p--;
    CHECK(p.load() == arr + 1);
    --p;
    CHECK(p.load() == arr);

    p += 3;
    CHECK(p.load() == arr + 3);
    p -= 2;
    CHECK(p.load() == arr + 1);

    // Dereference through loaded pointer
    CHECK(*p.load() == arr[1]);
}

//===----------------------------------------------------------------------===//
// test_atomic_flag
//===----------------------------------------------------------------------===//
void test_atomic_flag() {
    std::atomic_flag f = ATOMIC_FLAG_INIT;
    CHECK(!f.test());

    bool was = f.test_and_set();
    CHECK(!was);      // was clear
    CHECK(f.test());  // now set

    was = f.test_and_set();
    CHECK(was);       // was set

    f.clear();
    CHECK(!f.test());

    // explicit memory order
    f.test_and_set(std::memory_order_acquire);
    CHECK(f.test(std::memory_order_relaxed));
    f.clear(std::memory_order_release);
    CHECK(!f.test());
}

//===----------------------------------------------------------------------===//
// test_atomic_is_always_lock_free
//===----------------------------------------------------------------------===//
void test_atomic_is_always_lock_free() {
    // On a standard x86-64 platform, int and pointer are always lock-free.
    static_assert(std::atomic<int>::is_always_lock_free);
    static_assert(std::atomic<long long>::is_always_lock_free);
    static_assert(std::atomic<int*>::is_always_lock_free);
    // Runtime is_lock_free must agree
    std::atomic<int> a(0);
    CHECK(a.is_lock_free() == std::atomic<int>::is_always_lock_free);
}

//===----------------------------------------------------------------------===//
// test_atomic_free_functions
//===----------------------------------------------------------------------===//
void test_atomic_free_functions() {
    std::atomic<int> a(0);
    std::atomic_store(&a, 5);
    CHECK(std::atomic_load(&a) == 5);

    std::atomic_store_explicit(&a, 10, std::memory_order_relaxed);
    CHECK(std::atomic_load_explicit(&a, std::memory_order_acquire) == 10);

    int old = std::atomic_exchange(&a, 20);
    CHECK(old == 10);
    CHECK(std::atomic_load(&a) == 20);

    old = std::atomic_exchange_explicit(&a, 30, std::memory_order_acq_rel);
    CHECK(old == 20);

    int exp = 30;
    bool ok = std::atomic_compare_exchange_strong(&a, &exp, 40);
    CHECK(ok);
    CHECK(std::atomic_load(&a) == 40);

    exp = 99;
    ok = std::atomic_compare_exchange_strong(&a, &exp, 50);
    CHECK(!ok);
    CHECK(exp == 40);

    CHECK(std::atomic_fetch_add(&a, 5) == 40);
    CHECK(std::atomic_fetch_sub(&a, 3) == 45);
    CHECK(std::atomic_load(&a) == 42);

    CHECK(std::atomic_fetch_and(&a, 0xF) == 42);  // 42 = 0x2A
    CHECK(std::atomic_fetch_or(&a, 0x80) == (42 & 0xF));
    std::atomic_store(&a, 0xFF);
    CHECK(std::atomic_fetch_xor(&a, 0x0F) == 0xFF);
    CHECK(std::atomic_load(&a) == 0xF0);

    CHECK(std::atomic_is_lock_free(&a));
}

//===----------------------------------------------------------------------===//
// test_atomic_ref_int
//===----------------------------------------------------------------------===//
void test_atomic_ref_int() {
    int x = 10;
    std::atomic_ref<int> r(x);

    r.store(42);
    CHECK(x == 42);
    CHECK(r.load() == 42);

    int old = r.exchange(100);
    CHECK(old == 42);
    CHECK(x == 100);

    int exp = 100;
    bool ok = r.compare_exchange_strong(exp, 200);
    CHECK(ok);
    CHECK(x == 200);

    CHECK(r.fetch_add(5) == 200); CHECK(x == 205);
    CHECK(r.fetch_sub(5) == 205); CHECK(x == 200);
    CHECK(r.fetch_and(0xFF) == 200); CHECK(x == 200);
    CHECK(r.fetch_or(0xFF00) == 200);
    r.store(0);
    r.fetch_xor(0xAB);
    CHECK(x == 0xAB);
}

//===----------------------------------------------------------------------===//
// test_atomic_ref_pointer
//===----------------------------------------------------------------------===//
void test_atomic_ref_pointer() {
    int arr[4] = {1, 2, 3, 4};
    int* p = arr;
    std::atomic_ref<int*> r(p);

    r.store(arr + 1);
    CHECK(p == arr + 1);

    int* old = r.fetch_add(1);
    CHECK(old == arr + 1);
    CHECK(p == arr + 2);

    r.fetch_sub(2);
    CHECK(p == arr);
}

//===----------------------------------------------------------------------===//
// test_atomic_fence
//===----------------------------------------------------------------------===//
void test_atomic_fence() {
    // Just verify the calls don't crash; correctness is platform/hardware level.
    std::atomic_thread_fence(std::memory_order_seq_cst);
    std::atomic_signal_fence(std::memory_order_acquire);
}

//===----------------------------------------------------------------------===//
// test_kill_dependency
//===----------------------------------------------------------------------===//
void test_kill_dependency() {
    int x = 42;
    int y = std::kill_dependency(x);
    CHECK(y == 42);
}

//===----------------------------------------------------------------------===//
// test_atomic_typedefs
//===----------------------------------------------------------------------===//
void test_atomic_typedefs() {
    // Verify the typedefs compile and work
    std::atomic_int    ai(1);  CHECK(ai.load() == 1);
    std::atomic_uint   au(2u); CHECK(au.load() == 2u);
    std::atomic_bool   ab(true); CHECK(ab.load());
    std::atomic_llong  all(3LL); CHECK(all.load() == 3LL);
    std::atomic_size_t as_(4u); CHECK(as_.load() == 4u);
    std::atomic_int64_t a64(5LL); CHECK(a64.load() == 5LL);
    std::atomic_uint64_t au64(6ULL); CHECK(au64.load() == 6ULL);
    std::atomic_intptr_t aip(7); CHECK(aip.load() == 7);
}

//===----------------------------------------------------------------------===//
// test_atomic_float
//===----------------------------------------------------------------------===//
void test_atomic_float() {
    std::atomic<float> f(1.0f);
    CHECK(f.load() == 1.0f);
    f.store(2.0f);
    CHECK(f.load() == 2.0f);

    float old = f.fetch_add(0.5f);
    CHECK(old == 2.0f);
    // fetch_add is CAS-loop based, result may have float rounding
    // just check it moved in the right direction
    CHECK(f.load() > 2.0f);

    old = f.fetch_sub(0.5f);
    CHECK(f.load() < old + 0.001f);  // decreased by ~0.5
}
