// Tests for <charconv> integer to_chars / from_chars.
// Ported from libc++ test/std/utilities/charconv/charconv.to.chars/integral.pass.cpp
// and charconv.from.chars/integral.pass.cpp.
// No main(); auto-generated by tools/gen_main.sh.
#include <charconv>
#include <cstdint>
#include <cstring>   // memcmp, strcmp
#include <limits>    // std::numeric_limits
#include "test.h"

//===----------------------------------------------------------------------===//
// Helpers
//===----------------------------------------------------------------------===//

// Convert integer to string via to_chars; return true and fill buf on success.
template<class T>
static bool to_str(char* buf, int bufsz, T value, int base = 10) {
    auto r = std::to_chars(buf, buf + bufsz, value, base);
    if (r.ec != std::errc{}) return false;
    *r.ptr = '\0';
    return true;
}

// Round-trip: convert value to chars then parse back; check equality.
template<class T>
static bool roundtrip(T value, int base = 10) {
    char buf[128];
    auto r = std::to_chars(buf, buf + sizeof(buf), value, base);
    if (r.ec != std::errc{}) return false;
    T v2 = 0;
    auto r2 = std::from_chars(buf, r.ptr, v2, base);
    return r2.ec == std::errc{} && r2.ptr == r.ptr && v2 == value;
}

//===----------------------------------------------------------------------===//
// test_charconv_types — struct layout; no operator bool in standard
//===----------------------------------------------------------------------===//
void test_charconv_types() {
    // to_chars_result: check ec field directly (no operator bool in standard)
    {
        char buf[4];
        auto r = std::to_chars(buf, buf + sizeof(buf), 42);
        CHECK(r.ec == std::errc{});
    }
    {
        char buf[2];
        auto r = std::to_chars(buf, buf + 2, 999);
        CHECK(r.ec == std::errc::value_too_large);
        CHECK(r.ec != std::errc{});
    }
    // from_chars_result: check ec field directly
    {
        int v = 0;
        const char* s = "42";
        auto r = std::from_chars(s, s + 2, v);
        CHECK(r.ec == std::errc{});
        CHECK(v == 42);
    }
    {
        int v = 0;
        const char* s = "xyz";
        auto r = std::from_chars(s, s + 3, v);
        CHECK(r.ec == std::errc::invalid_argument);
        CHECK(r.ec != std::errc{});
    }
    // operator== on results
    {
        char buf[8];
        auto r1 = std::to_chars(buf, buf + 8, 7);
        auto r2 = std::to_chars(buf, buf + 8, 7);
        CHECK(r1 == r2);
    }
}

//===----------------------------------------------------------------------===//
// test_charconv_roundtrip_base10 — basic decimal round-trips
//===----------------------------------------------------------------------===//
void test_charconv_roundtrip_base10() {
    // int
    CHECK(roundtrip(0));
    CHECK(roundtrip(1));
    CHECK(roundtrip(-1));
    CHECK(roundtrip(42));
    CHECK(roundtrip(-42));
    CHECK(roundtrip(2147483647));    // INT_MAX
    CHECK(roundtrip(-2147483648LL)); // INT_MIN (as long long to avoid UB)

    // unsigned int
    CHECK(roundtrip(0u));
    CHECK(roundtrip(4294967295u)); // UINT_MAX

    // long long
    CHECK(roundtrip(9223372036854775807LL));  // LLONG_MAX
    CHECK(roundtrip(-9223372036854775807LL - 1)); // LLONG_MIN

    // unsigned long long
    CHECK(roundtrip(18446744073709551615ULL)); // ULLONG_MAX

    // short
    CHECK(roundtrip<short>(0));
    CHECK(roundtrip<short>(32767));
    CHECK(roundtrip<short>(-32768));

    // unsigned short
    CHECK(roundtrip<unsigned short>(0));
    CHECK(roundtrip<unsigned short>(65535));

    // char (signed and unsigned)
    CHECK(roundtrip<signed char>(0));
    CHECK(roundtrip<signed char>(127));
    CHECK(roundtrip<signed char>(-128));
    CHECK(roundtrip<unsigned char>(0));
    CHECK(roundtrip<unsigned char>(255));
}

//===----------------------------------------------------------------------===//
// test_charconv_roundtrip_bases — base 2, 8, 16 + arbitrary
//===----------------------------------------------------------------------===//
void test_charconv_roundtrip_bases() {
    // base 2
    CHECK(roundtrip(0, 2));
    CHECK(roundtrip(1, 2));
    CHECK(roundtrip(255u, 2));
    CHECK(roundtrip(0xDEADBEEFu, 2));
    CHECK(roundtrip(-42, 2));
    CHECK(roundtrip(2147483647, 2));
    CHECK(roundtrip(-2147483647 - 1, 2));

    // base 8
    CHECK(roundtrip(0, 8));
    CHECK(roundtrip(7, 8));
    CHECK(roundtrip(511u, 8));
    CHECK(roundtrip(-1, 8));
    CHECK(roundtrip(0xFFFFFFFFu, 8));

    // base 16
    CHECK(roundtrip(0, 16));
    CHECK(roundtrip(15u, 16));
    CHECK(roundtrip(255u, 16));
    CHECK(roundtrip(0xDEADBEEFu, 16));
    CHECK(roundtrip(-1, 16));
    CHECK(roundtrip(9223372036854775807LL, 16));

    // base 36
    CHECK(roundtrip(0, 36));
    CHECK(roundtrip(35, 36));
    CHECK(roundtrip(12345, 36));
    CHECK(roundtrip(-999999, 36));
    CHECK(roundtrip(4294967295u, 36));

    // base 3, 7, 11, 13
    CHECK(roundtrip(0, 3));
    CHECK(roundtrip(100, 7));
    CHECK(roundtrip(-100, 11));
    CHECK(roundtrip(999999, 13));
}

//===----------------------------------------------------------------------===//
// test_charconv_to_chars_output — verify exact character output
//===----------------------------------------------------------------------===//
void test_charconv_to_chars_output() {
    char buf[128];

    // zero
    CHECK(to_str(buf, sizeof(buf), 0));
    CHECK(std::strcmp(buf, "0") == 0);

    // negative
    CHECK(to_str(buf, sizeof(buf), -1));
    CHECK(std::strcmp(buf, "-1") == 0);

    CHECK(to_str(buf, sizeof(buf), -128));
    CHECK(std::strcmp(buf, "-128") == 0);

    // base 2 examples
    CHECK(to_str(buf, sizeof(buf), 0u, 2));
    CHECK(std::strcmp(buf, "0") == 0);

    CHECK(to_str(buf, sizeof(buf), 1u, 2));
    CHECK(std::strcmp(buf, "1") == 0);

    CHECK(to_str(buf, sizeof(buf), 10u, 2));
    CHECK(std::strcmp(buf, "1010") == 0);

    CHECK(to_str(buf, sizeof(buf), 255u, 2));
    CHECK(std::strcmp(buf, "11111111") == 0);

    // base 8
    CHECK(to_str(buf, sizeof(buf), 8u, 8));
    CHECK(std::strcmp(buf, "10") == 0);

    CHECK(to_str(buf, sizeof(buf), 255u, 8));
    CHECK(std::strcmp(buf, "377") == 0);

    // base 16
    CHECK(to_str(buf, sizeof(buf), 255u, 16));
    CHECK(std::strcmp(buf, "ff") == 0);

    CHECK(to_str(buf, sizeof(buf), 0xDEADu, 16));
    CHECK(std::strcmp(buf, "dead") == 0);

    // base 36: 35 -> "z"
    CHECK(to_str(buf, sizeof(buf), 35, 36));
    CHECK(std::strcmp(buf, "z") == 0);

    // large decimal
    CHECK(to_str(buf, sizeof(buf), 1000000000));
    CHECK(std::strcmp(buf, "1000000000") == 0);
}

//===----------------------------------------------------------------------===//
// test_charconv_buffer_too_small — errc::value_too_large
//===----------------------------------------------------------------------===//
void test_charconv_buffer_too_small() {
    char buf[4];

    // 5-digit number in 4-char buffer
    {
        auto r = std::to_chars(buf, buf + 4, 12345);
        CHECK(r.ec == std::errc::value_too_large);
        CHECK(r.ptr == buf + 4);
    }

    // Exactly fits
    {
        auto r = std::to_chars(buf, buf + 4, 9999);
        CHECK(r.ec == std::errc{});
    }

    // Negative: '-' plus digits
    {
        auto r = std::to_chars(buf, buf + 4, -999);
        CHECK(r.ec == std::errc{});  // "-999" = 4 chars, fits
    }
    {
        auto r = std::to_chars(buf, buf + 4, -9999);
        CHECK(r.ec == std::errc::value_too_large);
    }

    // base 2: 1-byte buffer for value needing multiple bits
    {
        char tiny[3];
        auto r = std::to_chars(tiny, tiny + 3, 15u, 2); // "1111" needs 4
        CHECK(r.ec == std::errc::value_too_large);
    }

    // base 16: small buffer
    {
        char tiny[2];
        auto r = std::to_chars(tiny, tiny + 2, 256u, 16); // "100" needs 3
        CHECK(r.ec == std::errc::value_too_large);
    }
}

//===----------------------------------------------------------------------===//
// test_charconv_from_chars_errors — errc::invalid_argument / result_out_of_range
//===----------------------------------------------------------------------===//
void test_charconv_from_chars_errors() {
    // invalid_argument: no valid digits at all
    {
        int v = 99;
        const char* s = "xyz";
        auto r = std::from_chars(s, s + 3, v);
        CHECK(r.ec == std::errc::invalid_argument);
        CHECK(r.ptr == s);
        CHECK(v == 99); // unchanged
    }
    {
        int v = 0;
        const char* s = "";
        auto r = std::from_chars(s, s, v);
        CHECK(r.ec == std::errc::invalid_argument);
    }
    {
        unsigned v = 0;
        const char* s = "-1";
        // '-' is not a valid digit for unsigned in base 10
        auto r = std::from_chars(s, s + 2, v);
        CHECK(r.ec == std::errc::invalid_argument);
    }

    // result_out_of_range: valid digits but overflows T
    {
        int8_t v = 0;
        const char* s = "128"; // one past INT8_MAX
        auto r = std::from_chars(s, s + 3, v);
        CHECK(r.ec == std::errc::result_out_of_range);
    }
    {
        uint8_t v = 0;
        const char* s = "256"; // one past UINT8_MAX
        auto r = std::from_chars(s, s + 3, v);
        CHECK(r.ec == std::errc::result_out_of_range);
    }
    {
        int v = 0;
        const char* s = "2147483648"; // INT_MAX + 1
        auto r = std::from_chars(s, s + 10, v);
        CHECK(r.ec == std::errc::result_out_of_range);
    }
    {
        unsigned long long v = 0;
        const char* s = "18446744073709551616"; // ULLONG_MAX + 1
        auto r = std::from_chars(s, s + 20, v);
        CHECK(r.ec == std::errc::result_out_of_range);
    }

    // invalid digit for base
    {
        unsigned v = 0;
        const char* s = "2"; // digit 2 invalid for base 2
        auto r = std::from_chars(s, s + 1, v, 2);
        CHECK(r.ec == std::errc::invalid_argument);
    }
    {
        unsigned v = 0;
        const char* s = "8"; // digit 8 invalid for base 8
        auto r = std::from_chars(s, s + 1, v, 8);
        CHECK(r.ec == std::errc::invalid_argument);
    }
    {
        unsigned v = 0;
        const char* s = "g"; // 'g' invalid for base 16
        auto r = std::from_chars(s, s + 1, v, 16);
        CHECK(r.ec == std::errc::invalid_argument);
    }
}

//===----------------------------------------------------------------------===//
// test_charconv_from_chars_partial — ptr points past consumed chars
//===----------------------------------------------------------------------===//
void test_charconv_from_chars_partial() {
    // stops at non-digit
    {
        int v = 0;
        const char* s = "42abc";
        auto r = std::from_chars(s, s + 5, v);
        CHECK(r.ec == std::errc{});
        CHECK(v == 42);
        CHECK(r.ptr == s + 2);
    }
    // stops at wrong-base digit
    {
        unsigned v = 0;
        const char* s = "101z";
        auto r = std::from_chars(s, s + 4, v, 2);
        CHECK(r.ec == std::errc{});
        CHECK(v == 5u); // "101" in base 2 = 5
        CHECK(r.ptr == s + 3);
    }
    // leading zeros treated as valid
    {
        int v = 0;
        const char* s = "007";
        auto r = std::from_chars(s, s + 3, v);
        CHECK(r.ec == std::errc{});
        CHECK(v == 7);
        CHECK(r.ptr == s + 3);
    }
}

//===----------------------------------------------------------------------===//
// test_charconv_negative — negative integers in various bases
//===----------------------------------------------------------------------===//
void test_charconv_negative() {
    CHECK(roundtrip(-1, 2));
    CHECK(roundtrip(-127, 2));
    CHECK(roundtrip(-128, 2)); // INT8_MIN
    CHECK(roundtrip(-1, 8));
    CHECK(roundtrip(-32768, 8)); // INT16_MIN
    CHECK(roundtrip(-1, 16));
    CHECK(roundtrip(std::numeric_limits<int>::min(), 10));
    CHECK(roundtrip(std::numeric_limits<int>::min(), 16));
    CHECK(roundtrip(std::numeric_limits<long long>::min(), 10));
    CHECK(roundtrip(std::numeric_limits<long long>::min(), 16));
}

//===----------------------------------------------------------------------===//
// test_charconv_static — compile-time checks
//===----------------------------------------------------------------------===//
void test_charconv_static() {
    // chars_format bitwise operations
    static_assert((std::chars_format::fixed | std::chars_format::scientific)
                  == std::chars_format::general);
    static_assert((std::chars_format::general & std::chars_format::fixed)
                  == std::chars_format::fixed);

    // to_chars_result / from_chars_result are standard-layout
    static_assert(__is_standard_layout(std::to_chars_result));
    static_assert(__is_standard_layout(std::from_chars_result));

    // is_integral coverage: bool excluded
    static_assert(!std::is_same_v<bool, int>);
}
