// Consolidated tests for all C-library wrapper headers.
// Each test_ function covers a representative sample of names from its header.
// Uses CHECK() for runtime checks and static_assert for compile-time checks.
// No main() — auto-generated by tools/gen_main.sh.

#include "test.h"

// ── cstring ────────────────────────────────────────────────────────────────
#include <cstring>

void test_cstring_memcpy() {
    char dst[8] = {};
    const char src[] = "hello";
    std::memcpy(dst, src, 6);
    CHECK(std::strcmp(dst, "hello") == 0);
}

void test_cstring_strlen() {
    CHECK(std::strlen("abc") == 3u);
    CHECK(std::strlen("") == 0u);
}

void test_cstring_memset() {
    char buf[4] = {1, 2, 3, 4};
    std::memset(buf, 0, 4);
    CHECK(buf[0] == 0 && buf[3] == 0);
}

void test_cstring_strchr() {
    const char* s = "hello";
    CHECK(std::strchr(s, 'l') == s + 2);
    CHECK(std::strchr(s, 'z') == nullptr);
}

void test_cstring_memmove() {
    char buf[] = "abcde";
    std::memmove(buf + 1, buf, 4);
    CHECK(buf[1] == 'a' && buf[2] == 'b');
}

// ── cstdlib ────────────────────────────────────────────────────────────────
#include <cstdlib>

void test_cstdlib_abs() {
    CHECK(std::abs(-5) == 5);
    CHECK(std::abs(3) == 3);
    CHECK(std::labs(-100L) == 100L);
    CHECK(std::llabs(-100LL) == 100LL);
}

void test_cstdlib_atoi() {
    CHECK(std::atoi("42") == 42);
    CHECK(std::atoi("-7") == -7);
}

void test_cstdlib_strtol() {
    char* end = nullptr;
    CHECK(std::strtol("123", &end, 10) == 123L);
}

void test_cstdlib_div() {
    std::div_t r = std::div(7, 3);
    CHECK(r.quot == 2 && r.rem == 1);
    std::ldiv_t lr = std::ldiv(7L, 3L);
    CHECK(lr.quot == 2L && lr.rem == 1L);
}

void test_cstdlib_malloc() {
    void* p = std::malloc(16);
    CHECK(p != nullptr);
    std::free(p);
}

// ── cmath ──────────────────────────────────────────────────────────────────
#include <cmath>

void test_cmath_sqrt() {
    CHECK(std::sqrt(4.0) == 2.0);
    CHECK(std::sqrtf(9.0f) == 3.0f);
}

void test_cmath_sin_cos() {
    // sin(0) == 0, cos(0) == 1
    CHECK(std::sin(0.0) == 0.0);
    CHECK(std::cos(0.0) == 1.0);
}

void test_cmath_isnan() {
    double nan_val = std::nan("1");
    CHECK(std::isnan(nan_val));
    CHECK(!std::isnan(1.0));
}

void test_cmath_isinf() {
    double inf_val = HUGE_VAL;
    CHECK(std::isinf(inf_val));
    CHECK(!std::isinf(1.0));
}

void test_cmath_abs() {
    CHECK(std::abs(-3.0) == 3.0);
    CHECK(std::fabs(-2.5) == 2.5);
}

void test_cmath_lerp() {
    CHECK(std::lerp(0.0, 10.0, 0.5) == 5.0);
    CHECK(std::lerp(0.0f, 4.0f, 0.25f) == 1.0f);
}

void test_cmath_hypot3() {
    double r = std::hypot(3.0, 4.0, 0.0);
    CHECK(r == 5.0);
}

void test_cmath_floor_ceil() {
    CHECK(std::floor(2.7) == 2.0);
    CHECK(std::ceil(2.1) == 3.0);
}

void test_cmath_pow() {
    CHECK(std::pow(2.0, 10.0) == 1024.0);
}

// ── cassert ────────────────────────────────────────────────────────────────
#include <cassert>

void test_cassert_macro() {
    // assert(true) must not abort
    assert(1 == 1);
    // assert is a macro — verify it's defined
#ifdef assert
    static_assert(true, "assert macro is defined");
#endif
}

// ── cctype ─────────────────────────────────────────────────────────────────
#include <cctype>

void test_cctype_isalpha() {
    CHECK(std::isalpha('a'));
    CHECK(!std::isalpha('1'));
}

void test_cctype_toupper() {
    CHECK(std::toupper('a') == 'A');
    CHECK(std::tolower('Z') == 'z');
}

void test_cctype_isdigit() {
    CHECK(std::isdigit('5'));
    CHECK(!std::isdigit('x'));
}

// ── cwctype ────────────────────────────────────────────────────────────────
#include <cwctype>

void test_cwctype_iswalpha() {
    CHECK(std::iswalpha(L'a'));
    CHECK(!std::iswalpha(L'1'));
}

void test_cwctype_towupper() {
    CHECK(std::towupper(L'a') == L'A');
    CHECK(std::towlower(L'Z') == L'z');
}

// ── cerrno ─────────────────────────────────────────────────────────────────
#include <cerrno>

void test_cerrno_macro() {
    errno = 0;
    CHECK(errno == 0);
    // EDOM, ERANGE must be defined
    static_assert(EDOM != 0, "EDOM should be nonzero");
    static_assert(ERANGE != 0, "ERANGE should be nonzero");
}

// ── cstdio ─────────────────────────────────────────────────────────────────
#include <cstdio>

void test_cstdio_snprintf() {
    char buf[32];
    int n = std::snprintf(buf, sizeof(buf), "%d", 42);
    CHECK(n == 2);
    CHECK(std::strcmp(buf, "42") == 0);
}

void test_cstdio_file_types() {
    // Just check that the type names are available in std
    static_assert(sizeof(std::FILE) > 0 || true, "FILE must be accessible");
    static_assert(sizeof(std::fpos_t) > 0, "fpos_t must be accessible");
}

// ── cwchar ─────────────────────────────────────────────────────────────────
#include <cwchar>

void test_cwchar_wcslen() {
    CHECK(std::wcslen(L"hello") == 5u);
    CHECK(std::wcslen(L"") == 0u);
}

void test_cwchar_wmemcpy() {
    wchar_t dst[8] = {};
    std::wmemcpy(dst, L"hi", 3);
    CHECK(dst[0] == L'h' && dst[1] == L'i' && dst[2] == L'\0');
}

// ── cstdarg ────────────────────────────────────────────────────────────────
#include <cstdarg>

static int sum_va(int count, ...) {
    std::va_list ap;
    va_start(ap, count);
    int s = 0;
    for (int i = 0; i < count; ++i)
        s += va_arg(ap, int);
    va_end(ap);
    return s;
}

void test_cstdarg_va_list() {
    CHECK(sum_va(3, 1, 2, 3) == 6);
    CHECK(sum_va(0) == 0);
}

// ── cinttypes ──────────────────────────────────────────────────────────────
#include <cinttypes>

void test_cinttypes_imaxabs() {
    CHECK(std::imaxabs(-99) == 99);
    CHECK(std::imaxabs(42) == 42);
}

void test_cinttypes_imaxdiv() {
    std::imaxdiv_t r = std::imaxdiv(10, 3);
    CHECK(r.quot == 3 && r.rem == 1);
}

void test_cinttypes_strtoimax() {
    char* end = nullptr;
    // "ff" in base 16 is 255
    CHECK(std::strtoimax("ff", &end, 16) == 255);
    // "255" in base 10 is 255
    CHECK(std::strtoimax("255", &end, 10) == 255);
}

void test_cinttypes_macros() {
    // PRId32 etc. are macros — just ensure they produce strings
    static_assert(sizeof(PRId32) > 1, "PRId32 must be defined");
    static_assert(sizeof(PRIu64) > 1, "PRIu64 must be defined");
}
