// test/deque.cpp — tests for <deque>
// Each test_ function is a no-arg free function using CHECK and static_assert.
// main() is auto-generated by tools/gen_main.sh.

#include <deque>
#include "test.h"

//===----------------------------------------------------------------------===//
// Basic type checks
//===----------------------------------------------------------------------===//

void test_deque_types() {
    static_assert(std::is_same_v<std::deque<int>::value_type, int>);
    static_assert(std::is_same_v<std::deque<int>::allocator_type, std::allocator<int>>);
    static_assert(std::is_same_v<std::deque<int>::reference, int&>);
    static_assert(std::is_same_v<std::deque<int>::const_reference, const int&>);
    static_assert(std::is_same_v<std::deque<int>::pointer, int*>);
    static_assert(std::is_same_v<std::deque<int>::const_pointer, const int*>);
}

//===----------------------------------------------------------------------===//
// Default construction
//===----------------------------------------------------------------------===//

void test_deque_default_ctor() {
    std::deque<int> d;
    CHECK(d.empty());
    CHECK(d.size() == 0);
    CHECK(d.begin() == d.end());
}

//===----------------------------------------------------------------------===//
// push_back / push_front
//===----------------------------------------------------------------------===//

void test_deque_push_back() {
    std::deque<int> d;
    for (int i = 0; i < 100; ++i)
        d.push_back(i);
    CHECK(d.size() == 100);
    for (int i = 0; i < 100; ++i)
        CHECK(d[i] == i);
}

void test_deque_push_front() {
    std::deque<int> d;
    for (int i = 0; i < 100; ++i)
        d.push_front(i);
    CHECK(d.size() == 100);
    for (int i = 0; i < 100; ++i)
        CHECK(d[i] == 99 - i);
}

void test_deque_push_mixed() {
    std::deque<int> d;
    d.push_back(1);
    d.push_front(0);
    d.push_back(2);
    d.push_front(-1);
    CHECK(d.size() == 4);
    CHECK(d[0] == -1);
    CHECK(d[1] == 0);
    CHECK(d[2] == 1);
    CHECK(d[3] == 2);
}

//===----------------------------------------------------------------------===//
// pop_back / pop_front
//===----------------------------------------------------------------------===//

void test_deque_pop_back() {
    std::deque<int> d;
    d.push_back(1);
    d.push_back(2);
    d.push_back(3);
    d.pop_back();
    CHECK(d.size() == 2);
    CHECK(d.back() == 2);
}

void test_deque_pop_front() {
    std::deque<int> d;
    d.push_back(1);
    d.push_back(2);
    d.push_back(3);
    d.pop_front();
    CHECK(d.size() == 2);
    CHECK(d.front() == 2);
}

//===----------------------------------------------------------------------===//
// front / back
//===----------------------------------------------------------------------===//

void test_deque_front_back() {
    std::deque<int> d;
    d.push_back(10);
    d.push_back(20);
    d.push_back(30);
    CHECK(d.front() == 10);
    CHECK(d.back()  == 30);
    d.front() = 100;
    d.back()  = 300;
    CHECK(d[0] == 100);
    CHECK(d[2] == 300);
}

//===----------------------------------------------------------------------===//
// operator[] / at
//===----------------------------------------------------------------------===//

void test_deque_subscript() {
    std::deque<int> d;
    for (int i = 0; i < 50; ++i)
        d.push_back(i * 2);
    for (int i = 0; i < 50; ++i)
        CHECK(d[i] == i * 2);
}

void test_deque_at() {
    std::deque<int> d;
    d.push_back(10);
    d.push_back(20);
    CHECK(d.at(0) == 10);
    CHECK(d.at(1) == 20);
}

//===----------------------------------------------------------------------===//
// Count constructor / copy constructor / assignment
//===----------------------------------------------------------------------===//

void test_deque_count_ctor() {
    std::deque<int> d(5, 42);
    CHECK(d.size() == 5);
    for (std::size_t i = 0; i < 5; ++i)
        CHECK(d[i] == 42);
}

void test_deque_count_default_ctor() {
    std::deque<int> d(10);
    CHECK(d.size() == 10);
    for (std::size_t i = 0; i < 10; ++i)
        CHECK(d[i] == 0);
}

void test_deque_copy_ctor() {
    std::deque<int> d;
    for (int i = 0; i < 20; ++i)
        d.push_back(i);
    std::deque<int> d2(d);
    CHECK(d2.size() == 20);
    for (int i = 0; i < 20; ++i)
        CHECK(d2[i] == i);
    // Independence
    d2[0] = 999;
    CHECK(d[0] == 0);
}

void test_deque_move_ctor() {
    std::deque<int> d;
    for (int i = 0; i < 20; ++i)
        d.push_back(i);
    std::deque<int> d2(std::move(d));
    CHECK(d2.size() == 20);
    CHECK(d.empty());
    for (int i = 0; i < 20; ++i)
        CHECK(d2[i] == i);
}

void test_deque_copy_assign() {
    std::deque<int> d;
    for (int i = 0; i < 15; ++i)
        d.push_back(i);
    std::deque<int> d2;
    d2 = d;
    CHECK(d2.size() == 15);
    for (int i = 0; i < 15; ++i)
        CHECK(d2[i] == i);
}

void test_deque_move_assign() {
    std::deque<int> d;
    for (int i = 0; i < 15; ++i)
        d.push_back(i);
    std::deque<int> d2;
    d2 = std::move(d);
    CHECK(d2.size() == 15);
    for (int i = 0; i < 15; ++i)
        CHECK(d2[i] == i);
}

//===----------------------------------------------------------------------===//
// Range constructor + iterator constructor
//===----------------------------------------------------------------------===//

void test_deque_range_ctor() {
    int arr[] = {1, 2, 3, 4, 5};
    std::deque<int> d(arr, arr + 5);
    CHECK(d.size() == 5);
    for (int i = 0; i < 5; ++i)
        CHECK(d[i] == i + 1);
}

//===----------------------------------------------------------------------===//
// initializer_list constructor / assign
//===----------------------------------------------------------------------===//

void test_deque_il_ctor() {
    std::deque<int> d{1, 2, 3, 4, 5};
    CHECK(d.size() == 5);
    CHECK(d[0] == 1);
    CHECK(d[4] == 5);
}

void test_deque_il_assign() {
    std::deque<int> d;
    d = {10, 20, 30};
    CHECK(d.size() == 3);
    CHECK(d[0] == 10);
    CHECK(d[2] == 30);
}

//===----------------------------------------------------------------------===//
// assign overloads
//===----------------------------------------------------------------------===//

void test_deque_assign_count() {
    std::deque<int> d{1, 2, 3};
    d.assign(5, 99);
    CHECK(d.size() == 5);
    for (std::size_t i = 0; i < 5; ++i)
        CHECK(d[i] == 99);
    d.assign(2, 7);
    CHECK(d.size() == 2);
    CHECK(d[0] == 7);
}

void test_deque_assign_iter() {
    int arr[] = {5, 6, 7, 8};
    std::deque<int> d{1, 2, 3};
    d.assign(arr, arr + 4);
    CHECK(d.size() == 4);
    for (int i = 0; i < 4; ++i)
        CHECK(d[i] == 5 + i);
}

//===----------------------------------------------------------------------===//
// Iterators
//===----------------------------------------------------------------------===//

void test_deque_iterators() {
    std::deque<int> d;
    for (int i = 0; i < 10; ++i)
        d.push_back(i);
    int n = 0;
    for (auto it = d.begin(); it != d.end(); ++it, ++n)
        CHECK(*it == n);
    CHECK(n == 10);

    // reverse iterators
    n = 9;
    for (auto it = d.rbegin(); it != d.rend(); ++it, --n)
        CHECK(*it == n);
}

void test_deque_const_iterators() {
    const std::deque<int> d{1, 2, 3, 4, 5};
    // d[0]==1, d[1]==2, ...
    int n = 0;
    for (auto it = d.begin(); it != d.end(); ++it, ++n)
        CHECK(*it == n + 1);

    n = 0;
    for (auto it = d.cbegin(); it != d.cend(); ++it, ++n)
        CHECK(*it == n + 1);
}

void test_deque_iterator_arithmetic() {
    std::deque<int> d;
    for (int i = 0; i < 20; ++i)
        d.push_back(i);
    auto it = d.begin();
    it += 5;
    CHECK(*it == 5);
    it -= 3;
    CHECK(*it == 2);
    CHECK(*(it + 7) == 9);
    CHECK(it[3] == 5);
    CHECK(d.end() - d.begin() == 20);
}

//===----------------------------------------------------------------------===//
// resize
//===----------------------------------------------------------------------===//

void test_deque_resize() {
    std::deque<int> d{1, 2, 3};
    d.resize(6, 0);
    CHECK(d.size() == 6);
    CHECK(d[0] == 1);
    CHECK(d[3] == 0);
    d.resize(2);
    CHECK(d.size() == 2);
    CHECK(d[1] == 2);
}

//===----------------------------------------------------------------------===//
// clear / shrink_to_fit
//===----------------------------------------------------------------------===//

void test_deque_clear() {
    std::deque<int> d{1, 2, 3, 4, 5};
    d.clear();
    CHECK(d.empty());
    CHECK(d.size() == 0);
    // Can push after clear
    d.push_back(42);
    CHECK(d.size() == 1);
    CHECK(d[0] == 42);
}

void test_deque_shrink_to_fit() {
    std::deque<int> d;
    for (int i = 0; i < 1000; ++i)
        d.push_back(i);
    d.clear();
    d.shrink_to_fit();
    CHECK(d.empty());
    d.push_back(1);
    CHECK(d.size() == 1);
}

//===----------------------------------------------------------------------===//
// emplace_front / emplace_back / emplace
//===----------------------------------------------------------------------===//

struct Point {
    int x, y;
    Point(int x_, int y_) : x(x_), y(y_) {}
};

void test_deque_emplace_back() {
    std::deque<Point> d;
    d.emplace_back(1, 2);
    d.emplace_back(3, 4);
    CHECK(d.size() == 2);
    CHECK(d[0].x == 1 && d[0].y == 2);
    CHECK(d[1].x == 3 && d[1].y == 4);
}

void test_deque_emplace_front() {
    std::deque<Point> d;
    d.emplace_front(3, 4);
    d.emplace_front(1, 2);
    CHECK(d.size() == 2);
    CHECK(d[0].x == 1 && d[0].y == 2);
    CHECK(d[1].x == 3 && d[1].y == 4);
}

void test_deque_emplace() {
    std::deque<int> d{1, 2, 4, 5};
    auto it = d.emplace(d.begin() + 2, 3);
    CHECK(d.size() == 5);
    CHECK(*it == 3);
    CHECK(d[2] == 3);
    for (int i = 0; i < 5; ++i)
        CHECK(d[i] == i + 1);
}

//===----------------------------------------------------------------------===//
// insert single / range / initializer_list
//===----------------------------------------------------------------------===//

void test_deque_insert_single() {
    std::deque<int> d{1, 2, 4, 5};
    auto it = d.insert(d.begin() + 2, 3);
    CHECK(d.size() == 5);
    CHECK(*it == 3);
    for (int i = 0; i < 5; ++i)
        CHECK(d[i] == i + 1);
}

void test_deque_insert_n() {
    std::deque<int> d{1, 5};
    d.insert(d.begin() + 1, 3, 2);
    // d should be {1, 2, 2, 2, 5}
    CHECK(d.size() == 5);
    CHECK(d[0] == 1);
    CHECK(d[1] == 2);
    CHECK(d[2] == 2);
    CHECK(d[3] == 2);
    CHECK(d[4] == 5);
}

void test_deque_insert_range() {
    int arr[] = {2, 3, 4};
    std::deque<int> d{1, 5};
    d.insert(d.begin() + 1, arr, arr + 3);
    CHECK(d.size() == 5);
    for (int i = 0; i < 5; ++i)
        CHECK(d[i] == i + 1);
}

void test_deque_insert_il() {
    std::deque<int> d{1, 5};
    d.insert(d.begin() + 1, {2, 3, 4});
    CHECK(d.size() == 5);
    for (int i = 0; i < 5; ++i)
        CHECK(d[i] == i + 1);
}

//===----------------------------------------------------------------------===//
// erase single / range
//===----------------------------------------------------------------------===//

void test_deque_erase_single() {
    std::deque<int> d{1, 2, 3, 4, 5};
    auto it = d.erase(d.begin() + 2);  // erase 3
    CHECK(d.size() == 4);
    CHECK(*it == 4);
    CHECK(d[0] == 1);
    CHECK(d[1] == 2);
    CHECK(d[2] == 4);
    CHECK(d[3] == 5);
}

void test_deque_erase_range() {
    std::deque<int> d{1, 2, 3, 4, 5};
    auto it = d.erase(d.begin() + 1, d.begin() + 4); // erase 2,3,4
    CHECK(d.size() == 2);
    CHECK(*it == 5);
    CHECK(d[0] == 1);
    CHECK(d[1] == 5);
}

//===----------------------------------------------------------------------===//
// swap
//===----------------------------------------------------------------------===//

void test_deque_swap() {
    std::deque<int> a{1, 2, 3};
    std::deque<int> b{4, 5, 6, 7};
    a.swap(b);
    CHECK(a.size() == 4 && b.size() == 3);
    CHECK(a[0] == 4);
    CHECK(b[0] == 1);
    std::swap(a, b);
    CHECK(a.size() == 3 && b.size() == 4);
}

//===----------------------------------------------------------------------===//
// Comparison operators
//===----------------------------------------------------------------------===//

void test_deque_compare() {
    std::deque<int> a{1, 2, 3};
    std::deque<int> b{1, 2, 3};
    std::deque<int> c{1, 2, 4};

    CHECK(a == b);
    CHECK(!(a == c));
    CHECK((a <=> b) == std::strong_ordering::equal);
    CHECK((a <=> c) == std::strong_ordering::less);
    CHECK((c <=> a) == std::strong_ordering::greater);
}

//===----------------------------------------------------------------------===//
// erase / erase_if (C++20)
//===----------------------------------------------------------------------===//

void test_deque_erase_value() {
    std::deque<int> d{1, 2, 3, 2, 4, 2};
    auto n = std::erase(d, 2);
    CHECK(n == 3);
    CHECK(d.size() == 3);
    CHECK(d[0] == 1);
    CHECK(d[1] == 3);
    CHECK(d[2] == 4);
}

void test_deque_erase_if() {
    std::deque<int> d{1, 2, 3, 4, 5, 6};
    auto n = std::erase_if(d, [](int x){ return x % 2 == 0; });
    CHECK(n == 3);
    CHECK(d.size() == 3);
    CHECK(d[0] == 1);
    CHECK(d[1] == 3);
    CHECK(d[2] == 5);
}

//===----------------------------------------------------------------------===//
// Large stress test (exercises multiple blocks)
//===----------------------------------------------------------------------===//

void test_deque_stress() {
    std::deque<int> d;
    const int N = 2000;
    // Push alternately front/back
    for (int i = 0; i < N; ++i) {
        if (i % 2 == 0) d.push_back(i);
        else             d.push_front(i);
    }
    CHECK(d.size() == static_cast<std::size_t>(N));

    // Pop half from front, half from back
    for (int i = 0; i < N / 4; ++i) d.pop_front();
    for (int i = 0; i < N / 4; ++i) d.pop_back();
    CHECK(d.size() == static_cast<std::size_t>(N / 2));
}

//===----------------------------------------------------------------------===//
// Deduction guides
//===----------------------------------------------------------------------===//

void test_deque_large_insert_front() {
    // Exercise add_front_capacity(n) with large n
    std::deque<int> d;
    for (int i = 0; i < 200; ++i)
        d.push_back(i + 200);
    // Insert 200 elements at the front position
    std::deque<int> src;
    for (int i = 0; i < 200; ++i)
        src.push_back(i);
    d.insert(d.begin(), src.begin(), src.end());
    CHECK(d.size() == 400);
    for (int i = 0; i < 400; ++i)
        CHECK(d[i] == i);
}

void test_deque_large_insert_back() {
    // Exercise add_back_capacity(n) with large n
    std::deque<int> d;
    for (int i = 0; i < 200; ++i)
        d.push_back(i);
    std::deque<int> src;
    for (int i = 0; i < 200; ++i)
        src.push_back(i + 200);
    d.insert(d.end(), src.begin(), src.end());
    CHECK(d.size() == 400);
    for (int i = 0; i < 400; ++i)
        CHECK(d[i] == i);
}

void test_deque_deduction() {
    int arr[] = {1, 2, 3};
    std::deque d(arr, arr + 3);
    static_assert(std::is_same_v<decltype(d), std::deque<int>>);
    CHECK(d.size() == 3);
}

//===----------------------------------------------------------------------===//
// get_allocator
//===----------------------------------------------------------------------===//

void test_deque_get_allocator() {
    std::deque<int> d;
    auto a = d.get_allocator();
    static_assert(std::is_same_v<decltype(a), std::allocator<int>>);
}

//===----------------------------------------------------------------------===//
// max_size
//===----------------------------------------------------------------------===//

void test_deque_max_size() {
    std::deque<int> d;
    CHECK(d.max_size() > 0);
}

//===----------------------------------------------------------------------===//
// Reverse iterator over larger deque
//===----------------------------------------------------------------------===//

void test_deque_reverse_iter() {
    std::deque<int> d;
    for (int i = 0; i < 50; ++i) d.push_back(i);
    int expected = 49;
    for (auto it = d.rbegin(); it != d.rend(); ++it, --expected)
        CHECK(*it == expected);
    CHECK(expected == -1);
}
