// test/functional.cpp — tests for <functional>
// Each test function is void test_functional_<name>().
// Uses CHECK (runtime) and static_assert (compile-time).
// No main() — auto-generated by tools/gen_main.sh.
// No progress printing.
#include <functional>
#include "test.h"

//===----------------------------------------------------------------------===//
// reference_wrapper tests
//===----------------------------------------------------------------------===//

void test_functional_reference_wrapper() {
    int x = 42;
    std::reference_wrapper<int> rw(x);
    CHECK(rw.get() == 42);
    x = 99;
    CHECK(rw.get() == 99);

    // operator type&
    int& r = rw;
    CHECK(r == 99);

    // ref / cref
    auto rw2 = std::ref(x);
    CHECK(rw2.get() == 99);

    const int cx = 7;
    auto crw = std::cref(cx);
    CHECK(crw.get() == 7);

    // ref(reference_wrapper) returns same wrapper
    auto rw3 = std::ref(rw2);
    CHECK(rw3.get() == 99);

    // cref(reference_wrapper<T>) returns reference_wrapper<const T>
    auto crw2 = std::cref(rw2);
    CHECK(crw2.get() == 99);
}

void test_functional_reference_wrapper_invoke() {
    // Invoke callable through reference_wrapper
    auto add = [](int a, int b) { return a + b; };
    auto rw_add = std::ref(add);
    CHECK(rw_add(3, 4) == 7);
    CHECK(rw_add(10, 20) == 30);
}

//===----------------------------------------------------------------------===//
// invoke / invoke_r tests
//===----------------------------------------------------------------------===//

static int add_fn(int a, int b) { return a + b; }

void test_functional_invoke() {
    // Free function
    CHECK(std::invoke(add_fn, 3, 4) == 7);

    // Lambda
    auto sq = [](int x) { return x * x; };
    CHECK(std::invoke(sq, 5) == 25);

    // Member function
    struct Foo { int val; int get() const { return val; } };
    Foo foo{42};
    CHECK(std::invoke(&Foo::get, foo) == 42);
    CHECK(std::invoke(&Foo::get, &foo) == 42);

    // Member object
    CHECK(std::invoke(&Foo::val, foo) == 42);

    // reference_wrapper
    auto rw = std::ref(foo);
    CHECK(std::invoke(&Foo::get, rw) == 42);
    CHECK(std::invoke(&Foo::val, rw) == 42);

    // invoke_r
    double d = std::invoke_r<double>(add_fn, 1, 2);
    CHECK(d == 3.0);

    // invoke_r void
    bool called = false;
    std::invoke_r<void>([&]{ called = true; });
    CHECK(called);
}

void test_functional_invoke_traits() {
    static_assert(std::is_invocable_v<decltype(add_fn), int, int>);
    static_assert(!std::is_invocable_v<decltype(add_fn), int>);
    static_assert(std::is_invocable_r_v<int, decltype(add_fn), int, int>);
    static_assert(std::is_invocable_r_v<double, decltype(add_fn), int, int>);
}

//===----------------------------------------------------------------------===//
// mem_fn tests
//===----------------------------------------------------------------------===//

void test_functional_mem_fn() {
    struct Bar {
        int x;
        int get() const { return x; }
        int add(int a) const { return x + a; }
    };
    Bar b{10};

    auto gfn = std::mem_fn(&Bar::get);
    CHECK(gfn(b) == 10);
    CHECK(gfn(&b) == 10);

    auto afn = std::mem_fn(&Bar::add);
    CHECK(afn(b, 5) == 15);

    // member object pointer
    auto xfn = std::mem_fn(&Bar::x);
    CHECK(xfn(b) == 10);
}

//===----------------------------------------------------------------------===//
// Arithmetic functor tests
//===----------------------------------------------------------------------===//

void test_functional_arithmetic() {
    static_assert(std::plus<int>{}(1, 2) == 3);
    static_assert(std::minus<int>{}(5, 2) == 3);
    static_assert(std::multiplies<int>{}(3, 4) == 12);
    static_assert(std::divides<int>{}(10, 2) == 5);
    static_assert(std::modulus<int>{}(7, 3) == 1);
    static_assert(std::negate<int>{}(5) == -5);

    // transparent void specializations
    static_assert(std::plus<>{}(1, 2) == 3);
    static_assert(std::minus<>{}(5, 2) == 3);
    static_assert(std::multiplies<>{}(3, 4) == 12);
    static_assert(std::divides<>{}(10, 2) == 5);
    static_assert(std::modulus<>{}(7, 3) == 1);
    static_assert(std::negate<>{}(5) == -5);

    // is_transparent exists
    static_assert(std::is_void_v<std::plus<>::is_transparent>);
}

//===----------------------------------------------------------------------===//
// Comparison functor tests
//===----------------------------------------------------------------------===//

void test_functional_comparison() {
    static_assert(std::equal_to<int>{}(1, 1));
    static_assert(!std::equal_to<int>{}(1, 2));
    static_assert(std::not_equal_to<int>{}(1, 2));
    static_assert(std::less<int>{}(1, 2));
    static_assert(!std::less<int>{}(2, 1));
    static_assert(std::greater<int>{}(2, 1));
    static_assert(std::less_equal<int>{}(1, 1));
    static_assert(std::less_equal<int>{}(1, 2));
    static_assert(std::greater_equal<int>{}(1, 1));
    static_assert(std::greater_equal<int>{}(2, 1));

    // transparent
    static_assert(std::equal_to<>{}(1, 1));
    static_assert(std::less<>{}(1, 2));
    static_assert(std::greater<>{}(2, 1));
}

//===----------------------------------------------------------------------===//
// Logical functor tests
//===----------------------------------------------------------------------===//

void test_functional_logical() {
    static_assert(std::logical_and<bool>{}(true, true));
    static_assert(!std::logical_and<bool>{}(true, false));
    static_assert(std::logical_or<bool>{}(false, true));
    static_assert(!std::logical_or<bool>{}(false, false));
    static_assert(std::logical_not<bool>{}(false));
    static_assert(!std::logical_not<bool>{}(true));

    // transparent
    static_assert(std::logical_and<>{}(true, true));
    static_assert(std::logical_or<>{}(false, true));
    static_assert(std::logical_not<>{}(false));
}

//===----------------------------------------------------------------------===//
// Bitwise functor tests
//===----------------------------------------------------------------------===//

void test_functional_bitwise() {
    static_assert(std::bit_and<int>{}(0b1010, 0b1100) == 0b1000);
    static_assert(std::bit_or<int>{}(0b1010, 0b1100) == 0b1110);
    static_assert(std::bit_xor<int>{}(0b1010, 0b1100) == 0b0110);
    static_assert(std::bit_not<unsigned>{}(0u) == ~0u);

    // transparent
    static_assert(std::bit_and<>{}(0b1010, 0b1100) == 0b1000);
    static_assert(std::bit_or<>{}(0b1010, 0b1100) == 0b1110);
    static_assert(std::bit_xor<>{}(0b1010, 0b1100) == 0b0110);
}

//===----------------------------------------------------------------------===//
// hash tests
//===----------------------------------------------------------------------===//

void test_functional_hash_basic() {
    // int
    std::hash<int> hi;
    CHECK(hi(0) == 0);
    CHECK(hi(1) == 1);
    CHECK(hi(42) == 42);

    // bool
    std::hash<bool> hb;
    CHECK(hb(false) == 0);
    CHECK(hb(true) == 1);

    // nullptr_t
    std::hash<std::nullptr_t> hn;
    CHECK(hn(nullptr) == 662607004ull);

    // pointer
    int x = 5;
    std::hash<int*> hp;
    size_t h = hp(&x);
    (void)h; // just ensure it compiles and runs

    // float — -0.0 and 0.0 same hash
    std::hash<float> hf;
    CHECK(hf(0.0f) == hf(-0.0f));
    CHECK(hf(0.0f) == 0);

    // double
    std::hash<double> hd;
    CHECK(hd(0.0) == hd(-0.0));
}

void test_functional_hash_enum() {
    enum class Color { Red = 1, Green = 2 };
    std::hash<Color> hc;
    // enum hash should equal hash of underlying type
    std::hash<int> hi;
    CHECK(hc(Color::Red) == hi(1));
    CHECK(hc(Color::Green) == hi(2));
}

void test_functional_hash_consistency() {
    // Same value hashes consistently
    std::hash<long> hl;
    long v = 12345L;
    CHECK(hl(v) == hl(v));

    std::hash<unsigned long long> hull;
    unsigned long long uv = 999999999999ULL;
    CHECK(hull(uv) == hull(uv));
}

//===----------------------------------------------------------------------===//
// not_fn tests
//===----------------------------------------------------------------------===//

void test_functional_not_fn() {
    auto is_positive = [](int x) { return x > 0; };
    auto is_not_positive = std::not_fn(is_positive);
    CHECK(!is_not_positive(5));
    CHECK(is_not_positive(-1));
    CHECK(is_not_positive(0));
}

//===----------------------------------------------------------------------===//
// bind_front tests
//===----------------------------------------------------------------------===//

void test_functional_bind_front() {
    auto add = [](int a, int b) { return a + b; };
    auto add5 = std::bind_front(add, 5);
    CHECK(add5(3) == 8);
    CHECK(add5(10) == 15);

    // with free function
    auto add3 = std::bind_front(add_fn, 3);
    CHECK(add3(7) == 10);
}

//===----------------------------------------------------------------------===//
// bind_back tests
//===----------------------------------------------------------------------===//

void test_functional_bind_back() {
    auto sub = [](int a, int b) { return a - b; };
    auto sub3 = std::bind_back(sub, 3);
    CHECK(sub3(10) == 7);
    CHECK(sub3(5) == 2);
}

//===----------------------------------------------------------------------===//
// bind + placeholders tests
//===----------------------------------------------------------------------===//

void test_functional_bind() {
    using namespace std::placeholders;

    auto add = [](int a, int b) { return a + b; };
    auto add5 = std::bind(add, 5, _1);
    CHECK(add5(3) == 8);

    // reversed args
    auto sub = [](int a, int b) { return a - b; };
    auto rsub = std::bind(sub, _2, _1);
    CHECK(rsub(3, 10) == 7);  // sub(10, 3)

    // bind with member function
    struct Baz { int val; int get() const { return val; } };
    Baz bz{42};
    auto get_bz = std::bind(&Baz::get, std::ref(bz));
    CHECK(get_bz() == 42);

    // is_bind_expression
    auto bound = std::bind(add, 1, 2);
    static_assert(std::is_bind_expression_v<decltype(bound)>);
    static_assert(!std::is_bind_expression_v<int>);

    // is_placeholder
    static_assert(std::is_placeholder_v<decltype(_1)> == 1);
    static_assert(std::is_placeholder_v<decltype(_2)> == 2);
    static_assert(std::is_placeholder_v<int> == 0);
}

void test_functional_bind_r() {
    using namespace std::placeholders;
    auto add = [](int a, int b) { return a + b; };
    auto bound = std::bind<double>(add, _1, _2);
    double r = bound(3, 4);
    CHECK(r == 7.0);
}

//===----------------------------------------------------------------------===//
// function<R(Args...)> tests
//===----------------------------------------------------------------------===//

void test_functional_function_basic() {
    // Construct from lambda
    std::function<int(int, int)> f = [](int a, int b) { return a + b; };
    CHECK(static_cast<bool>(f));
    CHECK(f(3, 4) == 7);

    // Construct from free function
    std::function<int(int, int)> f2 = add_fn;
    CHECK(f2(1, 2) == 3);

    // Default-constructed is empty
    std::function<int()> empty;
    CHECK(!empty);

    // nullptr construction
    std::function<int()> nullf(nullptr);
    CHECK(!nullf);
}

void test_functional_function_copy_move() {
    std::function<int(int)> f1 = [](int x) { return x * 2; };
    auto f2 = f1;  // copy
    CHECK(f2(5) == 10);
    CHECK(f1(5) == 10);  // original still valid

    auto f3 = std::move(f1);  // move
    CHECK(f3(5) == 10);
    // f1 may be empty after move (implementation-defined, but we don't CHECK it)

    // assign
    std::function<int(int)> f4;
    f4 = f2;
    CHECK(f4(5) == 10);

    // assign nullptr
    f4 = nullptr;
    CHECK(!f4);
}

void test_functional_function_swap() {
    std::function<int(int)> f1 = [](int x) { return x + 1; };
    std::function<int(int)> f2 = [](int x) { return x + 2; };
    f1.swap(f2);
    CHECK(f1(0) == 2);
    CHECK(f2(0) == 1);
}

void test_functional_function_capturing_lambda() {
    int captured = 100;
    std::function<int()> f = [&captured]{ return captured; };
    CHECK(f() == 100);
    captured = 200;
    CHECK(f() == 200);
}

void test_functional_function_member_fn() {
    struct Counter {
        int n = 0;
        void inc() { ++n; }
        int get() const { return n; }
    };
    Counter c;
    std::function<void()> inc = [&c]{ c.inc(); };
    inc(); inc(); inc();
    CHECK(c.get() == 3);
}

void test_functional_function_operator_bool() {
    std::function<void()> f;
    CHECK(!f);
    f = []{};
    CHECK(f);
    f = nullptr;
    CHECK(!f);
}
