// test/future.cpp — tests for <future>
// Each test_* function is a no-arg free function using CHECK / static_assert.
// main() is auto-generated by tools/gen_main.sh.
//
// Note: std::string is not used here because the transitive include chain
// future→system_error→string→algorithm has a pre-existing namespace-nesting
// issue in include/optional. Tests use int / structs instead.
#include <future>
#include <atomic>
#include "test.h"

// A non-trivial movable value type used instead of std::string.
struct Val {
    int v;
    explicit Val(int x) : v(x) {}
    Val(const Val&) = default;
    Val& operator=(const Val&) = default;
    bool operator==(const Val& o) const { return v == o.v; }
};

// ============================================================
// test_future_promise_value_roundtrip
// ============================================================
void test_future_promise_value_roundtrip() {
    std::promise<int> p;
    std::future<int>  f = p.get_future();
    p.set_value(42);
    CHECK(f.get() == 42);
}

// ============================================================
// test_future_promise_non_trivial
// ============================================================
void test_future_promise_non_trivial() {
    // Tests promise/future with a non-trivial value type (Val struct).
    std::promise<Val> p;
    auto f = p.get_future();
    p.set_value(Val(99));
    CHECK(f.get() == Val(99));
}

// ============================================================
// test_future_promise_void
// ============================================================
void test_future_promise_void() {
    std::promise<void> p;
    auto f = p.get_future();
    p.set_value();
    f.get();  // should not trap
    CHECK(true);
}

// ============================================================
// test_future_valid
// ============================================================
void test_future_valid() {
    std::promise<int> p;
    std::future<int>  f = p.get_future();
    CHECK(f.valid());
    p.set_value(1);
    (void)f.get();
    CHECK(!f.valid());
}

// ============================================================
// test_future_async_launch_async
// ============================================================
void test_future_async_launch_async() {
    auto f = std::async(std::launch::async, []{ return 100; });
    CHECK(f.get() == 100);
}

// ============================================================
// test_future_async_launch_deferred
// ============================================================
void test_future_async_launch_deferred() {
    std::atomic<int> executed{0};
    auto f = std::async(std::launch::deferred, [&]{
        executed.fetch_add(1, std::memory_order_relaxed);
        return 200;
    });
    // The callable must NOT have run yet.
    CHECK(executed.load() == 0);
    int v = f.get();
    CHECK(v == 200);
    CHECK(executed.load() == 1);
}

// ============================================================
// test_future_packaged_task
// ============================================================
void test_future_packaged_task() {
    std::packaged_task<int(int, int)> task([](int a, int b){ return a + b; });
    auto f = task.get_future();
    task(3, 4);
    CHECK(f.get() == 7);
}

// ============================================================
// test_future_packaged_task_void
// ============================================================
void test_future_packaged_task_void() {
    std::atomic<int> counter{0};
    std::packaged_task<void()> task([&]{
        counter.fetch_add(1, std::memory_order_relaxed);
    });
    auto f = task.get_future();
    task();
    f.get();
    CHECK(counter.load() == 1);
}

// ============================================================
// test_future_async_no_policy
// ============================================================
void test_future_async_no_policy() {
    // async() without explicit policy defaults to async|deferred.
    auto f = std::async([]{ return 55; });
    CHECK(f.get() == 55);
}

// ============================================================
// test_future_shared_future
// ============================================================
void test_future_shared_future() {
    std::promise<int> p;
    auto sf = p.get_future().share();
    // Can copy a shared_future.
    std::shared_future<int> sf2 = sf;
    p.set_value(7);
    CHECK(sf.get() == 7);
    CHECK(sf2.get() == 7);
}
