// test/ios.cpp — tests for <streambuf>, <ios>, and <locale> (minimal).
// Each test function crashes on failure via CHECK(); silent on success.
// No main() — auto-generated by tools/gen_main.sh.

#include <streambuf>
#include <ios>
#include <locale>
#include "test.h"

//===----------------------------------------------------------------------===//
// Custom streambuf: fixed-size array backing store.
// Supports both write (sputc/sputn) and read (sgetc/sbumpc).
//===----------------------------------------------------------------------===//
struct __attribute__((visibility("hidden"))) FixedBuf : std::streambuf {
    static constexpr int cap = 64;
    char data[cap] = {};
    int  write_pos = 0; // how many bytes have been put

    FixedBuf() {
        // Initially no get area; set up put area over the whole buffer.
        setp(data, data + cap);
        // No get area yet; will be set up after writes are committed.
    }

    // After writing, call this to enable reading what was written.
    void commit() {
        write_pos = static_cast<int>(pptr() - pbase());
        setg(data, data, data + write_pos);
    }

    // overflow: called when put area is full — we're fixed-size, signal error.
    int_type overflow(int_type c) override {
        if (c == traits_type::eof()) return traits_type::eof();
        // Buffer full
        return traits_type::eof();
    }

    // underflow: called when get area is exhausted.
    int_type underflow() override {
        // If there is data beyond current gptr, reset window.
        // For simplicity: when get area is exhausted we are at EOF.
        return traits_type::eof();
    }
};

//===----------------------------------------------------------------------===//
// test_streambuf_sputc_sgetc
//   Exercises sputc and sgetc on a custom FixedBuf.
//===----------------------------------------------------------------------===//
void test_streambuf_sputc_sgetc() {
    FixedBuf buf;

    // Write characters
    CHECK(buf.sputc('H') == 'H');
    CHECK(buf.sputc('i') == 'i');
    CHECK(buf.sputc('!') == '!');

    // Commit writes so we can read them back.
    buf.commit();

    // Read them back
    CHECK(buf.sgetc()  == 'H');
    CHECK(buf.sbumpc() == 'H');
    CHECK(buf.sgetc()  == 'i');
    CHECK(buf.sbumpc() == 'i');
    CHECK(buf.sgetc()  == '!');
    CHECK(buf.sbumpc() == '!');

    // Now at EOF
    CHECK(buf.sgetc()  == std::char_traits<char>::eof());
}

//===----------------------------------------------------------------------===//
// test_streambuf_sputn_sgetn
//   Exercises sputn / sgetn.
//===----------------------------------------------------------------------===//
void test_streambuf_sputn_sgetn() {
    FixedBuf buf;

    const char msg[] = "Hello";
    std::streamsize n = buf.sputn(msg, 5);
    CHECK(n == 5);

    buf.commit();

    char out[8] = {};
    std::streamsize got = buf.sgetn(out, 5);
    CHECK(got == 5);
    CHECK(out[0] == 'H');
    CHECK(out[4] == 'o');
}

//===----------------------------------------------------------------------===//
// test_streambuf_putback
//   Exercises sputbackc / sungetc.
//===----------------------------------------------------------------------===//
void test_streambuf_putback() {
    FixedBuf buf;
    buf.sputc('A');
    buf.sputc('B');
    buf.commit();

    CHECK(buf.sbumpc() == 'A'); // consume A, gptr now at B
    CHECK(buf.sgetc()  == 'B');
    // sungetc: step back to A
    auto r = buf.sungetc();
    CHECK(r != std::char_traits<char>::eof());
    CHECK(buf.sgetc() == 'A');
}

//===----------------------------------------------------------------------===//
// test_streambuf_in_avail
//===----------------------------------------------------------------------===//
void test_streambuf_in_avail() {
    FixedBuf buf;
    buf.sputc('X');
    buf.sputc('Y');
    buf.commit();

    CHECK(buf.in_avail() == 2);
    buf.sbumpc();
    CHECK(buf.in_avail() == 1);
    buf.sbumpc();
    CHECK(buf.in_avail() == 0);
}

//===----------------------------------------------------------------------===//
// test_ios_base_flags
//   Tests fmtflags set/unset/get, precision, width.
//===----------------------------------------------------------------------===//
void test_ios_base_flags() {
    FixedBuf buf;
    std::ios  stream(&buf);

    // Initially skipws|dec should be set by init()
    CHECK((stream.flags() & std::ios_base::skipws) != 0);
    CHECK((stream.flags() & std::ios_base::dec)    != 0);

    // setf single flag
    stream.setf(std::ios_base::boolalpha);
    CHECK((stream.flags() & std::ios_base::boolalpha) != 0);

    // unsetf
    stream.unsetf(std::ios_base::boolalpha);
    CHECK((stream.flags() & std::ios_base::boolalpha) == 0);

    // setf with mask (basefield)
    stream.setf(std::ios_base::hex, std::ios_base::basefield);
    CHECK((stream.flags() & std::ios_base::basefield) == std::ios_base::hex);

    // precision
    CHECK(stream.precision() == 6);
    auto old_prec = stream.precision(10);
    CHECK(old_prec == 6);
    CHECK(stream.precision() == 10);

    // width
    CHECK(stream.width() == 0);
    auto old_w = stream.width(8);
    CHECK(old_w == 0);
    CHECK(stream.width() == 8);
}

//===----------------------------------------------------------------------===//
// test_ios_base_state
//   Tests rdstate/clear/setstate/good/eof/fail/bad.
//   Exceptions mask is left at goodbit so clear() never traps.
//===----------------------------------------------------------------------===//
void test_ios_base_state() {
    FixedBuf buf;
    std::ios  stream(&buf);

    CHECK(stream.good());
    CHECK(!stream.eof());
    CHECK(!stream.fail());
    CHECK(!stream.bad());
    CHECK(static_cast<bool>(stream));
    CHECK(!(!stream));

    // setstate eofbit — eof() true, fail() false (only eofbit, not failbit/badbit)
    stream.setstate(std::ios_base::eofbit);
    CHECK(stream.eof());
    CHECK(!stream.fail()); // eofbit alone does NOT set fail(); fail() = (failbit|badbit)!=0
    CHECK(!stream.bad());
    CHECK(!stream.good()); // any bit set => not good

    // clear back to good
    stream.clear();
    CHECK(stream.good());

    // setstate failbit
    stream.setstate(std::ios_base::failbit);
    CHECK(stream.fail());
    CHECK(!stream.bad());
    CHECK(!stream.eof());

    stream.clear();
    CHECK(stream.good());

    // setstate badbit
    stream.setstate(std::ios_base::badbit);
    CHECK(stream.bad());
    CHECK(stream.fail()); // bad implies fail()
    stream.clear();
    CHECK(stream.good());
}

//===----------------------------------------------------------------------===//
// test_ios_base_xalloc_iword_pword
//===----------------------------------------------------------------------===//
void test_ios_base_xalloc_iword_pword() {
    FixedBuf buf;
    std::ios  stream(&buf);

    int idx = std::ios_base::xalloc();
    stream.iword(idx) = 42L;
    CHECK(stream.iword(idx) == 42L);

    int idx2 = std::ios_base::xalloc();
    void* ptr = &buf;
    stream.pword(idx2) = ptr;
    CHECK(stream.pword(idx2) == ptr);
}

//===----------------------------------------------------------------------===//
// test_ios_manipulators
//===----------------------------------------------------------------------===//
void test_ios_manipulators() {
    FixedBuf buf;
    std::ios  stream(&buf);

    std::hex(stream);
    CHECK((stream.flags() & std::ios_base::basefield) == std::ios_base::hex);

    std::dec(stream);
    CHECK((stream.flags() & std::ios_base::basefield) == std::ios_base::dec);

    std::oct(stream);
    CHECK((stream.flags() & std::ios_base::basefield) == std::ios_base::oct);

    std::dec(stream);

    std::left(stream);
    CHECK((stream.flags() & std::ios_base::adjustfield) == std::ios_base::left);

    std::right(stream);
    CHECK((stream.flags() & std::ios_base::adjustfield) == std::ios_base::right);

    std::fixed(stream);
    CHECK((stream.flags() & std::ios_base::floatfield) == std::ios_base::fixed);

    std::scientific(stream);
    CHECK((stream.flags() & std::ios_base::floatfield) == std::ios_base::scientific);

    std::defaultfloat(stream);
    CHECK((stream.flags() & std::ios_base::floatfield) == 0u);

    std::boolalpha(stream);
    CHECK((stream.flags() & std::ios_base::boolalpha) != 0);
    std::noboolalpha(stream);
    CHECK((stream.flags() & std::ios_base::boolalpha) == 0);
}

//===----------------------------------------------------------------------===//
// test_ios_fill_widen
//   Tests fill() and widen() / narrow() on basic_ios<char>.
//===----------------------------------------------------------------------===//
void test_ios_fill_widen() {
    FixedBuf buf;
    std::ios  stream(&buf);

    // Default fill is ' ' (space), obtained via widen(' ')
    CHECK(stream.fill() == ' ');

    // Change fill
    char old = stream.fill('*');
    CHECK(old == ' ');
    CHECK(stream.fill() == '*');

    // widen and narrow (char -> char via ctype<char> classic which is identity)
    CHECK(stream.widen('A') == 'A');
    CHECK(stream.narrow('Z', '?') == 'Z');
}

//===----------------------------------------------------------------------===//
// test_ios_rdbuf_null
//   A stream with null rdbuf should have badbit set; operations must not crash.
//===----------------------------------------------------------------------===//
void test_ios_rdbuf_null() {
    // basic_ios default ctor + init(nullptr) => badbit set
    // We test via a concrete derived class.
    struct __attribute__((visibility("hidden"))) NullStream : std::ios {
        NullStream() : std::ios(nullptr) {}
    };
    NullStream ns;
    CHECK(ns.bad());
    CHECK(ns.rdbuf() == nullptr);

    // clear() with null rdbuf should re-set badbit
    ns.clear(std::ios_base::goodbit); // requests goodbit, but rdbuf_ is null => badbit forced
    CHECK(ns.bad());
}

//===----------------------------------------------------------------------===//
// test_locale_ctype
//   Tests that use_facet<ctype<char>> is available and works.
//===----------------------------------------------------------------------===//
void test_locale_ctype() {
    const std::locale& loc = std::locale::classic();

    CHECK(std::has_facet<std::ctype<char>>(loc));

    const auto& ct = std::use_facet<std::ctype<char>>(loc);
    CHECK(ct.is(std::ctype_base::alpha, 'a'));
    CHECK(ct.is(std::ctype_base::digit, '7'));
    CHECK(!ct.is(std::ctype_base::digit, 'x'));
    CHECK(ct.toupper('a') == 'A');
    CHECK(ct.tolower('Z') == 'z');
    CHECK(ct.widen('B') == 'B');
    CHECK(ct.narrow('C', '?') == 'C');
}

//===----------------------------------------------------------------------===//
// test_locale_numpunct
//===----------------------------------------------------------------------===//
void test_locale_numpunct() {
    const std::locale& loc = std::locale::classic();
    CHECK(std::has_facet<std::numpunct<char>>(loc));

    const auto& np = std::use_facet<std::numpunct<char>>(loc);
    CHECK(np.decimal_point() == '.');
    CHECK(np.thousands_sep() == ',');
}
