// test/istream.cpp — tests for <istream> (basic_istream).
// Each test function crashes on failure via CHECK(); silent on success.
// No main() — auto-generated by tools/gen_main.sh.

#include <istream>
#include <iostream>
#include "test.h"

//===----------------------------------------------------------------------===//
// String-backed read-only streambuf.
//===----------------------------------------------------------------------===//
struct __attribute__((visibility("hidden"))) RdBuf : std::streambuf {
    RdBuf(const char* s, int n) {
        // const_cast: we only read from it
        char* p = const_cast<char*>(s);
        setg(p, p, p + n);
    }
    int_type underflow() override { return traits_type::eof(); }
};

//===----------------------------------------------------------------------===//
// test_istream_read_int
//===----------------------------------------------------------------------===//
void test_istream_read_int() {
    const char* s = "42 -7 0 100";
    RdBuf buf(s, 11);
    std::istream is(&buf);

    int a, b, c, d;
    is >> a >> b >> c >> d;
    CHECK(a == 42);
    CHECK(b == -7);
    CHECK(c == 0);
    CHECK(d == 100);
}

//===----------------------------------------------------------------------===//
// test_istream_read_long
//===----------------------------------------------------------------------===//
void test_istream_read_long() {
    const char* s = "1234567890 -9876543210";
    RdBuf buf(s, static_cast<int>(__builtin_strlen(s)));
    std::istream is(&buf);

    long long a, b;
    is >> a >> b;
    CHECK(a == 1234567890LL);
    CHECK(b == -9876543210LL);
}

//===----------------------------------------------------------------------===//
// test_istream_read_unsigned
//===----------------------------------------------------------------------===//
void test_istream_read_unsigned() {
    const char* s = "255 65535";
    RdBuf buf(s, 9);
    std::istream is(&buf);

    unsigned int a;
    unsigned long b;
    is >> a >> b;
    CHECK(a == 255u);
    CHECK(b == 65535ul);
}

//===----------------------------------------------------------------------===//
// test_istream_read_float
//===----------------------------------------------------------------------===//
void test_istream_read_float() {
    const char* s = "3.14 -2.5 1e3";
    RdBuf buf(s, static_cast<int>(__builtin_strlen(s)));
    std::istream is(&buf);

    double a, b, c;
    is >> a >> b >> c;
    // Use integer comparison trick: check approximate values
    CHECK(a > 3.13 && a < 3.15);
    CHECK(b < -2.4 && b > -2.6);
    CHECK(c > 999.9 && c < 1000.1);
}

//===----------------------------------------------------------------------===//
// test_istream_read_bool
//===----------------------------------------------------------------------===//
void test_istream_read_bool() {
    const char* s = "1 0";
    RdBuf buf(s, 3);
    std::istream is(&buf);

    bool a, b;
    is >> a >> b;
    CHECK(a == true);
    CHECK(b == false);
}

void test_istream_read_bool_alpha() {
    const char* s = "true false";
    RdBuf buf(s, static_cast<int>(__builtin_strlen(s)));
    std::istream is(&buf);
    is >> std::boolalpha;

    bool a, b;
    is >> a >> b;
    CHECK(a == true);
    CHECK(b == false);
}

//===----------------------------------------------------------------------===//
// test_istream_read_char
//===----------------------------------------------------------------------===//
void test_istream_read_char() {
    const char* s = "A B C";
    RdBuf buf(s, 5);
    std::istream is(&buf);

    char a, b, c;
    is >> a >> b >> c;
    CHECK(a == 'A');
    CHECK(b == 'B');
    CHECK(c == 'C');
}

//===----------------------------------------------------------------------===//
// test_istream_read_word
//===----------------------------------------------------------------------===//
void test_istream_read_word() {
    const char* s = "hello world";
    RdBuf buf(s, 11);
    std::istream is(&buf);

    char word1[16] = {}, word2[16] = {};
    is >> word1 >> word2;
    CHECK(__builtin_memcmp(word1, "hello", 5) == 0 && word1[5] == '\0');
    CHECK(__builtin_memcmp(word2, "world", 5) == 0 && word2[5] == '\0');
}

//===----------------------------------------------------------------------===//
// test_istream_getline
//===----------------------------------------------------------------------===//
void test_istream_getline() {
    const char* s = "line one\nline two\n";
    RdBuf buf(s, static_cast<int>(__builtin_strlen(s)));
    std::istream is(&buf);

    char line1[32] = {}, line2[32] = {};
    is.getline(line1, 32);
    is.getline(line2, 32);

    CHECK(__builtin_memcmp(line1, "line one", 8) == 0 && line1[8] == '\0');
    CHECK(__builtin_memcmp(line2, "line two", 8) == 0 && line2[8] == '\0');
}

//===----------------------------------------------------------------------===//
// test_istream_get
//===----------------------------------------------------------------------===//
void test_istream_get() {
    const char* s = "ABC";
    RdBuf buf(s, 3);
    std::istream is(&buf);

    char c;
    is.get(c);
    CHECK(c == 'A');
    CHECK(is.gcount() == 1);

    auto ic = is.get();
    CHECK(ic == 'B');
    CHECK(is.gcount() == 1);

    is.get(c);
    CHECK(c == 'C');

    // EOF
    is.get(c);
    CHECK(is.fail());
    CHECK(is.eof());
}

//===----------------------------------------------------------------------===//
// test_istream_ignore
//===----------------------------------------------------------------------===//
void test_istream_ignore() {
    const char* s = "XYZAB";
    RdBuf buf(s, 5);
    std::istream is(&buf);

    is.ignore(3);
    char c;
    is.get(c);
    CHECK(c == 'A');
}

//===----------------------------------------------------------------------===//
// test_istream_peek_unget
//===----------------------------------------------------------------------===//
void test_istream_peek_unget() {
    const char* s = "AB";
    RdBuf buf(s, 2);
    std::istream is(&buf);

    auto ic = is.peek();
    CHECK(ic == 'A');
    // peek doesn't consume
    ic = is.peek();
    CHECK(ic == 'A');

    char c;
    is.get(c); CHECK(c == 'A');
    is.unget();
    is.get(c); CHECK(c == 'A');
}

//===----------------------------------------------------------------------===//
// test_istream_read
//===----------------------------------------------------------------------===//
void test_istream_read() {
    const char* s = "Hello";
    RdBuf buf(s, 5);
    std::istream is(&buf);

    char out[6] = {};
    is.read(out, 5);
    CHECK(is.gcount() == 5);
    CHECK(__builtin_memcmp(out, "Hello", 5) == 0);
}

//===----------------------------------------------------------------------===//
// test_istream_ws_manipulator
//===----------------------------------------------------------------------===//
void test_istream_ws_manipulator() {
    const char* s = "   hello";
    RdBuf buf(s, static_cast<int>(__builtin_strlen(s)));
    std::istream is(&buf);

    is >> std::ws;
    char word[16] = {};
    is >> word;
    CHECK(__builtin_memcmp(word, "hello", 5) == 0);
}

//===----------------------------------------------------------------------===//
// test_istream_hex_input
//===----------------------------------------------------------------------===//
void test_istream_hex_input() {
    const char* s = "ff 10";
    RdBuf buf(s, 5);
    std::istream is(&buf);
    is >> std::hex;

    int a, b;
    is >> a >> b;
    CHECK(a == 0xFF);
    CHECK(b == 0x10);
    is >> std::dec;
}

//===----------------------------------------------------------------------===//
// test_istream_oct_input
//===----------------------------------------------------------------------===//
void test_istream_oct_input() {
    const char* s = "10 17";
    RdBuf buf(s, 5);
    std::istream is(&buf);
    is >> std::oct;

    int a, b;
    is >> a >> b;
    CHECK(a == 8);   // 010 octal
    CHECK(b == 15);  // 017 octal
    is >> std::dec;
}

//===----------------------------------------------------------------------===//
// test_istream_cin_compiles
// Verify &std::cin is non-null (don't actually read from it — no TTY).
//===----------------------------------------------------------------------===//
void test_istream_cin_compiles() {
    CHECK(&std::cin != nullptr);
}

//===----------------------------------------------------------------------===//
// test_istream_gcount
//===----------------------------------------------------------------------===//
void test_istream_gcount() {
    const char* s = "ABCDE";
    RdBuf buf(s, 5);
    std::istream is(&buf);

    char out[8] = {};
    is.read(out, 5);
    CHECK(is.gcount() == 5);
}

//===----------------------------------------------------------------------===//
// test_istream_get_delim
//===----------------------------------------------------------------------===//
void test_istream_get_delim() {
    const char* s = "hello:world";
    RdBuf buf(s, 11);
    std::istream is(&buf);

    char first[16] = {}, second[16] = {};
    is.getline(first, 16, ':');
    is.getline(second, 16, ':');

    CHECK(__builtin_memcmp(first, "hello", 5) == 0 && first[5] == '\0');
    CHECK(__builtin_memcmp(second, "world", 5) == 0 && second[5] == '\0');
}
