// test/memory.cpp — tests for <memory>
// Each test_ function is a no-arg free function that uses CHECK and static_assert.
// main() is auto-generated by tools/gen_main.sh.

#include <memory>
#include "test.h"

//===----------------------------------------------------------------------===//
// addressof / to_address (from <bits/pointer.h>, re-exported through <memory>)
//===----------------------------------------------------------------------===//

void test_memory_addressof() {
    int x = 42;
    CHECK(std::addressof(x) == &x);

    // addressof with overloaded operator&
    struct Bad {
        int* operator&() const { return nullptr; }
        int val;
    };
    Bad b{7};
    CHECK(std::addressof(b) != nullptr);
    CHECK(std::addressof(b)->val == 7);
}

void test_memory_to_address() {
    int x = 42;
    int* p = &x;
    CHECK(std::to_address(p) == p);

    // pointer_traits<T*>::to_address
    static_assert(std::is_same_v<decltype(std::to_address(p)), int*>);
}

//===----------------------------------------------------------------------===//
// pointer_traits
//===----------------------------------------------------------------------===//

void test_memory_pointer_traits() {
    using PT = std::pointer_traits<int*>;
    static_assert(std::is_same_v<PT::pointer, int*>);
    static_assert(std::is_same_v<PT::element_type, int>);
    static_assert(std::is_same_v<PT::difference_type, std::ptrdiff_t>);
    static_assert(std::is_same_v<PT::rebind<double>, double*>);

    int x = 5;
    CHECK(PT::pointer_to(x) == &x);
}

//===----------------------------------------------------------------------===//
// allocator_arg_t / allocator_arg
//===----------------------------------------------------------------------===//

void test_memory_allocator_arg() {
    static_assert(std::is_same_v<decltype(std::allocator_arg), const std::allocator_arg_t>);
    // Just ensure it exists and is a constexpr value
    constexpr std::allocator_arg_t a{};
    (void)a;
}

//===----------------------------------------------------------------------===//
// uses_allocator / uses_allocator_v
//===----------------------------------------------------------------------===//

void test_memory_uses_allocator() {
    struct WithAlloc {
        using allocator_type = std::allocator<int>;
    };
    struct WithoutAlloc {};
    // Type where allocator is not convertible from std::allocator<int>
    struct WithUnrelatedAlloc {
        struct MyAlloc {};
        using allocator_type = MyAlloc;
    };

    static_assert(std::uses_allocator_v<WithAlloc, std::allocator<int>>);
    static_assert(!std::uses_allocator_v<WithoutAlloc, std::allocator<int>>);
    // std::allocator<int> is not convertible to WithUnrelatedAlloc::MyAlloc
    static_assert(!std::uses_allocator_v<WithUnrelatedAlloc, std::allocator<int>>);
}

//===----------------------------------------------------------------------===//
// allocator<T>
//===----------------------------------------------------------------------===//

void test_memory_allocator() {
    std::allocator<int> a;
    int* p = a.allocate(4);
    CHECK(p != nullptr);
    p[0] = 1; p[1] = 2; p[2] = 3; p[3] = 4;
    CHECK(p[2] == 3);
    a.deallocate(p, 4);

    // Copy construction from different type
    std::allocator<double> b(a);
    double* q = b.allocate(2);
    CHECK(q != nullptr);
    b.deallocate(q, 2);

    // Equality
    std::allocator<int> c;
    CHECK(a == c);

    // allocate_at_least
    auto res = a.allocate_at_least(3);
    CHECK(res.ptr != nullptr);
    CHECK(res.count == 3);
    a.deallocate(res.ptr, res.count);
}

//===----------------------------------------------------------------------===//
// allocator_traits
//===----------------------------------------------------------------------===//

void test_memory_allocator_traits() {
    using Traits = std::allocator_traits<std::allocator<int>>;

    static_assert(std::is_same_v<Traits::value_type, int>);
    static_assert(std::is_same_v<Traits::pointer, int*>);
    static_assert(std::is_same_v<Traits::const_pointer, const int*>);
    static_assert(std::is_same_v<Traits::void_pointer, void*>);
    static_assert(std::is_same_v<Traits::const_void_pointer, const void*>);
    static_assert(std::is_same_v<Traits::difference_type, std::ptrdiff_t>);
    static_assert(std::is_same_v<Traits::size_type, std::size_t>);
    static_assert(std::is_same_v<Traits::propagate_on_container_copy_assignment, std::false_type>);
    static_assert(std::is_same_v<Traits::propagate_on_container_move_assignment, std::true_type>);
    static_assert(std::is_same_v<Traits::is_always_equal, std::true_type>);

    // rebind_alloc
    static_assert(std::is_same_v<Traits::rebind_alloc<double>, std::allocator<double>>);

    std::allocator<int> alloc;

    // allocate/deallocate
    int* p = Traits::allocate(alloc, 2);
    CHECK(p != nullptr);

    // construct/destroy via traits
    Traits::construct(alloc, p, 99);
    CHECK(*p == 99);
    Traits::destroy(alloc, p);

    Traits::deallocate(alloc, p, 2);

    // max_size
    std::size_t ms = Traits::max_size(alloc);
    CHECK(ms > 0);

    // select_on_container_copy_construction
    auto a2 = Traits::select_on_container_copy_construction(alloc);
    (void)a2;
}

//===----------------------------------------------------------------------===//
// allocation_result / allocate_at_least
//===----------------------------------------------------------------------===//

void test_memory_allocation_result() {
    std::allocator<int> a;
    auto res = std::allocate_at_least(a, 5);
    CHECK(res.ptr != nullptr);
    CHECK(res.count >= 5);
    a.deallocate(res.ptr, res.count);

    static_assert(std::is_same_v<decltype(res.ptr), int*>);
    static_assert(std::is_same_v<decltype(res.count), std::size_t>);
}

//===----------------------------------------------------------------------===//
// construct_at / destroy_at
//===----------------------------------------------------------------------===//

void test_memory_construct_at() {
    alignas(int) unsigned char buf[sizeof(int)];
    int* p = reinterpret_cast<int*>(buf);

    std::construct_at(p, 42);
    CHECK(*p == 42);
    std::destroy_at(p);

    // With multiple args
    struct S {
        int x, y;
        S(int a, int b) : x(a), y(b) {}
    };
    alignas(S) unsigned char sbuf[sizeof(S)];
    S* sp = reinterpret_cast<S*>(sbuf);
    std::construct_at(sp, 3, 7);
    CHECK(sp->x == 3);
    CHECK(sp->y == 7);
    std::destroy_at(sp);
}

namespace {
    int g_dtor_count = 0;
    struct Counted {
        ~Counted() { ++g_dtor_count; }
    };
}

void test_memory_destroy() {
    g_dtor_count = 0;

    alignas(Counted) unsigned char buf[5 * sizeof(Counted)];
    Counted* arr = reinterpret_cast<Counted*>(buf);
    for (int i = 0; i < 5; ++i)
        std::construct_at(arr + i);

    std::destroy(arr, arr + 5);
    CHECK(g_dtor_count == 5);

    // destroy_n
    g_dtor_count = 0;
    for (int i = 0; i < 3; ++i)
        std::construct_at(arr + i);
    auto end = std::destroy_n(arr, 3);
    CHECK(end == arr + 3);
    CHECK(g_dtor_count == 3);
}

//===----------------------------------------------------------------------===//
// default_delete
//===----------------------------------------------------------------------===//

void test_memory_default_delete() {
    // Single object
    int* p = new int(5);
    std::default_delete<int> d;
    d(p); // should delete p

    // Array
    int* arr = new int[3]{1,2,3};
    std::default_delete<int[]> da;
    da(arr);

    // Converting constructor
    struct Base { virtual ~Base() = default; };
    struct Derived : Base {};
    std::default_delete<Derived> dd;
    std::default_delete<Base> db(dd); // Derived* convertible to Base*
    (void)db;
}

//===----------------------------------------------------------------------===//
// unique_ptr<T,D>
//===----------------------------------------------------------------------===//

void test_memory_unique_ptr_basic() {
    // Default construct (null)
    std::unique_ptr<int> p;
    CHECK(!p);
    CHECK(p.get() == nullptr);

    // nullptr construct
    std::unique_ptr<int> q(nullptr);
    CHECK(!q);

    // Pointer construct
    std::unique_ptr<int> r(new int(42));
    CHECK(r);
    CHECK(*r == 42);

    // Release
    int* raw = r.release();
    CHECK(!r);
    CHECK(*raw == 42);
    delete raw;

    // Reset
    std::unique_ptr<int> s(new int(10));
    s.reset(new int(20));
    CHECK(*s == 20);
    s.reset();
    CHECK(!s);
}

void test_memory_unique_ptr_move() {
    std::unique_ptr<int> a(new int(1));
    std::unique_ptr<int> b = std::move(a);
    CHECK(!a);
    CHECK(*b == 1);

    std::unique_ptr<int> c;
    c = std::move(b);
    CHECK(!b);
    CHECK(*c == 1);

    // nullptr assignment
    c = nullptr;
    CHECK(!c);
}

void test_memory_unique_ptr_custom_deleter() {
    int deleted = 0;
    auto del = [&](int* p) { ++deleted; delete p; };
    {
        std::unique_ptr<int, decltype(del)> p(new int(5), del);
        CHECK(*p == 5);
    }
    CHECK(deleted == 1);
}

void test_memory_unique_ptr_swap() {
    std::unique_ptr<int> a(new int(1));
    std::unique_ptr<int> b(new int(2));
    std::swap(a, b);
    CHECK(*a == 2);
    CHECK(*b == 1);

    a.swap(b);
    CHECK(*a == 1);
    CHECK(*b == 2);
}

void test_memory_unique_ptr_comparisons() {
    std::unique_ptr<int> a(new int(1));
    std::unique_ptr<int> b(new int(2));
    std::unique_ptr<int> n;

    // vs nullptr
    CHECK(a != nullptr);
    CHECK(nullptr != a);
    CHECK(!n);
    CHECK(n == nullptr);

    // vs each other (based on pointer values, which vary — just check they compile)
    bool lt = (a < b) || (b < a) || (a == b);
    CHECK(lt); // one of them must be true
}

void test_memory_unique_ptr_arrow() {
    struct Foo { int x = 7; };
    std::unique_ptr<Foo> p(new Foo);
    CHECK(p->x == 7);
    CHECK((*p).x == 7);
}

//===----------------------------------------------------------------------===//
// unique_ptr<T[], D>  — array specialisation
//===----------------------------------------------------------------------===//

void test_memory_unique_ptr_array() {
    std::unique_ptr<int[]> a(new int[3]{10, 20, 30});
    CHECK(a[0] == 10);
    CHECK(a[1] == 20);
    CHECK(a[2] == 30);

    std::unique_ptr<int[]> b = std::move(a);
    CHECK(!a);
    CHECK(b[2] == 30);

    b.reset();
    CHECK(!b);
}

//===----------------------------------------------------------------------===//
// make_unique / make_unique_for_overwrite
//===----------------------------------------------------------------------===//

void test_memory_make_unique() {
    auto p = std::make_unique<int>(42);
    CHECK(*p == 42);

    auto arr = std::make_unique<int[]>(5);
    for (int i = 0; i < 5; ++i)
        arr[i] = i * 2;
    CHECK(arr[3] == 6);

    // make_unique_for_overwrite
    auto q = std::make_unique_for_overwrite<int>();
    // value is unspecified, just check it's non-null
    CHECK(q != nullptr);

    auto arr2 = std::make_unique_for_overwrite<int[]>(4);
    arr2[0] = 99;
    CHECK(arr2[0] == 99);
}

void test_memory_make_unique_struct() {
    struct Point { int x, y; };
    auto p = std::make_unique<Point>(Point{3, 4});
    CHECK(p->x == 3);
    CHECK(p->y == 4);
}

//===----------------------------------------------------------------------===//
// uninitialized algorithms
//===----------------------------------------------------------------------===//

void test_memory_uninitialized_value_construct() {
    alignas(int) unsigned char buf[5 * sizeof(int)];
    int* arr = reinterpret_cast<int*>(buf);

    std::uninitialized_value_construct(arr, arr + 5);
    for (int i = 0; i < 5; ++i)
        CHECK(arr[i] == 0);

    std::destroy(arr, arr + 5);
}

void test_memory_uninitialized_value_construct_n() {
    alignas(int) unsigned char buf[4 * sizeof(int)];
    int* arr = reinterpret_cast<int*>(buf);

    auto end = std::uninitialized_value_construct_n(arr, 4);
    CHECK(end == arr + 4);
    for (int i = 0; i < 4; ++i)
        CHECK(arr[i] == 0);

    std::destroy(arr, arr + 4);
}

void test_memory_uninitialized_default_construct() {
    // With trivial type — default-construct doesn't value-initialize,
    // just test that it doesn't crash
    alignas(int) unsigned char buf[3 * sizeof(int)];
    int* arr = reinterpret_cast<int*>(buf);
    std::uninitialized_default_construct(arr, arr + 3);
    std::destroy(arr, arr + 3);

    auto end = std::uninitialized_default_construct_n(arr, 3);
    CHECK(end == arr + 3);
    std::destroy(arr, arr + 3);
}

void test_memory_uninitialized_copy() {
    int src[5] = {1, 2, 3, 4, 5};
    alignas(int) unsigned char buf[5 * sizeof(int)];
    int* dst = reinterpret_cast<int*>(buf);

    auto end = std::uninitialized_copy(src, src + 5, dst);
    CHECK(end == dst + 5);
    for (int i = 0; i < 5; ++i)
        CHECK(dst[i] == src[i]);

    std::destroy(dst, dst + 5);
}

void test_memory_uninitialized_copy_n() {
    int src[4] = {10, 20, 30, 40};
    alignas(int) unsigned char buf[4 * sizeof(int)];
    int* dst = reinterpret_cast<int*>(buf);

    auto end = std::uninitialized_copy_n(src, 4, dst);
    CHECK(end == dst + 4);
    CHECK(dst[0] == 10);
    CHECK(dst[3] == 40);

    std::destroy(dst, dst + 4);
}

void test_memory_uninitialized_move() {
    struct MoveOnly {
        int val;
        MoveOnly(int v) : val(v) {}
        MoveOnly(MoveOnly&&) = default;
        MoveOnly(const MoveOnly&) = delete;
        MoveOnly& operator=(MoveOnly&&) = default;
        MoveOnly& operator=(const MoveOnly&) = delete;
    };

    alignas(MoveOnly) unsigned char src_buf[3 * sizeof(MoveOnly)];
    alignas(MoveOnly) unsigned char dst_buf[3 * sizeof(MoveOnly)];
    MoveOnly* src = reinterpret_cast<MoveOnly*>(src_buf);
    MoveOnly* dst = reinterpret_cast<MoveOnly*>(dst_buf);

    std::construct_at(src + 0, 1);
    std::construct_at(src + 1, 2);
    std::construct_at(src + 2, 3);

    auto end = std::uninitialized_move(src, src + 3, dst);
    CHECK(end == dst + 3);
    CHECK(dst[0].val == 1);
    CHECK(dst[1].val == 2);
    CHECK(dst[2].val == 3);

    std::destroy(dst, dst + 3);
    std::destroy(src, src + 3);
}

void test_memory_uninitialized_move_n() {
    alignas(int) unsigned char src_buf[3 * sizeof(int)];
    alignas(int) unsigned char dst_buf[3 * sizeof(int)];
    int* src = reinterpret_cast<int*>(src_buf);
    int* dst = reinterpret_cast<int*>(dst_buf);

    std::construct_at(src + 0, 10);
    std::construct_at(src + 1, 20);
    std::construct_at(src + 2, 30);

    auto [in_end, out_end] = std::uninitialized_move_n(src, 3, dst);
    CHECK(out_end == dst + 3);
    CHECK(dst[0] == 10);
    CHECK(dst[2] == 30);

    std::destroy(dst, dst + 3);
    std::destroy(src, src + 3);
}

void test_memory_uninitialized_fill() {
    alignas(int) unsigned char buf[4 * sizeof(int)];
    int* arr = reinterpret_cast<int*>(buf);

    std::uninitialized_fill(arr, arr + 4, 7);
    for (int i = 0; i < 4; ++i)
        CHECK(arr[i] == 7);

    std::destroy(arr, arr + 4);
}

void test_memory_uninitialized_fill_n() {
    alignas(int) unsigned char buf[3 * sizeof(int)];
    int* arr = reinterpret_cast<int*>(buf);

    auto end = std::uninitialized_fill_n(arr, 3, 99);
    CHECK(end == arr + 3);
    for (int i = 0; i < 3; ++i)
        CHECK(arr[i] == 99);

    std::destroy(arr, arr + 3);
}

//===----------------------------------------------------------------------===//
// align
//===----------------------------------------------------------------------===//

void test_memory_align() {
    alignas(64) unsigned char buf[128];
    void* p = buf + 1;  // misaligned by 1
    std::size_t space = 127;

    void* r = std::align(16, 32, p, space);
    // Result should be non-null and 16-byte aligned, with 32 bytes available
    CHECK(r != nullptr);
    CHECK((reinterpret_cast<std::uintptr_t>(r) % 16) == 0);
    CHECK(space >= 32);

    // Not enough space
    void* p2 = buf + 1;
    std::size_t space2 = 5;
    void* r2 = std::align(16, 32, p2, space2);
    CHECK(r2 == nullptr);
}

//===----------------------------------------------------------------------===//
// assume_aligned
//===----------------------------------------------------------------------===//

void test_memory_assume_aligned() {
    alignas(16) int x[4] = {1, 2, 3, 4};
    int* p = std::assume_aligned<16>(x);
    CHECK(p == x);
    CHECK(p[0] == 1);

    static_assert(noexcept(std::assume_aligned<16>(x)));
}

//===----------------------------------------------------------------------===//
// Static trait checks
//===----------------------------------------------------------------------===//

void test_memory_static_checks() {
    // allocator_traits rebind
    using A = std::allocator<int>;
    using T = std::allocator_traits<A>;
    static_assert(std::is_same_v<T::rebind_alloc<double>, std::allocator<double>>);

    // uses_allocator with std::allocator (allocator_type matches)
    struct WithIntAlloc { using allocator_type = std::allocator<int>; };
    static_assert(std::uses_allocator_v<WithIntAlloc, std::allocator<int>>);
    // Type without allocator_type: not uses_allocator
    struct NoAlloc { int x; };
    static_assert(!std::uses_allocator_v<NoAlloc, std::allocator<int>>);

    // unique_ptr type properties
    static_assert(std::is_same_v<std::unique_ptr<int>::element_type, int>);
    static_assert(std::is_same_v<std::unique_ptr<int>::deleter_type, std::default_delete<int>>);
    static_assert(std::is_same_v<std::unique_ptr<int>::pointer, int*>);

    static_assert(std::is_same_v<std::unique_ptr<int[]>::element_type, int>);
    static_assert(std::is_same_v<std::unique_ptr<int[]>::pointer, int*>);
}
