// test/numeric.cpp — tests for <numeric>
// Each test function is void test_numeric_<name>().
// Uses CHECK (runtime) and static_assert (compile-time).
// No main() — auto-generated by tools/gen_main.sh.
// No progress printing.
#include <numeric>
#include <iterator>
#include <functional>
#include "test.h"

//===----------------------------------------------------------------------===//
// accumulate
//===----------------------------------------------------------------------===//

void test_numeric_accumulate() {
    int arr[] = {1, 2, 3, 4, 5};

    // default (sum)
    int sum = std::accumulate(arr, arr + 5, 0);
    CHECK(sum == 15);

    // with binary op (product)
    int prod = std::accumulate(arr, arr + 5, 1, std::multiplies<int>{});
    CHECK(prod == 120);

    // empty range
    CHECK(std::accumulate(arr, arr, 42) == 42);

    // constexpr
    static_assert([]() {
        int a[] = {1, 2, 3};
        return std::accumulate(a, a + 3, 0) == 6;
    }());
}

//===----------------------------------------------------------------------===//
// reduce
//===----------------------------------------------------------------------===//

void test_numeric_reduce() {
    int arr[] = {1, 2, 3, 4, 5};

    // 3-arg: default init
    int s = std::reduce(arr, arr + 5);
    CHECK(s == 15);

    // 3-arg: explicit init
    int s2 = std::reduce(arr, arr + 5, 10);
    CHECK(s2 == 25);

    // 4-arg: with op
    int p = std::reduce(arr, arr + 5, 1, std::multiplies<int>{});
    CHECK(p == 120);

    // empty range
    CHECK(std::reduce(arr, arr) == 0); // value_type{} = 0
}

//===----------------------------------------------------------------------===//
// transform_reduce
//===----------------------------------------------------------------------===//

void test_numeric_transform_reduce() {
    int a[] = {1, 2, 3};
    int b[] = {4, 5, 6};

    // dot-product form (3-iterator)
    int dot = std::transform_reduce(a, a + 3, b, 0);
    CHECK(dot == 1*4 + 2*5 + 3*6); // 32

    // unary form
    int sq = std::transform_reduce(a, a + 3, 0, std::plus<int>{},
                                   [](int x){ return x * x; });
    CHECK(sq == 1 + 4 + 9); // 14

    // binary form with explicit ops
    int dp2 = std::transform_reduce(a, a + 3, b, 0,
                                    std::plus<int>{}, std::multiplies<int>{});
    CHECK(dp2 == 32);
}

//===----------------------------------------------------------------------===//
// inner_product
//===----------------------------------------------------------------------===//

void test_numeric_inner_product() {
    int a[] = {1, 2, 3};
    int b[] = {4, 5, 6};

    // default operators
    int ip = std::inner_product(a, a + 3, b, 0);
    CHECK(ip == 32);

    // custom ops: max(init, sum(xi*yi)) == same as inner_product with + and *
    // Use minus for op1 to test custom path
    int ip2 = std::inner_product(a, a + 3, b, 0,
                                 std::plus<int>{}, std::multiplies<int>{});
    CHECK(ip2 == 32);

    // constexpr
    static_assert([]() {
        int x[] = {1, 2};
        int y[] = {3, 4};
        return std::inner_product(x, x + 2, y, 0) == 11;
    }());
}

//===----------------------------------------------------------------------===//
// partial_sum
//===----------------------------------------------------------------------===//

void test_numeric_partial_sum() {
    int in[] = {1, 2, 3, 4, 5};
    int out[5] = {};

    std::partial_sum(in, in + 5, out);
    CHECK(out[0] == 1);
    CHECK(out[1] == 3);
    CHECK(out[2] == 6);
    CHECK(out[3] == 10);
    CHECK(out[4] == 15);

    // with custom op (running product)
    int out2[5] = {};
    std::partial_sum(in, in + 5, out2, std::multiplies<int>{});
    CHECK(out2[0] == 1);
    CHECK(out2[1] == 2);
    CHECK(out2[2] == 6);
    CHECK(out2[3] == 24);
    CHECK(out2[4] == 120);

    // empty range
    int* end = std::partial_sum(in, in, out);
    CHECK(end == out);
}

//===----------------------------------------------------------------------===//
// adjacent_difference
//===----------------------------------------------------------------------===//

void test_numeric_adjacent_difference() {
    int in[] = {1, 3, 6, 10, 15};
    int out[5] = {};

    std::adjacent_difference(in, in + 5, out);
    CHECK(out[0] == 1);
    CHECK(out[1] == 2);
    CHECK(out[2] == 3);
    CHECK(out[3] == 4);
    CHECK(out[4] == 5);

    // with custom op (max difference)
    int in2[] = {1, 3, 2, 5, 3};
    int out2[5] = {};
    std::adjacent_difference(in2, in2 + 5, out2,
                             [](int a, int b){ return a + b; });
    // out2[0] = 1
    // out2[1] = 3 + 1 = 4
    // out2[2] = 2 + 3 = 5
    // out2[3] = 5 + 2 = 7
    // out2[4] = 3 + 5 = 8
    CHECK(out2[0] == 1);
    CHECK(out2[1] == 4);
    CHECK(out2[2] == 5);
    CHECK(out2[3] == 7);
    CHECK(out2[4] == 8);
}

//===----------------------------------------------------------------------===//
// iota
//===----------------------------------------------------------------------===//

void test_numeric_iota() {
    int arr[5] = {};
    std::iota(arr, arr + 5, 1);
    CHECK(arr[0] == 1);
    CHECK(arr[1] == 2);
    CHECK(arr[2] == 3);
    CHECK(arr[3] == 4);
    CHECK(arr[4] == 5);

    // starts at 0
    std::iota(arr, arr + 5, 0);
    CHECK(arr[0] == 0);
    CHECK(arr[4] == 4);

    // constexpr
    static_assert([]() {
        int a[3] = {};
        std::iota(a, a + 3, 10);
        return a[0] == 10 && a[1] == 11 && a[2] == 12;
    }());
}

//===----------------------------------------------------------------------===//
// exclusive_scan
//===----------------------------------------------------------------------===//

void test_numeric_exclusive_scan() {
    int in[] = {1, 2, 3, 4, 5};
    int out[5] = {};

    // default op (plus)
    std::exclusive_scan(in, in + 5, out, 0);
    CHECK(out[0] == 0);
    CHECK(out[1] == 1);
    CHECK(out[2] == 3);
    CHECK(out[3] == 6);
    CHECK(out[4] == 10);

    // with init=1 and plus
    std::exclusive_scan(in, in + 5, out, 1, std::plus<int>{});
    CHECK(out[0] == 1);
    CHECK(out[1] == 2);
    CHECK(out[2] == 4);
    CHECK(out[3] == 7);
    CHECK(out[4] == 11);

    // empty range
    int* end = std::exclusive_scan(in, in, out, 0);
    CHECK(end == out);
}

//===----------------------------------------------------------------------===//
// inclusive_scan
//===----------------------------------------------------------------------===//

void test_numeric_inclusive_scan() {
    int in[] = {1, 2, 3, 4, 5};
    int out[5] = {};

    // default op
    std::inclusive_scan(in, in + 5, out);
    CHECK(out[0] == 1);
    CHECK(out[1] == 3);
    CHECK(out[2] == 6);
    CHECK(out[3] == 10);
    CHECK(out[4] == 15);

    // with binary op
    std::inclusive_scan(in, in + 5, out, std::plus<int>{});
    CHECK(out[0] == 1);
    CHECK(out[4] == 15);

    // with init
    std::inclusive_scan(in, in + 5, out, std::plus<int>{}, 10);
    CHECK(out[0] == 11);
    CHECK(out[1] == 13);
    CHECK(out[4] == 25);

    // empty range
    int* end = std::inclusive_scan(in, in, out);
    CHECK(end == out);
}

//===----------------------------------------------------------------------===//
// transform_exclusive_scan
//===----------------------------------------------------------------------===//

void test_numeric_transform_exclusive_scan() {
    int in[] = {1, 2, 3, 4};
    int out[4] = {};

    // square each element, then exclusive sum
    std::transform_exclusive_scan(in, in + 4, out, 0, std::plus<int>{},
                                  [](int x){ return x * x; });
    // excl prefix of [1, 4, 9, 16] with init=0:
    // out[0]=0, out[1]=1, out[2]=5, out[3]=14
    CHECK(out[0] == 0);
    CHECK(out[1] == 1);
    CHECK(out[2] == 5);
    CHECK(out[3] == 14);

    // empty range
    int* end = std::transform_exclusive_scan(in, in, out, 0, std::plus<int>{},
                                             [](int x){ return x; });
    CHECK(end == out);
}

//===----------------------------------------------------------------------===//
// transform_inclusive_scan
//===----------------------------------------------------------------------===//

void test_numeric_transform_inclusive_scan() {
    int in[] = {1, 2, 3, 4};
    int out[4] = {};

    // square each element, then inclusive sum
    std::transform_inclusive_scan(in, in + 4, out, std::plus<int>{},
                                  [](int x){ return x * x; });
    // incl prefix of [1, 4, 9, 16]:
    // out[0]=1, out[1]=5, out[2]=14, out[3]=30
    CHECK(out[0] == 1);
    CHECK(out[1] == 5);
    CHECK(out[2] == 14);
    CHECK(out[3] == 30);

    // with init=10
    std::transform_inclusive_scan(in, in + 4, out, std::plus<int>{},
                                  [](int x){ return x * x; }, 10);
    CHECK(out[0] == 11);
    CHECK(out[1] == 15);
    CHECK(out[2] == 24);
    CHECK(out[3] == 40);

    // empty range
    int* end = std::transform_inclusive_scan(in, in, out, std::plus<int>{},
                                             [](int x){ return x; });
    CHECK(end == out);
}

//===----------------------------------------------------------------------===//
// gcd
//===----------------------------------------------------------------------===//

void test_numeric_gcd() {
    static_assert(std::gcd(12, 8)  == 4);
    static_assert(std::gcd(7, 3)   == 1);
    static_assert(std::gcd(0, 5)   == 5);
    static_assert(std::gcd(5, 0)   == 5);
    static_assert(std::gcd(0, 0)   == 0);
    static_assert(std::gcd(100, 75) == 25);

    // Negative inputs (signed)
    CHECK(std::gcd(-12, 8)   == 4);
    CHECK(std::gcd(12, -8)   == 4);
    CHECK(std::gcd(-12, -8)  == 4);

    // Mixed types: int and long
    static_assert(std::gcd(4, 6L) == 2);
    static_assert(std::gcd(6L, 4) == 2);

    // gcd is commutative
    static_assert(std::gcd(48, 18) == std::gcd(18, 48));
}

//===----------------------------------------------------------------------===//
// lcm
//===----------------------------------------------------------------------===//

void test_numeric_lcm() {
    static_assert(std::lcm(4, 6)   == 12);
    static_assert(std::lcm(3, 7)   == 21);
    static_assert(std::lcm(0, 5)   == 0);
    static_assert(std::lcm(5, 0)   == 0);
    static_assert(std::lcm(0, 0)   == 0);
    static_assert(std::lcm(12, 18) == 36);

    // Negative inputs
    CHECK(std::lcm(-4, 6)  == 12);
    CHECK(std::lcm(4, -6)  == 12);
    CHECK(std::lcm(-4, -6) == 12);

    // Mixed types
    static_assert(std::lcm(4, 6L) == 12);
}

//===----------------------------------------------------------------------===//
// midpoint
//===----------------------------------------------------------------------===//

void test_numeric_midpoint_integer() {
    static_assert(std::midpoint(0, 4)   == 2);
    static_assert(std::midpoint(1, 5)   == 3);
    static_assert(std::midpoint(0, 3)   == 1);   // rounds toward a
    static_assert(std::midpoint(3, 0)   == 2);   // rounds toward a (3)
    static_assert(std::midpoint(0, 0)   == 0);
    static_assert(std::midpoint(-1, 1)  == 0);
    static_assert(std::midpoint(1, -1)  == 0);

    // int min/max: no overflow
    constexpr int imin = -2147483648;
    constexpr int imax =  2147483647;
    static_assert(std::midpoint(imin, imax) == -1); // (min+max)/2 = -0.5 -> rounds toward imin
    // verify: imin + (imax-imin)/2 = imin + (imax-imin)/2
    // unsigned diff = imax - imin = 4294967295
    // half_diff = 4294967295/2 = 2147483647
    // result = imin + 2147483647 = -1
    static_assert(std::midpoint(imax, imin) == 0);
}

void test_numeric_midpoint_float() {
    static_assert(std::midpoint(0.0f, 4.0f)  == 2.0f);
    static_assert(std::midpoint(1.0,  3.0)   == 2.0);
    static_assert(std::midpoint(1.0f, 2.0f)  == 1.5f);

    // Verify no overflow: large values
    constexpr float fmax = __FLT_MAX__;
    constexpr float res = std::midpoint(fmax, fmax);
    static_assert(res == fmax);
}

void test_numeric_midpoint_pointer() {
    int arr[5] = {0, 1, 2, 3, 4};
    int* p = std::midpoint(arr, arr + 4);
    CHECK(p == arr + 2);

    int* p2 = std::midpoint(arr, arr + 5);
    CHECK(p2 == arr + 2);

    // midpoint(a, a) == a
    CHECK(std::midpoint(arr, arr) == arr);
}
