// test/ostream.cpp — tests for <ostream> and <iostream> (basic_ostream).
// Each test function crashes on failure via CHECK(); silent on success.
// No main() — auto-generated by tools/gen_main.sh.

#include <ostream>
#include <iostream>
#include <cstring>   // memcmp
#include "test.h"

//===----------------------------------------------------------------------===//
// String-backed streambuf for testing.
// Supports write (sputc/sputn) and read (sgetc/sbumpc) after commit().
//===----------------------------------------------------------------------===//
struct __attribute__((visibility("hidden"))) StrBuf : std::streambuf {
    static constexpr int cap = 256;
    char data[cap] = {};

    StrBuf() { setp(data, data + cap); }

    int  size()  const { return static_cast<int>(pptr() - pbase()); }
    const char* str() { data[size()] = '\0'; return data; }

    void reset() {
        for (int i = 0; i < cap; ++i) data[i] = 0;
        setp(data, data + cap);
        setg(nullptr, nullptr, nullptr);
    }

    // Switch to read mode over what was written.
    void commit() {
        int n = size();
        setg(data, data, data + n);
    }

    int_type overflow(int_type c) override { return traits_type::eof(); }
    int_type underflow() override           { return traits_type::eof(); }
};

//===----------------------------------------------------------------------===//
// test_ostream_integers
//===----------------------------------------------------------------------===//
void test_ostream_integers() {
    StrBuf buf;
    std::ostream os(&buf);

    os << 42;
    CHECK(buf.size() == 2);
    CHECK(__builtin_memcmp(buf.data, "42", 2) == 0);
    buf.reset();

    os << -7;
    CHECK(buf.size() == 2);
    CHECK(__builtin_memcmp(buf.str(), "-7", 2) == 0);
    buf.reset();

    os << 0;
    CHECK(buf.size() == 1);
    CHECK(buf.data[0] == '0');
    buf.reset();

    os << 12345678LL;
    CHECK(__builtin_memcmp(buf.str(), "12345678", 8) == 0);
    buf.reset();

    os << static_cast<unsigned long long>(18446744073709551615ULL);
    // "18446744073709551615"
    CHECK(__builtin_memcmp(buf.str(), "18446744073709551615", 20) == 0);
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_hex_oct
//===----------------------------------------------------------------------===//
void test_ostream_hex_oct() {
    StrBuf buf;
    std::ostream os(&buf);

    os << std::hex << 255;
    CHECK(buf.size() == 2);
    CHECK(__builtin_memcmp(buf.str(), "ff", 2) == 0);
    buf.reset();

    os << std::uppercase << 255;
    CHECK(buf.size() == 2);
    CHECK(__builtin_memcmp(buf.str(), "FF", 2) == 0);
    os << std::nouppercase;
    buf.reset();

    os << std::showbase << 0xFF;
    CHECK(buf.size() == 4);
    CHECK(__builtin_memcmp(buf.str(), "0xff", 4) == 0);
    os << std::noshowbase;
    buf.reset();

    os << std::oct << 8;
    CHECK(buf.size() == 2);
    CHECK(__builtin_memcmp(buf.str(), "10", 2) == 0);
    buf.reset();

    os << std::showbase << 8;
    CHECK(buf.size() == 3);
    CHECK(__builtin_memcmp(buf.str(), "010", 3) == 0);
    os << std::noshowbase;
    buf.reset();

    os << std::dec;
}

//===----------------------------------------------------------------------===//
// test_ostream_bool
//===----------------------------------------------------------------------===//
void test_ostream_bool() {
    StrBuf buf;
    std::ostream os(&buf);

    os << true;
    CHECK(buf.size() == 1 && buf.data[0] == '1');
    buf.reset();

    os << false;
    CHECK(buf.size() == 1 && buf.data[0] == '0');
    buf.reset();

    os << std::boolalpha << true;
    CHECK(buf.size() == 4);
    CHECK(__builtin_memcmp(buf.str(), "true", 4) == 0);
    buf.reset();

    os << false;
    CHECK(buf.size() == 5);
    CHECK(__builtin_memcmp(buf.str(), "false", 5) == 0);
    os << std::noboolalpha;
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_floats
//===----------------------------------------------------------------------===//
void test_ostream_floats() {
    StrBuf buf;
    std::ostream os(&buf);

    // Default precision 6, %g format: 3.14 -> "3.14"
    os << 3.14;
    CHECK(buf.size() > 0);
    // "3.14" with %g6
    CHECK(__builtin_memcmp(buf.str(), "3.14", 4) == 0);
    buf.reset();

    // Fixed with precision 2
    os << std::fixed;
    os.precision(2);
    os << 3.14159;
    CHECK(buf.size() == 4);
    CHECK(__builtin_memcmp(buf.str(), "3.14", 4) == 0);
    os << std::defaultfloat;
    os.precision(6);
    buf.reset();

    // Scientific
    os << std::scientific;
    os.precision(2);
    os << 12345.0;
    // "1.23e+04"
    CHECK(buf.size() > 0);
    CHECK(buf.data[0] == '1');
    os << std::defaultfloat;
    os.precision(6);
    buf.reset();

    // Negative float
    os << -1.5;
    CHECK(buf.data[0] == '-');
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_strings
//===----------------------------------------------------------------------===//
void test_ostream_strings() {
    StrBuf buf;
    std::ostream os(&buf);

    os << "hello";
    CHECK(buf.size() == 5);
    CHECK(__builtin_memcmp(buf.str(), "hello", 5) == 0);
    buf.reset();

    os << 'A';
    CHECK(buf.size() == 1 && buf.data[0] == 'A');
    buf.reset();

    const char* p = "world";
    os << p;
    CHECK(buf.size() == 5);
    CHECK(__builtin_memcmp(buf.str(), "world", 5) == 0);
    buf.reset();

    // signed char*
    const signed char* sp = reinterpret_cast<const signed char*>("sign");
    os << sp;
    CHECK(buf.size() == 4);
    CHECK(__builtin_memcmp(buf.str(), "sign", 4) == 0);
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_width_fill
//===----------------------------------------------------------------------===//
void test_ostream_width_fill() {
    StrBuf buf;
    std::ostream os(&buf);

    // right-align, fill '0', width 6
    os.width(6);
    os.fill('0');
    os << std::right << 42;
    CHECK(buf.size() == 6);
    CHECK(__builtin_memcmp(buf.str(), "000042", 6) == 0);
    buf.reset();

    // Width resets to 0 after each formatted output
    CHECK(os.width() == 0);

    // left-align
    os.fill(' ');
    os.width(6);
    os << std::left << 42;
    CHECK(buf.size() == 6);
    CHECK(buf.data[0] == '4' && buf.data[1] == '2');
    CHECK(buf.data[2] == ' ' && buf.data[5] == ' ');
    buf.reset();

    // right with string
    os.width(6);
    os << std::right << "ab";
    CHECK(buf.size() == 6);
    CHECK(buf.data[0] == ' ' && buf.data[4] == 'a' && buf.data[5] == 'b');
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_manipulators
//===----------------------------------------------------------------------===//
void test_ostream_manipulators() {
    StrBuf buf;
    std::ostream os(&buf);

    os << std::endl;
    CHECK(buf.size() == 1 && buf.data[0] == '\n');
    buf.reset();

    os << std::ends;
    CHECK(buf.size() == 1 && buf.data[0] == '\0');
    buf.reset();

    os << std::flush;
    CHECK(buf.size() == 0);
}

//===----------------------------------------------------------------------===//
// test_ostream_nullptr
//===----------------------------------------------------------------------===//
void test_ostream_nullptr() {
    StrBuf buf;
    std::ostream os(&buf);
    os << nullptr;
    CHECK(buf.size() == 7);
    CHECK(__builtin_memcmp(buf.str(), "nullptr", 7) == 0);
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_showpos
//===----------------------------------------------------------------------===//
void test_ostream_showpos() {
    StrBuf buf;
    std::ostream os(&buf);
    os << std::showpos << 5;
    CHECK(buf.size() == 2);
    CHECK(buf.data[0] == '+' && buf.data[1] == '5');
    os << std::noshowpos;
    buf.reset();

    os << -5;
    CHECK(buf.data[0] == '-');
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_put_write
//===----------------------------------------------------------------------===//
void test_ostream_put_write() {
    StrBuf buf;
    std::ostream os(&buf);

    os.put('X');
    CHECK(buf.size() == 1 && buf.data[0] == 'X');
    buf.reset();

    os.write("abc", 3);
    CHECK(buf.size() == 3 && __builtin_memcmp(buf.str(), "abc", 3) == 0);
    buf.reset();
}

//===----------------------------------------------------------------------===//
// test_ostream_streambuf_insert
// os << sb: copies all characters from sb into os.
//===----------------------------------------------------------------------===//
void test_ostream_streambuf_insert() {
    StrBuf src, dst;
    // Write "hello" into src
    src.sputn("hello", 5);
    // Switch src to read mode
    src.commit();

    // Copy src -> dst via operator<<(basic_streambuf*)
    std::ostream os_dst(&dst);
    os_dst << &src;
    CHECK(dst.size() == 5);
    CHECK(__builtin_memcmp(dst.str(), "hello", 5) == 0);
}

//===----------------------------------------------------------------------===//
// test_ostream_cout_compiles
// Verify global stream objects are usable (no crash).
//===----------------------------------------------------------------------===//
void test_ostream_cout_compiles() {
    CHECK(&std::cout != nullptr);
    CHECK(&std::cerr != nullptr);
    CHECK(&std::clog != nullptr);
    // Write empty string — should not crash
    std::cout << "";
    std::cerr << "";
    std::clog << "";
}
