// test/queue.cpp — tests for <queue> (queue and priority_queue)
// Each test_ function is a no-arg free function using CHECK and static_assert.
// main() is auto-generated by tools/gen_main.sh.

#include <queue>
#include <deque>
#include <vector>
#include "test.h"

//===----------------------------------------------------------------------===//
// queue — type checks
//===----------------------------------------------------------------------===//

void test_queue_types() {
    using Q = std::queue<int>;
    static_assert(std::is_same_v<Q::value_type, int>);
    static_assert(std::is_same_v<Q::container_type, std::deque<int>>);
    static_assert(std::is_same_v<Q::reference, int&>);
    static_assert(std::is_same_v<Q::const_reference, const int&>);

    using QV = std::queue<double, std::deque<double>>;
    static_assert(std::is_same_v<QV::container_type, std::deque<double>>);
}

//===----------------------------------------------------------------------===//
// queue — default construction
//===----------------------------------------------------------------------===//

void test_queue_default_ctor() {
    std::queue<int> q;
    CHECK(q.empty());
    CHECK(q.size() == 0);
}

//===----------------------------------------------------------------------===//
// queue — push / front / back / pop
//===----------------------------------------------------------------------===//

void test_queue_push_front_back_pop() {
    std::queue<int> q;
    q.push(1);
    q.push(2);
    q.push(3);
    CHECK(q.size() == 3);
    CHECK(q.front() == 1);
    CHECK(q.back() == 3);
    q.pop();
    CHECK(q.front() == 2);
    CHECK(q.back() == 3);
    q.pop();
    q.pop();
    CHECK(q.empty());
}

//===----------------------------------------------------------------------===//
// queue — emplace
//===----------------------------------------------------------------------===//

void test_queue_emplace() {
    std::queue<int> q;
    q.emplace(7);
    q.emplace(8);
    CHECK(q.front() == 7);
    CHECK(q.back() == 8);
    CHECK(q.size() == 2);
}

//===----------------------------------------------------------------------===//
// queue — copy construction and assignment
//===----------------------------------------------------------------------===//

void test_queue_copy() {
    std::queue<int> a;
    a.push(10);
    a.push(20);

    std::queue<int> b(a);
    CHECK(b.size() == 2);
    CHECK(b.front() == 10);

    std::queue<int> c;
    c = a;
    CHECK(c.size() == 2);
    CHECK(c.back() == 20);
}

//===----------------------------------------------------------------------===//
// queue — move construction and assignment
//===----------------------------------------------------------------------===//

void test_queue_move() {
    std::queue<int> a;
    a.push(5);
    a.push(6);

    std::queue<int> b(std::move(a));
    CHECK(b.size() == 2);
    CHECK(b.front() == 5);

    std::queue<int> c;
    c = std::move(b);
    CHECK(c.size() == 2);
    CHECK(c.back() == 6);
}

//===----------------------------------------------------------------------===//
// queue — construction from container
//===----------------------------------------------------------------------===//

void test_queue_from_container() {
    std::deque<int> d{1, 2, 3};
    std::queue<int> q(d);
    CHECK(q.size() == 3);
    CHECK(q.front() == 1);
    CHECK(q.back() == 3);

    std::deque<int> d2{4, 5};
    std::queue<int> q2(std::move(d2));
    CHECK(q2.size() == 2);
    CHECK(q2.front() == 4);
}

//===----------------------------------------------------------------------===//
// queue — swap
//===----------------------------------------------------------------------===//

void test_queue_swap() {
    std::queue<int> a, b;
    a.push(1); a.push(2);
    b.push(10);

    a.swap(b);
    CHECK(a.size() == 1);
    CHECK(a.front() == 10);
    CHECK(b.size() == 2);
    CHECK(b.front() == 1);

    std::swap(a, b);
    CHECK(a.size() == 2);
    CHECK(a.front() == 1);
}

//===----------------------------------------------------------------------===//
// queue — comparison operators
//===----------------------------------------------------------------------===//

void test_queue_comparisons() {
    std::queue<int> a, b;
    a.push(1); a.push(2);
    b.push(1); b.push(2);

    CHECK(a == b);
    CHECK(!(a != b));
    CHECK(!(a < b));
    CHECK(a <= b);
    CHECK(a >= b);
    CHECK(!(a > b));

    b.push(3);
    CHECK(a != b);
    CHECK(a < b);
    CHECK(!(b < a));
    CHECK(a <= b);
    CHECK(!(a >= b));
    CHECK(b > a);
}

//===----------------------------------------------------------------------===//
// queue — operator<=> (three-way comparison)
//===----------------------------------------------------------------------===//

void test_queue_spaceship() {
    std::queue<int> a, b;
    a.push(1); a.push(2);
    b.push(1); b.push(2);
    CHECK((a <=> b) == std::strong_ordering::equal);

    b.push(3);
    CHECK((a <=> b) == std::strong_ordering::less);
    CHECK((b <=> a) == std::strong_ordering::greater);
}

//===----------------------------------------------------------------------===//
// queue — uses_allocator
//===----------------------------------------------------------------------===//

void test_queue_uses_allocator() {
    static_assert(std::uses_allocator<std::queue<int>, std::allocator<int>>::value);
}

//===----------------------------------------------------------------------===//
// queue — deduction guides
//===----------------------------------------------------------------------===//

void test_queue_deduction_guides() {
    std::deque<int> d{1, 2, 3};
    std::queue q(d);
    static_assert(std::is_same_v<decltype(q), std::queue<int>>);
    CHECK(q.size() == 3);
}

//===----------------------------------------------------------------------===//
// priority_queue — type checks
//===----------------------------------------------------------------------===//

void test_pqueue_types() {
    using PQ = std::priority_queue<int>;
    static_assert(std::is_same_v<PQ::value_type, int>);
    static_assert(std::is_same_v<PQ::container_type, std::vector<int>>);
    static_assert(std::is_same_v<PQ::value_compare, std::less<int>>);
    static_assert(std::is_same_v<PQ::reference, int&>);
    static_assert(std::is_same_v<PQ::const_reference, const int&>);
}

//===----------------------------------------------------------------------===//
// priority_queue — default construction
//===----------------------------------------------------------------------===//

void test_pqueue_default_ctor() {
    std::priority_queue<int> pq;
    CHECK(pq.empty());
    CHECK(pq.size() == 0);
}

//===----------------------------------------------------------------------===//
// priority_queue — push / top / pop (max-heap by default)
//===----------------------------------------------------------------------===//

void test_pqueue_push_top_pop() {
    std::priority_queue<int> pq;
    pq.push(3);
    pq.push(1);
    pq.push(4);
    pq.push(1);
    pq.push(5);
    pq.push(9);
    pq.push(2);
    CHECK(pq.size() == 7);
    // Should come out in descending order (max-heap)
    int prev = pq.top();
    pq.pop();
    while (!pq.empty()) {
        CHECK(pq.top() <= prev);
        prev = pq.top();
        pq.pop();
    }
}

//===----------------------------------------------------------------------===//
// priority_queue — emplace
//===----------------------------------------------------------------------===//

void test_pqueue_emplace() {
    std::priority_queue<int> pq;
    pq.emplace(42);
    pq.emplace(7);
    pq.emplace(100);
    CHECK(pq.top() == 100);
}

//===----------------------------------------------------------------------===//
// priority_queue — min-heap with greater<>
//===----------------------------------------------------------------------===//

void test_pqueue_min_heap() {
    std::priority_queue<int, std::vector<int>, std::greater<int>> pq;
    pq.push(5);
    pq.push(3);
    pq.push(8);
    pq.push(1);
    // Should come out in ascending order (min-heap)
    int prev = pq.top();
    pq.pop();
    while (!pq.empty()) {
        CHECK(pq.top() >= prev);
        prev = pq.top();
        pq.pop();
    }
}

//===----------------------------------------------------------------------===//
// priority_queue — copy construction and assignment
//===----------------------------------------------------------------------===//

void test_pqueue_copy() {
    std::priority_queue<int> a;
    a.push(10);
    a.push(20);
    a.push(5);

    std::priority_queue<int> b(a);
    CHECK(b.size() == 3);
    CHECK(b.top() == 20);

    std::priority_queue<int> c;
    c = a;
    CHECK(c.size() == 3);
    CHECK(c.top() == 20);
}

//===----------------------------------------------------------------------===//
// priority_queue — move construction and assignment
//===----------------------------------------------------------------------===//

void test_pqueue_move() {
    std::priority_queue<int> a;
    a.push(50);
    a.push(30);

    std::priority_queue<int> b(std::move(a));
    CHECK(b.size() == 2);
    CHECK(b.top() == 50);

    std::priority_queue<int> c;
    c = std::move(b);
    CHECK(c.size() == 2);
    CHECK(c.top() == 50);
}

//===----------------------------------------------------------------------===//
// priority_queue — construction from iterators
//===----------------------------------------------------------------------===//

void test_pqueue_iter_ctor() {
    int arr[] = {3, 1, 4, 1, 5, 9, 2, 6};
    std::priority_queue<int> pq(arr, arr + 8);
    CHECK(pq.size() == 8);
    CHECK(pq.top() == 9);

    // With explicit container: v={7,2,8} + arr[0..2]={3,1,4} => max is 8
    std::vector<int> v{7, 2, 8};
    std::priority_queue<int> pq2(arr, arr + 3, std::less<int>{}, v);
    CHECK(pq2.size() == 6); // 3 from v + 3 from arr
    CHECK(pq2.top() == 8);

    // With rvalue container: v2={100} + arr[0..2]={3,1,4} => max is 100
    std::vector<int> v2{100};
    std::priority_queue<int> pq3(arr, arr + 3, std::less<int>{}, std::move(v2));
    CHECK(pq3.top() == 100);
}

//===----------------------------------------------------------------------===//
// priority_queue — construction from Compare + Container
//===----------------------------------------------------------------------===//

void test_pqueue_comp_cont_ctor() {
    std::vector<int> v{5, 3, 8, 1};
    std::priority_queue<int> pq(std::less<int>{}, v);
    CHECK(pq.size() == 4);
    CHECK(pq.top() == 8);

    std::vector<int> v2{10, 2, 7};
    std::priority_queue<int> pq2(std::less<int>{}, std::move(v2));
    CHECK(pq2.size() == 3);
    CHECK(pq2.top() == 10);
}

//===----------------------------------------------------------------------===//
// priority_queue — swap
//===----------------------------------------------------------------------===//

void test_pqueue_swap() {
    std::priority_queue<int> a, b;
    a.push(10); a.push(20);
    b.push(100);

    a.swap(b);
    CHECK(a.size() == 1);
    CHECK(a.top() == 100);
    CHECK(b.size() == 2);
    CHECK(b.top() == 20);

    std::swap(a, b);
    CHECK(a.size() == 2);
    CHECK(a.top() == 20);
}

//===----------------------------------------------------------------------===//
// priority_queue — uses_allocator
//===----------------------------------------------------------------------===//

void test_pqueue_uses_allocator() {
    static_assert(std::uses_allocator<
        std::priority_queue<int>, std::allocator<int>>::value);
}

//===----------------------------------------------------------------------===//
// priority_queue — deduction guides
//===----------------------------------------------------------------------===//

void test_pqueue_deduction_guides() {
    std::priority_queue pq(std::less<int>{}, std::vector<int>{3, 1, 4});
    static_assert(std::is_same_v<decltype(pq),
        std::priority_queue<int, std::vector<int>, std::less<int>>>);
    CHECK(pq.top() == 4);
}
