// Tests for <span> — libcis port.
// Each function is named test_span_<case>; main is auto-generated by
// tools/gen_main.sh.  No progress printing; failures trap via CHECK().
#include "test.h"
#include <span>
#include <array>
#include <iterator>
#include <type_traits>
#include <cstddef>

//===----------------------------------------------------------------------===//
// test_span_dynamic_extent — constant
//===----------------------------------------------------------------------===//

void test_span_dynamic_extent() {
    static_assert(std::dynamic_extent == static_cast<std::size_t>(-1));
}

//===----------------------------------------------------------------------===//
// test_span_types — member type aliases
//===----------------------------------------------------------------------===//

void test_span_types() {
    using S = std::span<int, 3>;
    static_assert(std::is_same_v<S::element_type,    int>);
    static_assert(std::is_same_v<S::value_type,      int>);
    static_assert(std::is_same_v<S::size_type,       std::size_t>);
    static_assert(std::is_same_v<S::difference_type, std::ptrdiff_t>);
    static_assert(std::is_same_v<S::pointer,         int*>);
    static_assert(std::is_same_v<S::const_pointer,   const int*>);
    static_assert(std::is_same_v<S::reference,       int&>);
    static_assert(std::is_same_v<S::const_reference, const int&>);
    // iterator is an implementation-defined type; verify the standard properties
    // rather than pinning the exact type (vendors use wrapper iterators).
    static_assert(std::contiguous_iterator<S::iterator>);
    static_assert(std::is_same_v<std::iter_value_t<S::iterator>, int>);
    static_assert(S::extent == 3);

    using D = std::span<int>;
    static_assert(D::extent == std::dynamic_extent);
}

//===----------------------------------------------------------------------===//
// test_span_default_ctor — default construction (Extent == 0 only)
//===----------------------------------------------------------------------===//

void test_span_default_ctor() {
    std::span<int, 0> s;
    CHECK(s.data() == nullptr);
    CHECK(s.size() == 0);
    CHECK(s.empty());

    std::span<int> d;
    CHECK(d.data() == nullptr);
    CHECK(d.size() == 0);
    CHECK(d.empty());
}

//===----------------------------------------------------------------------===//
// test_span_ptr_count — (pointer, count) constructor
//===----------------------------------------------------------------------===//

void test_span_ptr_count() {
    int arr[5] = {1, 2, 3, 4, 5};

    std::span<int> d(arr, 3);
    CHECK(d.data() == arr);
    CHECK(d.size() == 3);
    CHECK(d[0] == 1 && d[1] == 2 && d[2] == 3);

    std::span<int, 3> s(arr, 3);
    CHECK(s.data() == arr);
    CHECK(s.size() == 3);
    CHECK(s[0] == 1 && s[2] == 3);
}

//===----------------------------------------------------------------------===//
// test_span_ptr_ptr — (iterator, sentinel) constructor
//===----------------------------------------------------------------------===//

void test_span_ptr_ptr() {
    int arr[5] = {10, 20, 30, 40, 50};

    std::span<int> d(arr, arr + 5);
    CHECK(d.size() == 5);
    CHECK(d[4] == 50);

    std::span<int, 5> s(arr, arr + 5);
    CHECK(s.size() == 5);
    CHECK(s[0] == 10);
}

//===----------------------------------------------------------------------===//
// test_span_c_array — C array constructor
//===----------------------------------------------------------------------===//

void test_span_c_array() {
    int arr[4] = {1, 2, 3, 4};

    std::span<int, 4> s(arr);
    CHECK(s.size() == 4);
    CHECK(s[3] == 4);
    CHECK(s.data() == arr);

    std::span<int> d(arr);
    CHECK(d.size() == 4);
    CHECK(d[0] == 1);
}

//===----------------------------------------------------------------------===//
// test_span_std_array — std::array constructor
//===----------------------------------------------------------------------===//

void test_span_std_array() {
    std::array<int, 3> a = {7, 8, 9};

    std::span<int, 3> s(a);
    CHECK(s.size() == 3);
    CHECK(s[0] == 7 && s[1] == 8 && s[2] == 9);

    std::span<int> d(a);
    CHECK(d.size() == 3);
    CHECK(d[2] == 9);

    const std::array<int, 3> ca = {4, 5, 6};
    std::span<const int, 3> cs(ca);
    CHECK(cs.size() == 3);
    CHECK(cs[0] == 4);

    std::span<const int> cd(ca);
    CHECK(cd.size() == 3);
}

//===----------------------------------------------------------------------===//
// test_span_copy_ctor — copy constructor and assignment
//===----------------------------------------------------------------------===//

void test_span_copy_ctor() {
    int arr[3] = {1, 2, 3};
    std::span<int, 3> s(arr, 3);
    std::span<int, 3> s2 = s;
    CHECK(s2.data() == s.data());
    CHECK(s2.size() == 3);

    std::span<int> d(arr, 3);
    std::span<int> d2 = d;
    CHECK(d2.size() == 3);
    CHECK(d2.data() == arr);

    // assignment
    std::span<int> d3;
    d3 = d;
    CHECK(d3.size() == 3);
}

//===----------------------------------------------------------------------===//
// test_span_converting_ctor — cross-extent conversions
//===----------------------------------------------------------------------===//

void test_span_converting_ctor() {
    int arr[5] = {1, 2, 3, 4, 5};

    // static -> dynamic
    std::span<int, 5> s(arr, 5);
    std::span<int> d(s);
    CHECK(d.size() == 5);
    CHECK(d.data() == arr);

    // dynamic -> static (explicit)
    std::span<int> d2(arr, 3);
    std::span<int, 3> s2(d2);
    CHECK(s2.size() == 3);
    CHECK(s2.data() == arr);

    // same extent, different cv
    std::span<int, 5> ms(arr, 5);
    std::span<const int, 5> cs(ms);
    CHECK(cs.size() == 5);
    CHECK(cs[0] == 1);
}

//===----------------------------------------------------------------------===//
// test_span_observers — size, size_bytes, empty
//===----------------------------------------------------------------------===//

void test_span_observers() {
    int arr[4] = {1, 2, 3, 4};

    std::span<int, 4> s(arr);
    CHECK(s.size() == 4);
    CHECK(s.size_bytes() == 4 * sizeof(int));
    CHECK(!s.empty());

    std::span<int, 0> z;
    CHECK(z.size() == 0);
    CHECK(z.size_bytes() == 0);
    CHECK(z.empty());

    std::span<int> d(arr, 4);
    CHECK(d.size() == 4);
    CHECK(d.size_bytes() == 4 * sizeof(int));
    CHECK(!d.empty());

    std::span<int> e;
    CHECK(e.empty());
}

//===----------------------------------------------------------------------===//
// test_span_element_access — operator[], front, back, data
//===----------------------------------------------------------------------===//

void test_span_element_access() {
    int arr[5] = {10, 20, 30, 40, 50};
    std::span<int, 5> s(arr);

    CHECK(s[0] == 10);
    CHECK(s[4] == 50);
    CHECK(s.front() == 10);
    CHECK(s.back() == 50);
    CHECK(s.data() == arr);

    // modification through span
    s[2] = 99;
    CHECK(arr[2] == 99);
    s[2] = 30; // restore

    std::span<int> d(arr, 5);
    CHECK(d.front() == 10);
    CHECK(d.back() == 50);
    CHECK(d.data() == arr);
}

//===----------------------------------------------------------------------===//
// test_span_iterators — begin, end, rbegin, rend
//===----------------------------------------------------------------------===//

void test_span_iterators() {
    int arr[5] = {1, 2, 3, 4, 5};

    std::span<int, 5> s(arr);
    // Vendors use wrapper iterators, so compare via to_address / &*it rather
    // than directly against raw pointers.
    CHECK(&*s.begin() == arr);
    CHECK(std::to_address(s.begin()) == arr);
    CHECK(std::to_address(s.end())   == arr + 5);

    int sum = 0;
    for (int x : s) sum += x;
    CHECK(sum == 15);

    // reverse iteration
    int rsum = 0;
    for (auto it = s.rbegin(); it != s.rend(); ++it)
        rsum += *it;
    CHECK(rsum == 15);

    std::span<int> d(arr, 5);
    CHECK(std::to_address(d.begin()) == arr);
    CHECK(std::to_address(d.end())   == arr + 5);

    sum = 0;
    for (int x : d) sum += x;
    CHECK(sum == 15);
}

//===----------------------------------------------------------------------===//
// test_span_first_last_subspan_static — static first/last/subspan
//===----------------------------------------------------------------------===//

void test_span_first_last_subspan_static() {
    int arr[5] = {1, 2, 3, 4, 5};

    std::span<int, 5> s(arr);

    auto f = s.first<3>();
    static_assert(decltype(f)::extent == 3);
    CHECK(f.size() == 3);
    CHECK(f[0] == 1 && f[2] == 3);

    auto l = s.last<2>();
    static_assert(decltype(l)::extent == 2);
    CHECK(l.size() == 2);
    CHECK(l[0] == 4 && l[1] == 5);

    auto ss = s.subspan<1, 3>();
    static_assert(decltype(ss)::extent == 3);
    CHECK(ss.size() == 3);
    CHECK(ss[0] == 2 && ss[2] == 4);

    // subspan<Offset> with default Count = dynamic_extent
    auto ss2 = s.subspan<2>();
    static_assert(decltype(ss2)::extent == 3); // 5 - 2
    CHECK(ss2.size() == 3);
    CHECK(ss2[0] == 3);

    // dynamic_extent span — static first/last
    std::span<int> d(arr, 5);
    auto df = d.first<3>();
    static_assert(decltype(df)::extent == 3);
    CHECK(df.size() == 3 && df[0] == 1);

    auto dl = d.last<2>();
    static_assert(decltype(dl)::extent == 2);
    CHECK(dl[0] == 4 && dl[1] == 5);

    auto ds = d.subspan<1, 2>();
    static_assert(decltype(ds)::extent == 2);
    CHECK(ds[0] == 2 && ds[1] == 3);
}

//===----------------------------------------------------------------------===//
// test_span_first_last_subspan_dynamic — runtime first/last/subspan
//===----------------------------------------------------------------------===//

void test_span_first_last_subspan_dynamic() {
    int arr[5] = {1, 2, 3, 4, 5};
    std::span<int, 5> s(arr);

    auto f = s.first(3);
    static_assert(decltype(f)::extent == std::dynamic_extent);
    CHECK(f.size() == 3);
    CHECK(f[2] == 3);

    auto l = s.last(2);
    CHECK(l.size() == 2);
    CHECK(l[0] == 4 && l[1] == 5);

    auto ss = s.subspan(1, 3);
    CHECK(ss.size() == 3);
    CHECK(ss[0] == 2);

    auto ss2 = s.subspan(2);
    CHECK(ss2.size() == 3);
    CHECK(ss2[0] == 3);

    std::span<int> d(arr, 5);
    CHECK(d.first(2).size() == 2);
    CHECK(d.last(2)[0] == 4);
    CHECK(d.subspan(0, 5).size() == 5);
    CHECK(d.subspan(3).size() == 2);
}

//===----------------------------------------------------------------------===//
// test_span_as_bytes — as_bytes / as_writable_bytes
//===----------------------------------------------------------------------===//

void test_span_as_bytes() {
    int arr[3] = {0x01020304, 0x05060708, 0x090a0b0c};
    std::span<int, 3> s(arr);

    auto b = std::as_bytes(s);
    static_assert(std::is_same_v<decltype(b),
        std::span<const std::byte, 3 * sizeof(int)>>);
    CHECK(b.size() == 3 * sizeof(int));
    CHECK(b.size_bytes() == 3 * sizeof(int));

    auto wb = std::as_writable_bytes(s);
    static_assert(std::is_same_v<decltype(wb),
        std::span<std::byte, 3 * sizeof(int)>>);
    CHECK(wb.size() == 3 * sizeof(int));

    // dynamic extent
    std::span<int> d(arr, 3);
    auto db = std::as_bytes(d);
    static_assert(decltype(db)::extent == std::dynamic_extent);
    CHECK(db.size() == 3 * sizeof(int));

    auto dwb = std::as_writable_bytes(d);
    static_assert(decltype(dwb)::extent == std::dynamic_extent);
    CHECK(dwb.size() == 3 * sizeof(int));
}

//===----------------------------------------------------------------------===//
// test_span_deduction_guides — CTAD
//===----------------------------------------------------------------------===//

void test_span_deduction_guides() {
    // C array
    int arr[4] = {1, 2, 3, 4};
    std::span s1(arr);
    static_assert(std::is_same_v<decltype(s1), std::span<int, 4>>);
    CHECK(s1.size() == 4);

    // std::array
    std::array<double, 3> a = {1.0, 2.0, 3.0};
    std::span s2(a);
    static_assert(std::is_same_v<decltype(s2), std::span<double, 3>>);
    CHECK(s2.size() == 3);

    const std::array<double, 3> ca = {1.0, 2.0, 3.0};
    std::span s3(ca);
    static_assert(std::is_same_v<decltype(s3), std::span<const double, 3>>);

    // pointer pair
    std::span s4(arr, arr + 4);
    static_assert(std::is_same_v<decltype(s4), std::span<int>>);
    CHECK(s4.size() == 4);

    // pointer + count
    std::span s5(arr, static_cast<std::size_t>(4));
    static_assert(std::is_same_v<decltype(s5), std::span<int>>);
    CHECK(s5.size() == 4);
}

//===----------------------------------------------------------------------===//
// test_span_const_element — const element type
//===----------------------------------------------------------------------===//

void test_span_const_element() {
    const int arr[3] = {1, 2, 3};
    std::span<const int, 3> s(arr);
    CHECK(s[0] == 1);
    CHECK(s.front() == 1);
    CHECK(s.back() == 3);

    static_assert(std::is_same_v<std::span<const int, 3>::value_type, int>);

    auto b = std::as_bytes(s);
    static_assert(decltype(b)::extent == 3 * sizeof(int));
    CHECK(b.size() == 3 * sizeof(int));
}

//===----------------------------------------------------------------------===//
// test_span_enable_borrowed_range — ranges::enable_borrowed_range
//===----------------------------------------------------------------------===//

void test_span_enable_borrowed_range() {
    static_assert(std::ranges::enable_borrowed_range<std::span<int>>);
    static_assert(std::ranges::enable_borrowed_range<std::span<int, 5>>);
    static_assert(std::ranges::enable_borrowed_range<std::span<const int>>);
}

//===----------------------------------------------------------------------===//
// test_span_range_for — range-based for loop works
//===----------------------------------------------------------------------===//

void test_span_range_for() {
    int arr[4] = {2, 4, 6, 8};
    std::span<int> s(arr, 4);
    int sum = 0;
    for (int x : s) sum += x;
    CHECK(sum == 20);

    // write through range-for
    for (int& x : s) x *= 2;
    CHECK(arr[0] == 4 && arr[3] == 16);
}

//===----------------------------------------------------------------------===//
// test_span_extent_compile_time — static extent constraints
//===----------------------------------------------------------------------===//

void test_span_extent_compile_time() {
    static_assert(std::span<int, 5>::extent == 5);
    static_assert(std::span<int>::extent == std::dynamic_extent);

    // first/last/subspan return spans with correct extents
    int arr[6] = {};
    std::span<int, 6> s(arr);

    static_assert(decltype(s.first<4>())::extent == 4);
    static_assert(decltype(s.last<2>())::extent  == 2);
    static_assert(decltype(s.subspan<1, 3>())::extent == 3);
    static_assert(decltype(s.subspan<1>())::extent    == 5); // 6-1
}
