// test/stack.cpp — tests for <stack>
// Each test_ function is a no-arg free function using CHECK and static_assert.
// main() is auto-generated by tools/gen_main.sh.

#include <stack>
#include <deque>
#include <vector>
#include "test.h"

//===----------------------------------------------------------------------===//
// Type checks
//===----------------------------------------------------------------------===//

void test_stack_types() {
    using S = std::stack<int>;
    static_assert(std::is_same_v<S::value_type, int>);
    static_assert(std::is_same_v<S::container_type, std::deque<int>>);
    static_assert(std::is_same_v<S::reference, int&>);
    static_assert(std::is_same_v<S::const_reference, const int&>);

    using SV = std::stack<double, std::vector<double>>;
    static_assert(std::is_same_v<SV::container_type, std::vector<double>>);
}

//===----------------------------------------------------------------------===//
// Default construction
//===----------------------------------------------------------------------===//

void test_stack_default_ctor() {
    std::stack<int> s;
    CHECK(s.empty());
    CHECK(s.size() == 0);
}

//===----------------------------------------------------------------------===//
// push / top / pop
//===----------------------------------------------------------------------===//

void test_stack_push_top_pop() {
    std::stack<int> s;
    s.push(1);
    s.push(2);
    s.push(3);
    CHECK(s.size() == 3);
    CHECK(s.top() == 3);
    s.pop();
    CHECK(s.top() == 2);
    s.pop();
    CHECK(s.top() == 1);
    s.pop();
    CHECK(s.empty());
}

//===----------------------------------------------------------------------===//
// emplace
//===----------------------------------------------------------------------===//

void test_stack_emplace() {
    std::stack<int> s;
    s.emplace(42);
    CHECK(s.top() == 42);
    CHECK(s.size() == 1);
}

//===----------------------------------------------------------------------===//
// Copy construction and assignment
//===----------------------------------------------------------------------===//

void test_stack_copy() {
    std::stack<int> a;
    a.push(10);
    a.push(20);

    std::stack<int> b(a);
    CHECK(b.size() == 2);
    CHECK(b.top() == 20);

    std::stack<int> c;
    c = a;
    CHECK(c.size() == 2);
    CHECK(c.top() == 20);
}

//===----------------------------------------------------------------------===//
// Move construction and assignment
//===----------------------------------------------------------------------===//

void test_stack_move() {
    std::stack<int> a;
    a.push(5);
    a.push(6);

    std::stack<int> b(std::move(a));
    CHECK(b.size() == 2);
    CHECK(b.top() == 6);

    std::stack<int> c;
    c = std::move(b);
    CHECK(c.size() == 2);
    CHECK(c.top() == 6);
}

//===----------------------------------------------------------------------===//
// Construction from container
//===----------------------------------------------------------------------===//

void test_stack_from_container() {
    std::deque<int> d{1, 2, 3};
    std::stack<int> s(d);
    CHECK(s.size() == 3);
    CHECK(s.top() == 3);

    std::deque<int> d2{4, 5};
    std::stack<int> s2(std::move(d2));
    CHECK(s2.size() == 2);
    CHECK(s2.top() == 5);
}

//===----------------------------------------------------------------------===//
// swap
//===----------------------------------------------------------------------===//

void test_stack_swap() {
    std::stack<int> a, b;
    a.push(1); a.push(2);
    b.push(10);

    a.swap(b);
    CHECK(a.size() == 1);
    CHECK(a.top() == 10);
    CHECK(b.size() == 2);
    CHECK(b.top() == 2);

    std::swap(a, b);
    CHECK(a.size() == 2);
    CHECK(a.top() == 2);
}

//===----------------------------------------------------------------------===//
// Comparison operators
//===----------------------------------------------------------------------===//

void test_stack_comparisons() {
    std::stack<int> a, b;
    a.push(1); a.push(2);
    b.push(1); b.push(2);

    CHECK(a == b);
    CHECK(!(a != b));
    CHECK(!(a < b));
    CHECK(a <= b);
    CHECK(a >= b);
    CHECK(!(a > b));

    b.push(3);
    CHECK(a != b);
    CHECK(a < b);
    CHECK(!(b < a));
    CHECK(a <= b);
    CHECK(!(a >= b));
    CHECK(b > a);
}

//===----------------------------------------------------------------------===//
// operator<=> (three-way comparison)
//===----------------------------------------------------------------------===//

void test_stack_spaceship() {
    std::stack<int> a, b;
    a.push(1); a.push(2);
    b.push(1); b.push(2);
    CHECK((a <=> b) == std::strong_ordering::equal);

    b.push(3);
    CHECK((a <=> b) == std::strong_ordering::less);
    CHECK((b <=> a) == std::strong_ordering::greater);
}

//===----------------------------------------------------------------------===//
// uses_allocator
//===----------------------------------------------------------------------===//

void test_stack_uses_allocator() {
    static_assert(std::uses_allocator<std::stack<int>, std::allocator<int>>::value);
}

//===----------------------------------------------------------------------===//
// Deduction guides
//===----------------------------------------------------------------------===//

void test_stack_deduction_guides() {
    std::deque<int> d{1, 2, 3};
    std::stack s(d);
    static_assert(std::is_same_v<decltype(s), std::stack<int>>);
    CHECK(s.size() == 3);

    std::stack<int, std::vector<int>> sv;
    sv.push(99);
    CHECK(sv.top() == 99);
}

//===----------------------------------------------------------------------===//
// vector-backed stack
//===----------------------------------------------------------------------===//

void test_stack_vector_backend() {
    std::stack<int, std::vector<int>> s;
    for (int i = 0; i < 10; ++i)
        s.push(i);
    CHECK(s.size() == 10);
    CHECK(s.top() == 9);
    for (int i = 9; i >= 0; --i) {
        CHECK(s.top() == i);
        s.pop();
    }
    CHECK(s.empty());
}
