// Tests for <stdexcept>, ported from libc++ test suite.
// Covers: logic_error, invalid_argument, domain_error, length_error,
//         out_of_range, runtime_error, range_error, overflow_error,
//         underflow_error — inheritance, what() content, copy semantics.
// No main(); auto-generated by tools/gen_main.sh.
#include <stdexcept>
#include "test.h"

// Helper: compare two C-strings
static bool streq(const char* a, const char* b) {
    return __builtin_strcmp(a, b) == 0;
}

//===----------------------------------------------------------------------===//
// test_stdexcept_logic_error
//===----------------------------------------------------------------------===//
void test_stdexcept_logic_error() {
    // Inheritance
    static_assert(__is_base_of(std::exception,   std::logic_error));
    static_assert(__is_polymorphic(std::logic_error));

    const char* msg = "logic_error message";

    // Construct from const char*
    std::logic_error e(msg);
    CHECK(streq(e.what(), msg));

    // Copy constructor
    std::logic_error e2(e);
    CHECK(streq(e2.what(), msg));

    // Copy assignment
    std::logic_error e3("other");
    e3 = e;
    CHECK(streq(e3.what(), msg));

    // Access through base pointer
    std::exception* p = &e;
    CHECK(streq(p->what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_invalid_argument
//===----------------------------------------------------------------------===//
void test_stdexcept_invalid_argument() {
    static_assert(__is_base_of(std::exception,   std::invalid_argument));
    static_assert(__is_base_of(std::logic_error, std::invalid_argument));
    static_assert(__is_polymorphic(std::invalid_argument));

    const char* msg = "invalid_argument message";
    std::invalid_argument e(msg);
    CHECK(streq(e.what(), msg));

    std::invalid_argument e2(e);
    CHECK(streq(e2.what(), msg));

    std::invalid_argument e3("placeholder");
    e3 = e;
    CHECK(streq(e3.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_domain_error
//===----------------------------------------------------------------------===//
void test_stdexcept_domain_error() {
    static_assert(__is_base_of(std::exception,   std::domain_error));
    static_assert(__is_base_of(std::logic_error, std::domain_error));
    static_assert(__is_polymorphic(std::domain_error));

    const char* msg = "domain_error message";
    std::domain_error e(msg);
    CHECK(streq(e.what(), msg));

    std::domain_error e2(e);
    CHECK(streq(e2.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_length_error
//===----------------------------------------------------------------------===//
void test_stdexcept_length_error() {
    static_assert(__is_base_of(std::exception,   std::length_error));
    static_assert(__is_base_of(std::logic_error, std::length_error));
    static_assert(__is_polymorphic(std::length_error));

    const char* msg = "length_error message";
    std::length_error e(msg);
    CHECK(streq(e.what(), msg));

    std::length_error e2(e);
    CHECK(streq(e2.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_out_of_range
//===----------------------------------------------------------------------===//
void test_stdexcept_out_of_range() {
    static_assert(__is_base_of(std::exception,   std::out_of_range));
    static_assert(__is_base_of(std::logic_error, std::out_of_range));
    static_assert(__is_polymorphic(std::out_of_range));

    const char* msg = "out_of_range message";
    std::out_of_range e(msg);
    CHECK(streq(e.what(), msg));

    std::out_of_range e2(e);
    CHECK(streq(e2.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_runtime_error
//===----------------------------------------------------------------------===//
void test_stdexcept_runtime_error() {
    static_assert(__is_base_of(std::exception, std::runtime_error));
    static_assert(__is_polymorphic(std::runtime_error));

    const char* msg = "runtime_error message";
    std::runtime_error e(msg);
    CHECK(streq(e.what(), msg));

    std::runtime_error e2(e);
    CHECK(streq(e2.what(), msg));

    std::runtime_error e3("placeholder");
    e3 = e;
    CHECK(streq(e3.what(), msg));

    std::exception* p = &e;
    CHECK(streq(p->what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_range_error
//===----------------------------------------------------------------------===//
void test_stdexcept_range_error() {
    static_assert(__is_base_of(std::exception,      std::range_error));
    static_assert(__is_base_of(std::runtime_error,  std::range_error));
    static_assert(__is_polymorphic(std::range_error));

    const char* msg = "range_error message";
    std::range_error e(msg);
    CHECK(streq(e.what(), msg));

    std::range_error e2(e);
    CHECK(streq(e2.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_overflow_error
//===----------------------------------------------------------------------===//
void test_stdexcept_overflow_error() {
    static_assert(__is_base_of(std::exception,      std::overflow_error));
    static_assert(__is_base_of(std::runtime_error,  std::overflow_error));
    static_assert(__is_polymorphic(std::overflow_error));

    const char* msg = "overflow_error message";
    std::overflow_error e(msg);
    CHECK(streq(e.what(), msg));

    std::overflow_error e2(e);
    CHECK(streq(e2.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_underflow_error
//===----------------------------------------------------------------------===//
void test_stdexcept_underflow_error() {
    static_assert(__is_base_of(std::exception,      std::underflow_error));
    static_assert(__is_base_of(std::runtime_error,  std::underflow_error));
    static_assert(__is_polymorphic(std::underflow_error));

    const char* msg = "underflow_error message";
    std::underflow_error e(msg);
    CHECK(streq(e.what(), msg));

    std::underflow_error e2(e);
    CHECK(streq(e2.what(), msg));
}

//===----------------------------------------------------------------------===//
// test_stdexcept_refcount
// Verify that the refcount storage is shared and that the string survives
// across multiple copies and outlives the original.
//===----------------------------------------------------------------------===//
void test_stdexcept_refcount() {
    const char* msg = "refcount test message";

    // Create a copy that outlives the original to exercise the refcount path.
    std::logic_error* p = nullptr;
    {
        std::logic_error orig(msg);
        p = new std::logic_error(orig); // copy; orig destroyed at end of block
    }
    // The copy must still have the message intact
    CHECK(streq(p->what(), msg));
    delete p;
}
