// test/stop_token.cpp — tests for <stop_token>
// Each test_* function is a no-arg free function using CHECK / static_assert.
// main() is auto-generated by tools/gen_main.sh.
#include <stop_token>
#include <atomic>
#include <thread>
#include "test.h"

// ============================================================
// test_stop_token_basic
// ============================================================
void test_stop_token_basic() {
    // Default-constructed stop_token: no stop possible, no stop requested
    std::stop_token st;
    CHECK(!st.stop_possible());
    CHECK(!st.stop_requested());
}

// ============================================================
// test_stop_token_source_token
// ============================================================
void test_stop_token_source_token() {
    std::stop_source ss;
    CHECK(ss.stop_possible());
    CHECK(!ss.stop_requested());

    std::stop_token st = ss.get_token();
    CHECK(st.stop_possible());
    CHECK(!st.stop_requested());

    ss.request_stop();

    CHECK(ss.stop_requested());
    CHECK(st.stop_requested());
}

// ============================================================
// test_stop_token_nostopstate
// ============================================================
void test_stop_token_nostopstate() {
    std::stop_source ss(std::nostopstate);
    CHECK(!ss.stop_possible());

    std::stop_token st = ss.get_token();
    CHECK(!st.stop_possible());
    CHECK(!st.stop_requested());
}

// ============================================================
// test_stop_token_callback_fires
// ============================================================
void test_stop_token_callback_fires() {
    std::stop_source ss;
    std::atomic<int> fired{0};

    {
        std::stop_callback cb(ss.get_token(), [&fired]() noexcept {
            fired.fetch_add(1, std::memory_order_relaxed);
        });

        ss.request_stop();
    }

    CHECK(fired.load() == 1);
}

// ============================================================
// test_stop_token_callback_already_stopped
// ============================================================
void test_stop_token_callback_already_stopped() {
    std::stop_source ss;
    ss.request_stop();

    std::atomic<int> fired{0};
    // Registering a callback after stop_requested -> fires immediately
    std::stop_callback cb(ss.get_token(), [&fired]() noexcept {
        fired.fetch_add(1, std::memory_order_relaxed);
    });

    CHECK(fired.load() == 1);
}

// ============================================================
// test_stop_token_multiple_callbacks
// ============================================================
void test_stop_token_multiple_callbacks() {
    std::stop_source ss;
    std::atomic<int> count{0};

    std::stop_callback cb1(ss.get_token(), [&count]() noexcept {
        count.fetch_add(1, std::memory_order_relaxed);
    });
    std::stop_callback cb2(ss.get_token(), [&count]() noexcept {
        count.fetch_add(1, std::memory_order_relaxed);
    });

    ss.request_stop();
    CHECK(count.load() == 2);
}

// ============================================================
// test_stop_token_callback_removed_before_stop
// ============================================================
void test_stop_token_callback_removed_before_stop() {
    std::stop_source ss;
    std::atomic<int> fired{0};

    {
        std::stop_callback cb(ss.get_token(), [&fired]() noexcept {
            fired.fetch_add(1, std::memory_order_relaxed);
        });
        // cb destroyed here — should be removed from list
    }

    ss.request_stop();
    CHECK(fired.load() == 0);
}

// ============================================================
// test_stop_token_callback_in_thread
// ============================================================
void test_stop_token_callback_in_thread() {
    std::stop_source ss;
    std::atomic<int> counter{0};

    auto run = [&ss, &counter]() {
        std::stop_callback cb(ss.get_token(), [&counter]() noexcept {
            counter.fetch_add(1, std::memory_order_release);
        });
        // spin until stopped
        while (!ss.stop_requested()) {
            // yield
        }
    };

    std::thread t(run);
    ss.request_stop();
    t.join();

    CHECK(counter.load(std::memory_order_acquire) >= 1);
}
