// Tests for <string_view> and char_traits.
// Each free function is named test_string_view_<case> or test_char_traits_<case>.
// Uses CHECK (runtime, traps on failure) and static_assert (compile-time).
// No progress printing; no main() (generated by tools/gen_main.sh).
#include <string_view>
#include "../test/test.h"

using namespace std;

//===----------------------------------------------------------------------===//
// char_traits<char>
//===----------------------------------------------------------------------===//

void test_char_traits_char_eq_lt() {
    static_assert(char_traits<char>::eq('a', 'a'));
    static_assert(!char_traits<char>::eq('a', 'b'));
    static_assert(char_traits<char>::lt('a', 'b'));
    static_assert(!char_traits<char>::lt('b', 'a'));
    // Signed char sign-extension: 0x80 vs 0x01 — unsigned semantics
    static_assert(char_traits<char>::lt('\x01', '\x80'));
    static_assert(!char_traits<char>::lt('\x80', '\x01'));
}

void test_char_traits_char_compare() {
    constexpr const char* a = "hello";
    constexpr const char* b = "hello";
    constexpr const char* c = "hellp";
    static_assert(char_traits<char>::compare(a, b, 5) == 0);
    static_assert(char_traits<char>::compare(a, c, 5) < 0);
    static_assert(char_traits<char>::compare(c, a, 5) > 0);
    static_assert(char_traits<char>::compare(a, b, 0) == 0);
}

void test_char_traits_char_length() {
    static_assert(char_traits<char>::length("") == 0);
    static_assert(char_traits<char>::length("hello") == 5);
    static_assert(char_traits<char>::length("hi there") == 8);
}

void test_char_traits_char_find() {
    constexpr const char* s = "hello";
    static_assert(char_traits<char>::find(s, 5, 'l') == s + 2);
    static_assert(char_traits<char>::find(s, 5, 'z') == nullptr);
    static_assert(char_traits<char>::find(s, 5, 'h') == s);
    static_assert(char_traits<char>::find(s, 5, 'o') == s + 4);
    static_assert(char_traits<char>::find(s, 0, 'h') == nullptr);
}

void test_char_traits_char_assign() {
    char c1 = 'a';
    char_traits<char>::assign(c1, 'z');
    CHECK(c1 == 'z');

    char buf[5] = {};
    char_traits<char>::assign(buf, 5, 'x');
    for (int i = 0; i < 5; ++i)
        CHECK(buf[i] == 'x');
}

void test_char_traits_char_copy_move() {
    char src[] = "hello";
    char dst[6] = {};
    char_traits<char>::copy(dst, src, 5);
    CHECK(char_traits<char>::compare(dst, src, 5) == 0);

    // move: overlapping forward
    char buf[] = "abcde";
    char_traits<char>::move(buf + 1, buf, 4);
    CHECK(buf[0] == 'a');
    CHECK(buf[1] == 'a');
    CHECK(buf[2] == 'b');
}

void test_char_traits_char_eof() {
    static_assert(char_traits<char>::eof() == EOF);
    auto e = char_traits<char>::eof();
    CHECK(!char_traits<char>::eq_int_type(char_traits<char>::not_eof(e), e));
    auto c = char_traits<char>::to_int_type('A');
    CHECK(char_traits<char>::not_eof(c) == c);
}

void test_char_traits_char_to_types() {
    constexpr auto i = char_traits<char>::to_int_type('\xFF');
    static_assert(i == 255); // unsigned char semantics
    constexpr auto ch = char_traits<char>::to_char_type(65);
    static_assert(ch == 'A');
}

//===----------------------------------------------------------------------===//
// char_traits<wchar_t>
//===----------------------------------------------------------------------===//

void test_char_traits_wchar_basic() {
    static_assert(char_traits<wchar_t>::eq(L'a', L'a'));
    static_assert(!char_traits<wchar_t>::eq(L'a', L'b'));
    static_assert(char_traits<wchar_t>::lt(L'a', L'b'));
    static_assert(char_traits<wchar_t>::length(L"hello") == 5);
    static_assert(char_traits<wchar_t>::length(L"") == 0);

    constexpr const wchar_t* s = L"hello";
    static_assert(char_traits<wchar_t>::compare(s, L"hello", 5) == 0);
    static_assert(char_traits<wchar_t>::compare(s, L"hellp", 5) < 0);
    static_assert(char_traits<wchar_t>::find(s, 5, L'l') == s + 2);
    static_assert(char_traits<wchar_t>::find(s, 5, L'z') == nullptr);
}

//===----------------------------------------------------------------------===//
// char_traits<char8_t>
//===----------------------------------------------------------------------===//

void test_char_traits_char8_basic() {
    static_assert(char_traits<char8_t>::eq(u8'a', u8'a'));
    static_assert(!char_traits<char8_t>::eq(u8'a', u8'b'));
    static_assert(char_traits<char8_t>::length(u8"hello") == 5);

    constexpr const char8_t* s = u8"hello";
    static_assert(char_traits<char8_t>::compare(s, u8"hello", 5) == 0);
    static_assert(char_traits<char8_t>::compare(s, u8"hellp", 5) < 0);
    static_assert(char_traits<char8_t>::find(s, 5, u8'l') == s + 2);
    static_assert(char_traits<char8_t>::find(s, 5, u8'z') == nullptr);
}

//===----------------------------------------------------------------------===//
// char_traits<char16_t>
//===----------------------------------------------------------------------===//

void test_char_traits_char16_basic() {
    static_assert(char_traits<char16_t>::eq(u'a', u'a'));
    static_assert(!char_traits<char16_t>::eq(u'a', u'b'));
    static_assert(char_traits<char16_t>::lt(u'a', u'b'));
    static_assert(char_traits<char16_t>::length(u"hello") == 5);

    constexpr const char16_t* s = u"hello";
    static_assert(char_traits<char16_t>::compare(s, u"hello", 5) == 0);
    static_assert(char_traits<char16_t>::find(s, 5, u'l') == s + 2);
    static_assert(char_traits<char16_t>::find(s, 5, u'z') == nullptr);
}

//===----------------------------------------------------------------------===//
// char_traits<char32_t>
//===----------------------------------------------------------------------===//

void test_char_traits_char32_basic() {
    static_assert(char_traits<char32_t>::eq(U'a', U'a'));
    static_assert(!char_traits<char32_t>::eq(U'a', U'b'));
    static_assert(char_traits<char32_t>::lt(U'a', U'b'));
    static_assert(char_traits<char32_t>::length(U"hello") == 5);

    constexpr const char32_t* s = U"hello";
    static_assert(char_traits<char32_t>::compare(s, U"hello", 5) == 0);
    static_assert(char_traits<char32_t>::find(s, 5, U'l') == s + 2);
    static_assert(char_traits<char32_t>::find(s, 5, U'z') == nullptr);
}

//===----------------------------------------------------------------------===//
// basic_string_view — construction
//===----------------------------------------------------------------------===//

void test_string_view_construct() {
    // Default
    constexpr string_view sv0;
    static_assert(sv0.empty());
    static_assert(sv0.size() == 0);
    static_assert(sv0.data() == nullptr);

    // From pointer
    constexpr string_view sv1("hello");
    static_assert(sv1.size() == 5);
    static_assert(!sv1.empty());

    // From pointer + length
    constexpr string_view sv2("hello world", 5);
    static_assert(sv2.size() == 5);

    // Copy
    constexpr string_view sv3 = sv1;
    static_assert(sv3.size() == 5);

    // Literal suffix
    using namespace std::literals::string_view_literals;
    auto sv4 = "hello"sv;
    CHECK(sv4.size() == 5);
    CHECK(sv4[0] == 'h');
}

void test_string_view_construct_wide() {
    using namespace std::literals::string_view_literals;
    auto wsv = L"wide"sv;
    CHECK(wsv.size() == 4);

    auto u8sv = u8"utf8"sv;
    CHECK(u8sv.size() == 4);

    auto u16sv = u"utf16"sv;
    CHECK(u16sv.size() == 5);

    auto u32sv = U"utf32"sv;
    CHECK(u32sv.size() == 5);
}

//===----------------------------------------------------------------------===//
// basic_string_view — capacity
//===----------------------------------------------------------------------===//

void test_string_view_capacity() {
    constexpr string_view sv("hello");
    static_assert(sv.size() == 5);
    static_assert(sv.length() == 5);
    static_assert(!sv.empty());
    static_assert(sv.max_size() > 0);

    constexpr string_view empty_sv;
    static_assert(empty_sv.empty());
    static_assert(empty_sv.size() == 0);
}

//===----------------------------------------------------------------------===//
// basic_string_view — element access
//===----------------------------------------------------------------------===//

void test_string_view_access() {
    constexpr string_view sv("hello");
    static_assert(sv[0] == 'h');
    static_assert(sv[4] == 'o');
    static_assert(sv.front() == 'h');
    static_assert(sv.back() == 'o');
    static_assert(sv.data()[1] == 'e');

    // at() — in-range
    CHECK(sv.at(0) == 'h');
    CHECK(sv.at(4) == 'o');
}

//===----------------------------------------------------------------------===//
// basic_string_view — iterators
//===----------------------------------------------------------------------===//

void test_string_view_iterators() {
    const char src[] = "hello";
    string_view sv(src);

    // Forward iteration
    int i = 0;
    for (auto it = sv.begin(); it != sv.end(); ++it, ++i)
        CHECK(*it == src[i]);
    CHECK(i == 5);

    // Reverse iteration
    string_view::size_type j = 5;
    for (auto it = sv.rbegin(); it != sv.rend(); ++it) {
        --j;
        CHECK(*it == src[j]);
    }
    CHECK(j == 0);
}

//===----------------------------------------------------------------------===//
// basic_string_view — modifiers
//===----------------------------------------------------------------------===//

void test_string_view_remove_prefix_suffix() {
    string_view sv("hello world");
    sv.remove_prefix(6);
    CHECK(sv.size() == 5);
    CHECK(sv[0] == 'w');

    sv.remove_suffix(1);
    CHECK(sv.size() == 4);
    CHECK(sv[3] == 'l');
}

void test_string_view_swap() {
    string_view a("hello");
    string_view b("world!");
    a.swap(b);
    CHECK(a.size() == 6);
    CHECK(a[0] == 'w');
    CHECK(b.size() == 5);
    CHECK(b[0] == 'h');
}

void test_string_view_copy() {
    string_view sv("hello world");
    char buf[6] = {};
    auto n = sv.copy(buf, 5, 6);
    CHECK(n == 5);
    CHECK(buf[0] == 'w');
    CHECK(buf[4] == 'd');
}

//===----------------------------------------------------------------------===//
// basic_string_view — substr
//===----------------------------------------------------------------------===//

void test_string_view_substr() {
    constexpr string_view sv("hello world");
    constexpr auto sub1 = sv.substr(0, 5);
    static_assert(sub1.size() == 5);
    static_assert(sub1[0] == 'h');
    static_assert(sub1[4] == 'o');

    constexpr auto sub2 = sv.substr(6);
    static_assert(sub2.size() == 5);
    static_assert(sub2[0] == 'w');

    // npos: takes everything from pos
    constexpr auto sub3 = sv.substr(0, string_view::npos);
    static_assert(sub3.size() == 11);

    // n > remaining: clamped
    constexpr auto sub4 = sv.substr(8, 100);
    static_assert(sub4.size() == 3); // "rld"

    // pos == size: empty view
    constexpr auto sub5 = sv.substr(11);
    static_assert(sub5.empty());
}

//===----------------------------------------------------------------------===//
// basic_string_view — compare
//===----------------------------------------------------------------------===//

void test_string_view_compare() {
    constexpr string_view a("hello");
    constexpr string_view b("hello");
    constexpr string_view c("world");
    constexpr string_view d("hell");

    static_assert(a.compare(b) == 0);
    static_assert(a.compare(c) < 0);
    static_assert(c.compare(a) > 0);
    static_assert(a.compare(d) > 0); // "hello" > "hell" (longer)
    static_assert(d.compare(a) < 0);

    // compare(pos, n, sv)
    static_assert(a.compare(0, 4, d) == 0); // "hell" == "hell"

    // compare(const char*)
    static_assert(a.compare("hello") == 0);
    static_assert(a.compare("world") < 0);
}

//===----------------------------------------------------------------------===//
// basic_string_view — starts_with / ends_with / contains
//===----------------------------------------------------------------------===//

void test_string_view_starts_ends_contains() {
    constexpr string_view sv("hello world");

    static_assert(sv.starts_with("hello"));
    static_assert(!sv.starts_with("world"));
    static_assert(sv.starts_with('h'));
    static_assert(!sv.starts_with('w'));
    static_assert(sv.starts_with(string_view("hello")));

    static_assert(sv.ends_with("world"));
    static_assert(!sv.ends_with("hello"));
    static_assert(sv.ends_with('d'));
    static_assert(!sv.ends_with('h'));
    static_assert(sv.ends_with(string_view("world")));

    static_assert(sv.contains("lo wo"));
    static_assert(!sv.contains("xyz"));
    static_assert(sv.contains(' '));
    static_assert(!sv.contains('z'));
    static_assert(sv.contains("hello world")); // exact match
}

//===----------------------------------------------------------------------===//
// basic_string_view — find
//===----------------------------------------------------------------------===//

void test_string_view_find() {
    constexpr string_view sv("hello world hello");
    constexpr auto npos = string_view::npos;

    static_assert(sv.find('h') == 0);
    static_assert(sv.find('o') == 4);
    static_assert(sv.find('z') == npos);
    static_assert(sv.find('h', 1) == 12);

    static_assert(sv.find("hello") == 0);
    static_assert(sv.find("hello", 1) == 12);
    static_assert(sv.find("xyz") == npos);

    static_assert(sv.find("ell", 0, 3) == 1);
    static_assert(sv.find("ell", 5, 3) == 13);

    static_assert(sv.find(string_view("world")) == 6);
    static_assert(sv.find(string_view("xyz")) == npos);
}

//===----------------------------------------------------------------------===//
// basic_string_view — rfind
//===----------------------------------------------------------------------===//

void test_string_view_rfind() {
    constexpr string_view sv("hello world hello");
    constexpr auto npos = string_view::npos;

    static_assert(sv.rfind('h') == 12);
    static_assert(sv.rfind('h', 11) == 0);
    static_assert(sv.rfind('z') == npos);

    static_assert(sv.rfind("hello") == 12);
    static_assert(sv.rfind("hello", 11) == 0);
    static_assert(sv.rfind("xyz") == npos);

    static_assert(sv.rfind(string_view("hello")) == 12);
}

//===----------------------------------------------------------------------===//
// basic_string_view — find_first_of / find_last_of
//===----------------------------------------------------------------------===//

void test_string_view_find_first_last_of() {
    constexpr string_view sv("hello world");
    constexpr auto npos = string_view::npos;

    static_assert(sv.find_first_of("aeiou") == 1); // 'e'
    static_assert(sv.find_first_of("xyz") == npos);
    static_assert(sv.find_first_of('l') == 2);
    static_assert(sv.find_first_of(string_view("lr")) == 2); // 'l'

    static_assert(sv.find_last_of("aeiou") == 7); // 'o' in "world"
    static_assert(sv.find_last_of("xyz") == npos);
    static_assert(sv.find_last_of('l') == 9);
    static_assert(sv.find_last_of(string_view("ld")) == 10); // 'd'
}

//===----------------------------------------------------------------------===//
// basic_string_view — find_first_not_of / find_last_not_of
//===----------------------------------------------------------------------===//

void test_string_view_find_not_of() {
    constexpr string_view sv("hello world");
    constexpr auto npos = string_view::npos;

    static_assert(sv.find_first_not_of("helo") == 5); // ' '
    static_assert(sv.find_first_not_of("hello world") == npos);
    static_assert(sv.find_first_not_of('h') == 1);
    static_assert(sv.find_first_not_of(string_view("helo ")) == 6); // 'w'

    static_assert(sv.find_last_not_of("orld") == 6); // 'w'
    static_assert(sv.find_last_not_of("hello world") == npos);
    static_assert(sv.find_last_not_of('d') == 9); // 'l'
    static_assert(sv.find_last_not_of(string_view("world")) == 5); // ' '
}

//===----------------------------------------------------------------------===//
// basic_string_view — comparison operators
//===----------------------------------------------------------------------===//

void test_string_view_operators() {
    constexpr string_view a("apple");
    constexpr string_view b("banana");
    constexpr string_view c("apple");

    static_assert(a == c);
    static_assert(!(a == b));
    static_assert(a != b);
    static_assert(!(a != c));

    // Spaceship / ordering
    static_assert((a <=> c) == strong_ordering::equal);
    static_assert((a <=> b) == strong_ordering::less);
    static_assert((b <=> a) == strong_ordering::greater);
}

//===----------------------------------------------------------------------===//
// mixed CharT specialisations — basic smoke tests
//===----------------------------------------------------------------------===//

void test_string_view_wstring_view() {
    wstring_view sv(L"hello world");
    CHECK(sv.size() == 11);
    CHECK(sv.find(L"world") == 6);
    CHECK(sv.starts_with(L"hello"));
    CHECK(sv.ends_with(L"world"));
}

void test_string_view_u16string_view() {
    u16string_view sv(u"hello");
    CHECK(sv.size() == 5);
    CHECK(sv.find(u'l') == 2);
    static_assert(u16string_view(u"hello").compare(u"hello") == 0);
}

void test_string_view_u32string_view() {
    u32string_view sv(U"hello");
    CHECK(sv.size() == 5);
    CHECK(sv.rfind(U'l') == 3);
}

//===----------------------------------------------------------------------===//
// hash<basic_string_view<...>> specialisations
//===----------------------------------------------------------------------===//

void test_string_view_hash() {
    // Equal string_views must hash equal.
    string_view a("hello");
    string_view b("hello");
    CHECK(hash<string_view>{}(a) == hash<string_view>{}(b));

    // Different content should (very likely) produce different hashes.
    string_view c("world");
    // Not a hard guarantee, but true for any reasonable hash function.
    CHECK(hash<string_view>{}(a) != hash<string_view>{}(c));

    // Empty string_views hash equal.
    string_view empty1;
    string_view empty2;
    CHECK(hash<string_view>{}(empty1) == hash<string_view>{}(empty2));

    // wstring_view: equal views hash equal.
    wstring_view wa(L"wide");
    wstring_view wb(L"wide");
    CHECK(hash<wstring_view>{}(wa) == hash<wstring_view>{}(wb));

    // u16string_view: equal views hash equal.
    u16string_view ua(u"u16");
    u16string_view ub(u"u16");
    CHECK(hash<u16string_view>{}(ua) == hash<u16string_view>{}(ub));

    // u32string_view: equal views hash equal.
    u32string_view u32a(U"u32");
    u32string_view u32b(U"u32");
    CHECK(hash<u32string_view>{}(u32a) == hash<u32string_view>{}(u32b));

    // u8string_view: equal views hash equal.
    u8string_view u8a(u8"u8");
    u8string_view u8b(u8"u8");
    CHECK(hash<u8string_view>{}(u8a) == hash<u8string_view>{}(u8b));

    // static_assert: hash<string_view> is callable.
    static_assert(requires { hash<string_view>{}(string_view{"x"}); });
}
