// test/thread.cpp — tests for <thread>
// Each test_* function is a no-arg free function using CHECK / static_assert.
// main() is auto-generated by tools/gen_main.sh.
#include <thread>
#include <atomic>
#include "test.h"

// ============================================================
// test_thread_basic
// ============================================================
void test_thread_basic() {
    // A thread runs a function that increments a counter, then join.
    std::atomic<int> counter{0};
    std::thread t([&counter]() {
        counter.fetch_add(1, std::memory_order_relaxed);
    });
    t.join();
    CHECK(counter.load() == 1);
}

// ============================================================
// test_thread_id_not_equal_default
// ============================================================
void test_thread_id_not_equal_default() {
    // this_thread::get_id() must not equal the default (null) id
    std::thread::id def;
    std::thread::id cur = std::this_thread::get_id();
    CHECK(!(def == cur));
}

// ============================================================
// test_thread_joinable
// ============================================================
void test_thread_joinable() {
    std::thread t([](){});
    CHECK(t.joinable());
    t.join();
    CHECK(!t.joinable());
}

// ============================================================
// test_thread_get_id
// ============================================================
void test_thread_get_id() {
    std::atomic<std::thread::id> child_id;
    std::thread t([&child_id]() {
        child_id.store(std::this_thread::get_id(), std::memory_order_release);
    });
    std::thread::id main_id = std::this_thread::get_id();
    t.join();

    std::thread::id cid = child_id.load(std::memory_order_acquire);
    // The child's id should differ from the main thread's id
    CHECK(!(cid == main_id));
    // The child's id should not equal the default id
    CHECK(!(cid == std::thread::id{}));
}

// ============================================================
// test_thread_hardware_concurrency
// ============================================================
void test_thread_hardware_concurrency() {
    // hardware_concurrency returns 0 or a positive number
    unsigned n = std::thread::hardware_concurrency();
    // We can't assert > 0 portably (spec allows 0), but check it doesn't crash.
    (void)n;
    CHECK(true);
}

// ============================================================
// test_thread_swap
// ============================================================
void test_thread_swap() {
    std::atomic<int> a{0}, b{0};
    std::thread t1([&a]() { a.store(1, std::memory_order_relaxed); });
    std::thread t2([&b]() { b.store(2, std::memory_order_relaxed); });
    std::swap(t1, t2);
    t1.join();
    t2.join();
    CHECK(a.load() == 1);
    CHECK(b.load() == 2);
}

// ============================================================
// test_thread_yield
// ============================================================
void test_thread_yield() {
    std::this_thread::yield();  // must not crash
    CHECK(true);
}

// ============================================================
// test_thread_sleep_for
// ============================================================
void test_thread_sleep_for() {
    // sleep for a very short duration — just check it doesn't crash/hang
    std::this_thread::sleep_for(std::chrono::nanoseconds(1));
    CHECK(true);
}

// ============================================================
// test_thread_jthread_stop
// ============================================================
void test_thread_jthread_stop() {
    // jthread: callable observes stop_requested after destructor calls request_stop
    std::atomic<bool> saw_stop{false};

    {
        std::jthread jt([&saw_stop](std::stop_token st) {
            while (!st.stop_requested()) {
                // spin
            }
            saw_stop.store(true, std::memory_order_release);
        });
        // jt destructor calls request_stop() then join()
    }

    CHECK(saw_stop.load(std::memory_order_acquire));
}

// ============================================================
// test_thread_jthread_auto_join
// ============================================================
void test_thread_jthread_auto_join() {
    std::atomic<int> counter{0};
    {
        std::jthread jt([&counter](std::stop_token /*st*/) {
            counter.fetch_add(1, std::memory_order_relaxed);
        });
        // destructor auto-joins
    }
    CHECK(counter.load() == 1);
}

// ============================================================
// test_thread_jthread_get_stop_token
// ============================================================
void test_thread_jthread_get_stop_token() {
    std::jthread jt([](std::stop_token /*st*/) {});
    std::stop_token st = jt.get_stop_token();
    CHECK(st.stop_possible());
    CHECK(!st.stop_requested());
    jt.request_stop();
    CHECK(st.stop_requested());
    // destructor will join
}
