// test/tuple.cpp — tests for <tuple>
// Each test_* function uses CHECK(...) and/or static_assert.
// No main(); it is generated by tools/gen_main.sh.
#include <tuple>
#include "test.h"

// ---- tuple_size / tuple_element ----

void test_tuple_size() {
    static_assert(std::tuple_size_v<std::tuple<>> == 0);
    static_assert(std::tuple_size_v<std::tuple<int>> == 1);
    static_assert(std::tuple_size_v<std::tuple<int, double, char>> == 3);
    static_assert(std::tuple_size_v<const std::tuple<int, double>> == 2);
    static_assert(std::tuple_size_v<volatile std::tuple<int>> == 1);
}

void test_tuple_element() {
    static_assert(std::is_same_v<std::tuple_element_t<0, std::tuple<int, double>>, int>);
    static_assert(std::is_same_v<std::tuple_element_t<1, std::tuple<int, double>>, double>);
    static_assert(std::is_same_v<std::tuple_element_t<0, std::tuple<int&>>, int&>);
    static_assert(std::is_same_v<std::tuple_element_t<0, const std::tuple<int>>, const int>);
    static_assert(std::is_same_v<std::tuple_element_t<2, std::tuple<char, float, long>>, long>);
}

// ---- basic construction ----

void test_tuple_default_construct() {
    std::tuple<> empty;
    (void)empty;

    std::tuple<int> t1;
    CHECK(std::get<0>(t1) == 0);

    std::tuple<int, double> t2;
    CHECK(std::get<0>(t2) == 0);
    CHECK(std::get<1>(t2) == 0.0);
}

void test_tuple_value_construct() {
    std::tuple<int, double, char> t(1, 2.5, 'a');
    CHECK(std::get<0>(t) == 1);
    CHECK(std::get<1>(t) == 2.5);
    CHECK(std::get<2>(t) == 'a');
}

void test_tuple_copy_construct() {
    std::tuple<int, double> a(42, 3.14);
    std::tuple<int, double> b(a);
    CHECK(std::get<0>(b) == 42);
    CHECK(std::get<1>(b) == 3.14);
}

void test_tuple_move_construct() {
    std::tuple<int, double> a(10, 2.0);
    std::tuple<int, double> b(std::move(a));
    CHECK(std::get<0>(b) == 10);
    CHECK(std::get<1>(b) == 2.0);
}

void test_tuple_converting_construct() {
    // From a different tuple type
    std::tuple<long, double> a(std::tuple<int, float>(7, 1.5f));
    CHECK(std::get<0>(a) == 7L);

    // From pair
    std::pair<int, double> p(3, 4.5);
    std::tuple<int, double> t(p);
    CHECK(std::get<0>(t) == 3);
    CHECK(std::get<1>(t) == 4.5);

    // From pair (move)
    std::tuple<int, double> t2(std::pair<int, double>(5, 6.0));
    CHECK(std::get<0>(t2) == 5);
    CHECK(std::get<1>(t2) == 6.0);
}

// ---- get<I> ----

void test_tuple_get_index() {
    std::tuple<int, double, char> t(1, 2.0, 'z');
    CHECK(std::get<0>(t) == 1);
    CHECK(std::get<1>(t) == 2.0);
    CHECK(std::get<2>(t) == 'z');

    // lvalue get returns reference
    std::get<0>(t) = 99;
    CHECK(std::get<0>(t) == 99);

    // const get
    const auto& ct = t;
    CHECK(std::get<0>(ct) == 99);

    // rvalue get
    int v = std::get<0>(std::move(t));
    CHECK(v == 99);
}

// ---- get<T> ----

void test_tuple_get_type() {
    std::tuple<int, double, char> t(1, 2.0, 'a');
    CHECK(std::get<int>(t)    == 1);
    CHECK(std::get<double>(t) == 2.0);
    CHECK(std::get<char>(t)   == 'a');

    std::get<int>(t) = 42;
    CHECK(std::get<int>(t) == 42);
}

// ---- assignment ----

void test_tuple_assign() {
    std::tuple<int, double> a(1, 2.0);
    std::tuple<int, double> b;
    b = a;
    CHECK(std::get<0>(b) == 1);
    CHECK(std::get<1>(b) == 2.0);

    std::tuple<int, double> c;
    c = std::move(a);
    CHECK(std::get<0>(c) == 1);

    // Converting assignment
    std::tuple<long, double> d;
    d = std::tuple<int, float>(3, 4.0f);
    CHECK(std::get<0>(d) == 3L);

    // From pair
    std::tuple<int, double> e;
    e = std::pair<int, double>(7, 8.0);
    CHECK(std::get<0>(e) == 7);
    CHECK(std::get<1>(e) == 8.0);
}

// ---- swap ----

void test_tuple_swap() {
    std::tuple<int, double> a(1, 2.0), b(3, 4.0);
    a.swap(b);
    CHECK(std::get<0>(a) == 3);
    CHECK(std::get<1>(a) == 4.0);
    CHECK(std::get<0>(b) == 1);
    CHECK(std::get<1>(b) == 2.0);

    std::swap(a, b);
    CHECK(std::get<0>(a) == 1);
}

// ---- make_tuple ----

void test_make_tuple() {
    auto t = std::make_tuple(1, 2.5, 'a');
    static_assert(std::is_same_v<decltype(t), std::tuple<int, double, char>>);
    CHECK(std::get<0>(t) == 1);
    CHECK(std::get<1>(t) == 2.5);
    CHECK(std::get<2>(t) == 'a');

    // make_tuple unwraps decay (basic case: no reference_wrapper needed)
    static_assert(std::is_same_v<std::tuple_element_t<0, decltype(t)>, int>);
}

// ---- tie ----

void test_tie() {
    int a = 0; double b = 0.0;
    std::tie(a, b) = std::make_tuple(5, 3.14);
    CHECK(a == 5);
    CHECK(b == 3.14);

    // ignore
    int c = 0;
    std::tie(c, std::ignore) = std::make_tuple(7, 99.9);
    CHECK(c == 7);
}

// ---- forward_as_tuple ----

void test_forward_as_tuple() {
    int x = 1;
    auto t = std::forward_as_tuple(x, 2, 3.0);
    static_assert(std::is_same_v<decltype(t), std::tuple<int&, int&&, double&&>>);
    CHECK(std::get<0>(t) == 1);
    CHECK(std::get<1>(t) == 2);
}

// ---- tuple_cat ----

void test_tuple_cat() {
    auto a = std::make_tuple(1, 2);
    auto b = std::make_tuple(3.0, 'x');
    auto c = std::tuple_cat(a, b);
    static_assert(std::is_same_v<decltype(c), std::tuple<int, int, double, char>>);
    CHECK(std::get<0>(c) == 1);
    CHECK(std::get<1>(c) == 2);
    CHECK(std::get<2>(c) == 3.0);
    CHECK(std::get<3>(c) == 'x');

    // Empty
    auto e = std::tuple_cat();
    static_assert(std::is_same_v<decltype(e), std::tuple<>>);

    // 3-way
    auto d = std::tuple_cat(std::make_tuple(1), std::make_tuple(2), std::make_tuple(3));
    CHECK(std::get<2>(d) == 3);

    // With pair
    auto p = std::pair<int, double>(10, 20.0);
    auto tp = std::tuple_cat(std::make_tuple('a'), p);
    CHECK(std::get<0>(tp) == 'a');
    CHECK(std::get<1>(tp) == 10);
    CHECK(std::get<2>(tp) == 20.0);
}

// ---- relational operators ----

void test_tuple_compare() {
    auto a = std::make_tuple(1, 2);
    auto b = std::make_tuple(1, 2);
    auto c = std::make_tuple(1, 3);
    auto d = std::make_tuple(2, 0);

    CHECK(a == b);
    CHECK(!(a == c));
    CHECK((a <=> b) == 0);
    CHECK((a <=> c) < 0);
    CHECK((c <=> a) > 0);
    CHECK((a <=> d) < 0);
}

// ---- apply ----

void test_apply() {
    auto add = [](int a, int b) { return a + b; };
    auto t = std::make_tuple(3, 4);
    CHECK(std::apply(add, t) == 7);

    // Member function pointer
    struct Foo { int val; int get() const { return val; } };
    Foo foo{42};
    auto t2 = std::make_tuple(&foo);
    CHECK(std::apply(&Foo::get, t2) == 42);
}

// ---- make_from_tuple ----

void test_make_from_tuple() {
    struct Point { int x, y; Point(int a, int b) : x(a), y(b) {} };
    auto t = std::make_tuple(3, 7);
    auto p = std::make_from_tuple<Point>(t);
    CHECK(p.x == 3);
    CHECK(p.y == 7);
}

// ---- structured bindings ----

void test_structured_bindings() {
    auto t = std::make_tuple(1, 2.5, 'z');
    auto [a, b, c] = t;
    CHECK(a == 1);
    CHECK(b == 2.5);
    CHECK(c == 'z');

    auto& [ra, rb, rc] = t;
    ra = 99;
    CHECK(std::get<0>(t) == 99);
}

// ---- reference elements ----

void test_tuple_references() {
    int x = 10, y = 20;
    std::tuple<int&, int&> t(x, y);
    std::get<0>(t) = 42;
    CHECK(x == 42);

    // forward_as_tuple then forward
    auto fat = std::forward_as_tuple(x, y);
    std::get<0>(fat) = 100;
    CHECK(x == 100);
}

// ---- EBO: empty types ----

void test_tuple_ebo() {
    struct Empty {};
    // tuple<Empty, int> should be no larger than tuple<int> due to EBO
    // (not strictly mandated but nice to verify it compiles)
    std::tuple<Empty, int> t(Empty{}, 5);
    CHECK(std::get<1>(t) == 5);
}

// ---- pair specialisations of tuple_size / tuple_element ----

void test_pair_tuple_interface() {
    static_assert(std::tuple_size_v<std::pair<int, double>> == 2);
    static_assert(std::is_same_v<std::tuple_element_t<0, std::pair<int, double>>, int>);
    static_assert(std::is_same_v<std::tuple_element_t<1, std::pair<int, double>>, double>);

    std::pair<int, double> p(3, 4.5);
    CHECK(std::get<0>(p) == 3);
    CHECK(std::get<1>(p) == 4.5);
    CHECK(std::get<int>(p) == 3);
    CHECK(std::get<double>(p) == 4.5);
}

// ---- piecewise pair construction (uses <tuple>) ----

void test_pair_piecewise() {
    struct S {
        int a, b;
        S(int x, int y) : a(x), b(y) {}
    };
    auto p = std::pair<S, S>(
        std::piecewise_construct,
        std::forward_as_tuple(1, 2),
        std::forward_as_tuple(3, 4));
    CHECK(p.first.a  == 1);
    CHECK(p.first.b  == 2);
    CHECK(p.second.a == 3);
    CHECK(p.second.b == 4);
}

// ---- tuple with move-only types ----

void test_tuple_move_only() {
    struct MO {
        int v;
        MO(int x) : v(x) {}
        MO(MO&&) = default;
        MO(const MO&) = delete;
        MO& operator=(MO&&) = default;
        MO& operator=(const MO&) = delete;
    };

    std::tuple<MO> t(MO{7});
    CHECK(std::get<0>(t).v == 7);

    std::tuple<MO> t2(std::move(t));
    CHECK(std::get<0>(t2).v == 7);
}
