// AST-transferred from libc++ by tools/transfer.py (slug=re_re_iter_re_regiter_re_regiter_comp_tested_elsewhere).
// main -> test_re_re_iter_re_regiter_re_regiter_comp_tested_elsewhere; file-scope helpers isolated in anon namespace.
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// <regex>

// class regex_iterator<BidirectionalIterator, charT, traits>

// bool operator==(const regex_iterator& right) const;
// bool operator!=(const regex_iterator& right) const; // generated by the compiler in C++20

void test_re_re_iter_re_regiter_re_regiter_comp_tested_elsewhere()
{

  return;
}
