#!/usr/bin/env python3
"""Emit build/transfer.ninja + the root build/build.ninja: the libc++ ->
libcis test transfer as a real, incremental dependency graph.

Graph:
    tools/transfer.py, tools/transfer_batch.py  (implicit deps of the edges)
        build/transfer.pch                            (rule pch)
        build/recs/<dir>.dirrec.json : <dir srcs> | py pch   (rule xferdir)
            ... which writes build/recs/<rel>.rec.json per file
        test/std/manifest.json : <all dirrecs>        (rule aggregate, rspfile)
        build/tripwire.ok      : manifest             (rule tripwire)
        build/groups.ninja     : manifest, tripwire   (generator, then subninja)

One edge per source DIRECTORY (the granularity the group TUs consume): one
Python+libclang+PCH startup serves ~7 files instead of 1.  Crash isolation
keeps per-file attribution: the batch child writes each rec as it goes, and on
a crash/hang the parent redoes the directory's missing recs per-file under
individual timeouts (transfer_batch.py).

The tripwire (tools/tripwire.py) asserts known fixtures (adaptation excised
RTTI sites, entries recorded, suite-level run-test counts) so a regression
that degrades the AST stage to a copy FAILS the build instead of producing
green recs of unmodified files.

Usage: tools/gen_transfer.py [SUBTREE ...]   (default: every std/ subtree)
"""
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import transfer as T  # noqa: E402

ROOT = T.ROOT
REC_DIR = os.path.join(ROOT, "build", "recs")


def copy_support(subtrees):
    """Static file copies (support harness + each subtree's sibling .h) done at
    generation time -- they are inputs, not transformed artifacts."""
    if not os.path.isdir(T.DST_SUPPORT):
        shutil.copytree(T.SRC_SUPPORT, T.DST_SUPPORT)
    for sub in subtrees:
        T.copy_sibling_headers(sub)


def main():
    subtrees = sys.argv[1:] or sorted(
        d for d in os.listdir(T.SRC_STD) if os.path.isdir(os.path.join(T.SRC_STD, d)))
    os.makedirs(T.DST_ROOT, exist_ok=True)
    copy_support(subtrees)

    tooldir = os.path.relpath(os.path.dirname(os.path.abspath(__file__)), ROOT)
    py = f"{tooldir}/transfer.py"
    pyb = f"{tooldir}/transfer_batch.py"
    pch = os.path.relpath(T.PCH_PATH, ROOT)
    L = [
        "ninja_required_version = 1.10",
        "",
        "rule pch",
        f"  command = python3 {py} --build-pch",
        "  description = PCH $out",
        "rule xferdir",
        f"  command = python3 {pyb} --edge-dir $out $in",
        "  description = XFER $dir",
        # 1100+ dirrec paths can exceed ARG_MAX; use a response file
        "rule aggregate",
        f"  command = python3 {py} --aggregate $out @$out.rsp",
        "  rspfile = $out.rsp",
        "  rspfile_content = $recs",
        "  description = MANIFEST $out",
        "rule tripwire",
        f"  command = python3 {tooldir}/tripwire.py $out",
        "  description = TRIPWIRE",
        "",
        f"build {pch}: pch | {py}",
        "",
    ]
    bydir = {}
    for sub in subtrees:
        for src, rel in T.list_inputs(sub):
            bydir.setdefault(os.path.dirname(rel), []).append((src, rel))

    dirrecs, recs = [], []
    for d in sorted(bydir):
        dirrec = os.path.relpath(
            os.path.join(REC_DIR, d.replace("/", "_") + ".dirrec.json"), ROOT)
        srcs = " ".join(os.path.relpath(s, ROOT) for s, _ in bydir[d])
        L += [f"build {dirrec}: xferdir {srcs} | {py} {pyb} {pch}",
              f"  dir = {d}"]
        dirrecs.append(dirrec)
        recs += [os.path.relpath(os.path.join(REC_DIR, rel + ".rec.json"), ROOT)
                 for _, rel in bydir[d]]

    man = os.path.relpath(os.path.join(T.DST_ROOT, "manifest.json"), ROOT)
    L.append(f"build {man}: aggregate " + " $\n    ".join(dirrecs))
    L.append("  recs = " + " ".join(recs))
    L += [f"build build/tripwire.ok: tripwire {man} | {tooldir}/tripwire.py",
          "default build/tripwire.ok", ""]

    out = os.path.join(ROOT, "build", "transfer.ninja")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(L))
    print(f"{out}: {len(recs)} files in {len(dirrecs)} directory edges")

    # root graph: transfer stage + ninja-regenerated groups stage.  ninja sees
    # groups.ninja is an out-of-date output of the gengroups edge, rebuilds it
    # (after manifest + tripwire), and reloads -- the whole pipeline
    # libc++ src -> rec -> manifest -> group.cpp -> exe -> .result is ONE graph.
    groups_ninja = os.path.join(ROOT, "build", "groups.ninja")
    if not os.path.exists(groups_ninja):
        open(groups_ninja, "w").write("# generated by gen_groups.py --ninja\n")
    root = "\n".join([
        "ninja_required_version = 1.10",
        "include build/transfer.ninja",
        "",
        "rule gengroups",
        "  command = python3 tools/gen_groups.py --ninja",
        "  generator = 1",
        "  restat = 1",
        f"build build/groups.ninja: gengroups {man} | tools/gen_groups.py build/tripwire.ok",
        "subninja build/groups.ninja",
        "",
    ])
    open(os.path.join(ROOT, "build", "build.ninja"), "w").write(root)
    print("build/build.ninja: root graph (transfer + tripwire + groups)")


if __name__ == "__main__":
    main()
