#!/usr/bin/env bash
# Generate a test main() that calls every free function named test_* found in the
# given source files. The list is never maintained by hand.
#
# The generated main prints a final tally: how many test functions ran and how
# many CHECK assertions passed (libcis_checks_passed is defined in test/test.h).
#
# Usage: gen_main.sh OUTPUT FILE...
set -euo pipefail

out="$1"
shift

names="$(grep -rhoE '\bvoid[[:space:]]+test_[A-Za-z0-9_]+[[:space:]]*\(' "$@" \
         | sed -E 's/.*\b(test_[A-Za-z0-9_]+).*/\1/' | sort -u)"
count="$(printf '%s\n' "$names" | grep -c . || true)"

{
  echo "// Auto-generated by tools/gen_main.sh. Do not edit."
  echo "extern unsigned long long libcis_checks_passed;  // defined in test/test.h"
  for n in $names; do echo "void $n();"; done
  echo "int main() {"
  for n in $names; do echo "  $n();"; done
  echo "  __builtin_printf(\"libcis: ran %d test functions, %llu CHECK assertions passed\\n\","
  echo "                   $count, libcis_checks_passed);"
  echo "  return 0;"
  echo "}"
} > "$out"
