#!/usr/bin/env bash
# Generate a test main() that calls every free function named test_* found in the
# given source files. The list is never maintained by hand.
#
# Usage: gen_main.sh OUTPUT FILE...
set -euo pipefail

out="$1"
shift

names="$(grep -rhoE '\bvoid[[:space:]]+test_[A-Za-z0-9_]+[[:space:]]*\(' "$@" \
         | sed -E 's/.*\b(test_[A-Za-z0-9_]+).*/\1/' | sort -u)"

{
  echo "// Auto-generated by tools/gen_main.sh. Do not edit."
  for n in $names; do echo "void $n();"; done
  echo "int main() {"
  for n in $names; do echo "  $n();"; done
  echo "  return 0;"
  echo "}"
} > "$out"
