#!/usr/bin/env python3
"""Emit a self-contained, portable copy of the transferred test suite:
a directory that is just a Makefile + test sources + the support headers,
so that

    make STDLIB=/path/to/stdlib/include

produces ONE statically linked executable that runs the whole suite and
prints a per-test pass/fail summary.

Why a generator (and not committed files): test/std/ is generated from
libc++ and git-ignored, so the only durable form of "the tests" is the
pipeline that produces them.  This tool is the last link: it reads
test/std/manifest.json and bakes the same consolidated, namespace-isolated
form the conformance build uses (tools/gen_groups.py) into a tree that has
no dependency on this repo's ninja graph, manifest, or tools -- only a C++
compiler and a path to the standard library under test.

Shape of the output (default: package/):

    package/
      Makefile            STDLIB=... -> one static ./tests binary
      main.cpp            calls every run_group_*(), prints the summary
      harness.h           fork-per-test runner + shared counters
      groups/<key>.cpp    one consolidated TU per library feature dir,
                          bodies concatenated verbatim (each already in its
                          own namespace), #includes hoisted+deduped
      include/            every non-.cpp file under test/std (support/ harness
                          + sibling test headers + data files) on the -I path
      support.cpp         operator new/delete glue (linked as an archive so
                          count_new tests can still replace it)

The libcis build model is the default (header-only: -nostdinc++ -I$(STDLIB),
support.cpp, -static -nodefaultlibs).  Every knob is an overridable Make
variable, so the same tree builds against a vendor toolchain too -- which is
exactly what makes these tests a useful cross-check (they were adapted to
compile against both vendor libc++/libstdc++ and libcis).

Usage:
    python3 tools/gen_package.py [--out DIR] [--apply-exclusions]

  --out DIR           output directory (default: package)
  --apply-exclusions  drop tools/exclusions.json tests from the package
                      (the gcc-10-limit / target-impossible set).  Default
                      is to include every transferred run-test, matching the
                      consolidated conformance build.
"""
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_groups as G  # noqa: E402  (chdir(ROOT) + MANIFEST/grouping/helpers)

ROOT = G.ROOT
MANIFEST = G.MANIFEST
SUPPORT_CPP = "src/support.cpp"
OVR = os.path.join(ROOT, "tools", "test_overrides")

HARNESS_H = """\
// fork-per-test harness, shared by every group TU and main.cpp.
// One inline counter pair (C++17) aggregates across all translation units;
// each test runs in its own child so an abort/crash/throw-under-fno-exceptions
// is contained and attributed instead of taking down the whole binary.
#pragma once
#include <cstdio>
#include <unistd.h>
#include <sys/wait.h>
namespace cis_harness {
inline int total = 0;
inline int fails = 0;
template <class F>
inline void run(F f, const char* name) {
  ++total;
  ::pid_t p = ::fork();
  if (p == 0) { ::alarm(30); ::_exit(f()); }   // per-test wall clock + exit code
  int st = 0; ::waitpid(p, &st, 0);
  if (!(WIFEXITED(st) && WEXITSTATUS(st) == 0)) {
    ++fails;
    ::fprintf(stderr, "FAIL %s (status=%d)\\n", name, st);
  }
}
}  // namespace cis_harness
"""

MAKEFILE = """\
# Portable libcis test package -- generated by tools/gen_package.py.
#
#   make STDLIB=/path/to/stdlib/include      # build ./tests (static)
#   make run STDLIB=...                       # build, then run the suite
#   make clean
#
# STDLIB points at the standard-library include directory under test.  The
# defaults below build header-only libcis (the same flags as the conformance
# build); override CXX / STD / LIBCISFLAGS / LDFLAGS / LDLIBS to target a
# vendor toolchain instead, e.g.:
#
#   make CXX=g++ STDLIB= LIBCISFLAGS= EXTRA='-std=gnu++20 -fno-exceptions -fno-rtti'
#
# STDLIB is required to build, but not for `make clean`.
ifneq ($(filter-out clean,$(or $(MAKECMDGOALS),all)),)
ifndef STDLIB
$(error STDLIB is not set: point it at the standard-library include dir, e.g. \
make STDLIB=/path/to/libcis/include)
endif
endif

CXX        ?= g++-10
STD        ?= gnu++20
# header-only model: ignore the system C++ headers, use $(STDLIB) instead.
LIBCISFLAGS ?= -fcoroutines -nostdinc++ -I$(STDLIB)
# the package's own include tree: . (harness.h) + support harness + sibling test headers.
PKGINC     := -I. -Iinclude -Iinclude/support
CXXFLAGS   ?= -std=$(STD) -fno-exceptions -fno-rtti -O0 -w $(LIBCISFLAGS) $(PKGINC) $(EXTRA)
# static link, no default libs -- support.cpp + the C runtime supply everything.
LDFLAGS    ?= -static -nodefaultlibs
LDLIBS     ?= -lpthread -lm -lc -lgcc -lgcc_eh

BUILD := build
GROUP_SRCS := $(wildcard groups/*.cpp)
GROUP_OBJS := $(patsubst groups/%.cpp,$(BUILD)/%.o,$(GROUP_SRCS))

all: tests

# operator new/delete glue must be an ARCHIVE: tests that bring their own
# operator new (libc++'s count_new.h) need the runtime's definitions to be
# archive members the linker only pulls when nothing else defines them.
$(BUILD)/libsupport.a: $(BUILD)/support.o
	rm -f $@ && ar rcs $@ $<

$(BUILD)/support.o: support.cpp | $(BUILD)
	$(CXX) $(CXXFLAGS) -c $< -o $@

tests: $(GROUP_OBJS) $(BUILD)/main.o $(BUILD)/libsupport.a
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(GROUP_OBJS) $(BUILD)/main.o \\
	    $(BUILD)/libsupport.a $(LDLIBS) -o $@

$(BUILD)/main.o: main.cpp | $(BUILD)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# per-group ADDITIONAL_COMPILE_FLAGS (target-specific GROUPFLAGS) are appended
# below this line by the generator.
$(BUILD)/%.o: groups/%.cpp | $(BUILD)
	$(CXX) $(CXXFLAGS) $(GROUPFLAGS) -c $< -o $@

$(BUILD):
	mkdir -p $(BUILD)

run: tests
	./tests

clean:
	rm -rf $(BUILD) tests

.PHONY: all run clean
"""


def apply_overrides():
    """Re-apply tools/test_overrides/ onto test/std (as run_files.py does), so
    the package picks up the hand-adapted forms regardless of transfer order."""
    if not os.path.isdir(OVR):
        return
    for dirp, _, files in os.walk(OVR):
        for fn in files:
            src = os.path.join(dirp, fn)
            dst = os.path.join(ROOT, "test/std", os.path.relpath(src, OVR))
            if os.path.exists(dst) and open(src).read() != open(dst).read():
                open(dst, "w").write(open(src).read())


def group_source(members, fnname):
    """A consolidated TU exposing `int fnname()` instead of main().

    Mirrors gen_groups.group_source: each member file's body is concatenated
    verbatim (it is already in its own namespace), its #includes are hoisted to
    the top and deduped, and quote-includes are re-anchored to test/std-rooted
    paths so they resolve against the package's include/ tree.
    """
    inc, seen, bodies, calls = [], set(), [], []
    for r in sorted(members, key=lambda r: r["file"]):
        filedir = os.path.dirname(r["file"])
        body = []
        for ln in open(os.path.join("test/std", r["file"]), errors="replace").read().splitlines(True):
            if re.match(r"\s*#\s*include\b", ln):
                ln = G.resolve_quote_include(ln, filedir)
                if ln.strip() not in seen:
                    seen.add(ln.strip())
                    inc.append(ln if ln.endswith("\n") else ln + "\n")
            else:
                body.append(ln)
        bodies.append("".join(body) + "\n")
        if r["kind"] == "run" and r.get("entry"):
            calls.append(
                f'  cis_harness::run([]() -> int {{ return {r["entry"]}; }}, "{r["slug"]}");')
    return ("".join(inc)
            + '\n#include "harness.h"\n\n'
            + "".join(bodies)
            + f"\nint {fnname}() {{\n" + "\n".join(calls) + "\n  return 0;\n}\n")


def copy_includes(dst_inc):
    """Copy every non-.cpp file under test/std (support/ harness, sibling test
    headers, locale/filesystem data) into the package's include tree, preserving
    relative paths so the hoisted quote-includes resolve."""
    src_root = os.path.join(ROOT, "test/std")
    for dirp, _, files in os.walk(src_root):
        for fn in files:
            if fn.endswith(".cpp"):
                continue
            src = os.path.join(dirp, fn)
            rel = os.path.relpath(src, src_root)
            if rel == "manifest.json":
                continue  # the build graph's index, not a test input
            dst = os.path.join(dst_inc, rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)


def main():
    out = "package"
    apply_excl = False
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--out" and i + 1 < len(args):
            out = args[i + 1]
            i += 2
        elif args[i] == "--apply-exclusions":
            apply_excl = True
            i += 1
        else:
            sys.exit(__doc__)

    if not os.path.exists(MANIFEST):
        sys.exit(f"{MANIFEST} not found -- run the transfer first "
                 f"(see README section 3): ninja -f build/build.ninja")

    apply_overrides()

    excl = set()
    if apply_excl:
        import json
        excl = {k for k in json.load(open("tools/exclusions.json")) if not k.startswith("_")}

    groups = G.load_groups()
    # keep only groups that still have a runnable test after exclusion filtering
    kept = {}
    for d, members in groups.items():
        ms = [r for r in members if r["file"] not in excl
              and r["kind"] == "run" and r.get("entry")]
        if ms:
            kept[d] = ms

    out = os.path.abspath(out)
    gdir = os.path.join(out, "groups")
    idir = os.path.join(out, "include")
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(gdir)
    os.makedirs(idir)

    # group TUs + the list of run_group entry points
    fns = []
    ntests = 0
    for d in sorted(kept):
        key = G.gkey(d)
        fn = f"run_group_{key}"
        fns.append(fn)
        ntests += len(kept[d])
        open(os.path.join(gdir, key + ".cpp"), "w").write(group_source(kept[d], fn))

    # harness + main driver
    open(os.path.join(out, "harness.h"), "w").write(HARNESS_H)
    decls = "".join(f"int {fn}();\n" for fn in fns)
    runs = "".join(f"  {fn}();\n" for fn in fns)
    open(os.path.join(out, "main.cpp"), "w").write(
        '#include "harness.h"\n\n'
        + decls
        + "\nint main() {\n"
        + runs
        + '  ::fprintf(stderr, "DONE total=%d fails=%d\\n",'
          " cis_harness::total, cis_harness::fails);\n"
        + "  return cis_harness::fails ? 1 : 0;\n}\n")

    # support glue + include tree
    shutil.copy2(os.path.join(ROOT, SUPPORT_CPP), os.path.join(out, "support.cpp"))
    copy_includes(idir)

    # Makefile, with per-group ADDITIONAL_COMPILE_FLAGS as target-specific vars
    flag_lines = []
    for d in sorted(kept):
        key = G.gkey(d)
        fl = sorted(set(f for r in kept[d] for f in r.get("flags", [])))
        fl = G.backend_flags(fl, "libcis")  # translate clang spellings for g++
        if fl:
            flag_lines.append(f"$(BUILD)/{key}.o: GROUPFLAGS = {' '.join(fl)}")
    makefile = MAKEFILE
    if flag_lines:
        makefile += "\n" + "\n".join(flag_lines) + "\n"
    open(os.path.join(out, "Makefile"), "w").write(makefile)

    print(f"{out}: {len(kept)} group TUs, {ntests} tests")
    print(f"  build with:  make -C {os.path.relpath(out, os.getcwd())} "
          f"STDLIB=$(pwd)/include && {os.path.relpath(out, os.getcwd())}/tests")


if __name__ == "__main__":
    main()
